### ISSUE TITLE
Vertical + images[] starts at image 7

### ISSUE THREAD

**Issue by uthne** [pisi/Reel#103]
When using 'vertical:true' with  images array  the reel starts at frame (image) number 7 and continue past the end of the array with image url "undefined".

**Comment by pisi** [comment]
Thanks for the report. Will look into this issue.

**Comment by pisi** [comment]
I've put together a test, which confirmed this issue in latest stable 1.1.4. The frame inexplicably traverses to the second frames stack (the stack's default footage is 6, hence the frame 7 (1+6).

With the same test I was also able to confirm this issue being gone from the current [beta](/pisi/Reel/tree/v1.2beta).

@uthne Can you please give the [1.2 beta](/pisi/Reel/tree/v1.2beta) a shot and verify my observation?

**Comment by pisi** [comment]
@uthne, can you please confirm this issue you reported is gone from the current [development](/pisi/Reel/tree/development) branch? It will help me to release the new 1.2. Thanks.
