### ISSUE TITLE
FEATURE REQ: Listeners

### ISSUE THREAD

**Issue by fishnyc22** [pisi/Reel#104]
Hey there. I love this plugin. Its awesome!

I would love to be able to add listeners (or is it currently possible?) to the reel that listens for a change and returns the current index number. I'm using an image sequence loaded in with the images[] array but would love to know which image the user is on so I can show or hide other elements on the page. 

Is there a way to get the current image the reel is showing? 

Thanks

**Comment by pisi** [comment]
Thanks! :)

Reel is completely event-driven, so you can bind listeners to anything that happens inside easily. Especially the key event for you will be `"frameChange"`, which gets triggered every time a different frame is used. I recommend you to use the current [v1.2beta](/pisi/Reel/tree/v1.2beta), where this is more straightforward:

``` js
$('#your_image').bind('frameChange', function(e, frame){
    // `frame` parameter contains the current frame number
});
```

In current stable 1.1.3 it is executed a bit differently (and worse). It still can be done, but I suspect the reliability would be lesser tha in 1.2:

``` js
$('#your_image').bind('frameChange', function(e){
    var frame = $(this).data('frame');
    // `frame` data contains the current frame number
});
```

**Comment by fishnyc22** [comment]
That's awesome. Thanks so much for the tips! Gonna try it out today.

Another quick questions I'm using those frames numbers to show reveal different divs containing instructional text. But the text overlays the image and interferes with the swiping. (this is a webkit only web app). I tried disabling touch on those docs with the proper webkit calls but it sill interferes with the swiping. Any idea how I can prevent that?

Thanks again for the help. 

Dave

**Comment by pisi** [comment]
Well then, I guess you can give a shot to a new feature of 1.2 - [annotations](/pisi/Reel/wiki/Annotations) - there's a real chance it will help with that. In 1.1.3 this was problematic, but now in [1.2beta](/pisi/Reel/tree/v1.2beta) annotations are rendered inside Reel's outter wrapper, to which all events are bound, and this arrangement allows for the swiping.

In the beta stage now there are [some examples with annotations](http://test.vostrel.cz/jquery.reel/example/) (marked in the list with *) and a [wiki howto page](/pisi/Reel/wiki/Annotations) to help with setting it up.

Please, let me know what you think about this new feature.

**Comment by fishnyc22** [comment]
I was looking into Annotations in the beta but wasn't sure if it was the right fit for me because I want my labels to FADE IN.  Is that possible with the annotations? 

Thanks again. I'll do some more research on it. 

regards, 

Dave

**Comment by fishnyc22** [comment]
Hey Petr, 

Thanks again for the suggestion of using the beta version. I'm trying to get my projecting working with it and getting the current frame using the code below but it always returns undefined. any idea why?

$('#swiper').bind('frameChange', function(e, frame){
   console.log(frame);
});

Any help is appreciated. 

Thanks

Dave

**Comment by pisi** [comment]
Dave, I'm sorry, looks like I misguided you a bit. The binding is a little bit awkward because of backwards compatibility with 1.1.3 and I tend to see the clean version and sometimes forget. The working binding should look like this:

``` js
$('#swiper').bind('frameChange', function(e, depr_frame, frame){
    console.log(frame);
}
```

First argument the handler receives is the event object as usual. The second one is reserved for the deprecated usage of `"frameChange"` - it will always be `undefined` unless you trigger `"frameChange"` yourself. And finally, the third one is the actual frame pulled from the data on change.

Sorry once again.

**Comment by Medjeti** [comment]
Hey Petr,

Thanks for an awesome plugin and great feedback!

I too am trying to get the frameChange event working. I'm using the v1.2beta (which by the way had some issues with jQuery 1.5.1) and the event is firing jsut fine.
However, the frame it reports seems to be a bit arbitrary - often a higher number than my total number of frames. 
I experienced the same behavior using v1.1.3.

Any idea what I can do to make this work?

Thanks in advance,
Mikael

**Comment by pisi** [comment]
@Medjeti what kind of issues with the jQuery 1.5.1?

To your other problem: the frame is fed to the `"frameChange"` event right after it has been stored into the data, which means the normalization of the value took place already. With the current 1.2 design it's fairly improbable to get a value higher than the total number of frames (with the 1.1 design this was entirely possible). Can you make a [jsfiddle](http://jsfiddle.com) of your code for me so I can see it? Thanks.
