### ISSUE TITLE
Image loading Completed Callback

### ISSUE THREAD

**Issue by juaniquillo** [pisi/Reel#107]
Is there a way to know when the script has finished loading the images, like a callback I can pass to the plugin?

**Comment by pisi** [comment]
Yes, you bind a handler to `"loaded"` event:

``` js
.bind("loaded", function(){
   // handler code
})
```

**Comment by juaniquillo** [comment]
thank you. I'll give it a try

**Comment by juaniquillo** [comment]
Hi again pisi. First of all, I didn't know if I should reopen the issue of not but I have the following question:

I used the code you gave me but it just tells me when the image in the DOM loaded. I'm passing an array of images to the plugin and I would like to know when all the images are loaded and available. I know the preloader offers a visual indication to the user, but I would like to execute a couple more actions after that happens. Please let me know if that's possible.

Thanks again.

**Comment by pisi** [comment]
I've put together this [fiddle](http://jsfiddle.net/b9LPV/) to showcase the `"loaded"` event gets fired exactly once during the loading. That one is for the 1.2 (RC at the time), but the very same [fiddle with 1.1.4](http://jsfiddle.net/unebn/), apart from being less talkative, it yields the same result.

I think you must be doing something wrong there in your code. Please feel free to fork any of the above fiddles and tailor your failing case for me to see. Thanks

**Comment by juaniquillo** [comment]
I think the problem might have do with me doing the testing on my localhost instead of online. I'll try again. By the way, is there any documentation about all those events? I tried the plugin's page and couldn't find anything about that.

Thanks for the demo.

**Comment by pisi** [comment]
http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html
