### ISSUE TITLE
Can this plugin be bound to the window scroll event?

### ISSUE THREAD

**Issue by mtwallet** [pisi/Reel#108]
It would be nice  if the plugin could be bound to the window scroll event in some way. So when the user scrolls down the page the plugin advances 1 frame for say every 10px scrolled, if the user scrolls up the animation is reversed.

What do you think?

**Comment by pisi** [comment]
I don't see any obstacle in the way. If you bind to `window`'s `"scroll"` event, get the scrolled distance, translate it into frames for example and set it back with `.reel("frame", new_frame)`. There also are `"stepLeft"` and `"stepRight"` events you can trigger and they will advance Reel with one frame.

The above applies to [v1.2beta](/pisi/Reel/tree/v1.2beta). In [1.1.3](/pisi/Reel/tree/1.1.3) you can change frame with `.trigger("frameChange", new_frame)`

**Comment by mtwallet** [comment]
Hi Pisi, I have created a demo which relates to your suggestion above (http://clients.majestic-interactive.co.uk/majestic/). The piece of code I have written to achieve to get the scroll value and translate the value is quite simple:

```
$(window).scroll(function()
{
    windowScrollCount   = $(this).scrollTop();
    animationFrame      = Math.round(windowScrollCount / 100);
});
```

This gives me 1 frame per 100 pixels scrolled but the results are not what I expected. Am I using the correct method in 'frame'?

**Comment by pisi** [comment]
No you're not. You see, `.reel()` has both constructing and data access purpose depending on argument(s) given.
- `.reel( [options] )`<br>The constructing is triggered either by an object of options or by no argument at all. This is what you do once to start and preload Reel.
- `.reel( data_key )`<br>The read data access mode is triggered by string as an argument. This way you can read Reel's internal data.
- `.reel( data_key, value )`<br>The write data access is triggered by having two arguments - first a string and second a value. This way you change data and a corresponding change event is triggered if the value differs from the last value.

You want it this way instead:

``` js
$('#image').reel(
{
    frames:      35
});
$(window).scroll(function()
{
    var windowScrollCount   = $(this).scrollTop();
    var animationFrame      = Math.round(windowScrollCount / 100);
    $('#image').reel("frame", animationFrame);
});
```

**Comment by mtwallet** [comment]
Hi Pisi, I understand now. This really does give endless options for using the plugin. Thanks for all your help I appreciate it. I'll post you a link of our site using this technique when its ready if you're interested?

**Comment by pisi** [comment]
Sure I'm interested! :)

**Comment by mtwallet** [comment]
Hi Pisi, Hope you are well? I am trying to use the new sequence method in combination with the above but cannot get an animation. Its strange I have set it up correctly and I am getting no console errors. If I write the images by hand it works just fine. I wonder if you can take a look and see what is occuring? (http://clients.majestic-interactive.co.uk/majestic/)  Many thanks.

**Comment by pisi** [comment]
Let me clarify two things here:
1. There's no `sequence` option in 1.2rc. It some time in the development versions, but it has been merged to be an alternative notation of already existing `images` option. Value is the same, only the name of option is different.
2. The `suffix` is applied only for sprites when the `src` is used as a base for sprite filename. `suffix` doesn't play any role for sequences of individual images and it is not added `images`, where you must specify complete URLs.

_For example:_

``` js
    images: "images/imac/##.jpg"
```

_is equivalent of:_

``` js
    images: [
        "images/imac/01.jpg",
        "images/imac/02.jpg",
        "images/imac/03.jpg",
        "images/imac/04.jpg",
        ...
    ]
```

**Comment by mtwallet** [comment]
Thanks Pisi I appreciate the help.

**Comment by pisi** [comment]
No problem at all. Hope you get it working!

**Comment by mtwallet** [comment]
I'm getting there and I'm really beginning to understand the plugin. I'm sure I can fully achieve what I set out to do though. Binding the plugin works great for the most part but if you drag the image via the plugin itself then go back to scrolling the page the two are obviously out of sync. Have a look http://clients.majestic-interactive.co.uk/majestic/index.html its not perfect by any means from a design POV but the concept is working.
