### ISSUE TITLE
Can't get .trigger('teardown') or .unreel() to work

### ISSUE THREAD

**Issue by burnsting** [pisi/Reel#109]
I'm loading in some ajax content and a .js file that triggers the reel(). But I can't get the teardown or unreel to work. I tried both the beta and the current version.

It works the first time the content gets loaded and reel() gets called. But when I unload the content and reload it later, call unreel() and call reel(), the reel doesn't work. In the beta it somewhat works, you can click on the picture but not drag. I basically need to fully re-initialize. 

Any ideas?

An unreelall() function would be really helpful, since I technically won't know the div's ID.

**Comment by pisi** [comment]
You most likely call the `.unreel()` after the DOM content is actually gone (replaced). You need to call `.unreel()` or the `.trigger("teardown")` when the Reel instance is still present in the DOM.

There kind of is such function. There is a `$.reel.instances` jQuery collection, which points to all Reel instances document-wide. Calling:

``` js
$.reel.instances.unreel()
```

will teardown all Reels on page. You don't even need to know the div IDs ;)

**Comment by burnsting** [comment]
I'm sorry, I get the same results using $.reel.instances.unreel(). I even tried de- and re-activating the reel using timers, without changing the content.

.trigger("teardown") on the content does work in the stable version though.. I'm currently using that one and getting the div ID from class='jquery-reel-overlay'. Thanks for clarifying! :)

**Comment by pisi** [comment]
Hmm, don't know really. I don't have a failing example at hand and both automated and manual tests confirm the `"teardown"` event is working well. Can you maybe show me your setup, so I can see it fail? If it's not for public yet, send it to petr at vostrel dot cz.

**Comment by pisi** [comment]
You must be doing something wrong there in the implementation of the plugin, I'm afraid @bornst. I'd love to help, but I would need to see it. Until then, it's case closed.
