### ISSUE TITLE
change direction of rotation

### ISSUE THREAD

**Issue by helloRoger** [pisi/Reel#110]
Hi, thanks for ur great work!

I want to know if it is possible to change the direction of rotation after initialised the plugin.
I use .data( ) to make it start the animation
but no matter the position or negative value i used,
the image rotate in same direction.

Please help... thanks!!

**Comment by helloRoger** [comment]
"the position or negative value i used" shd be "the positive or negative value i used,"

**Comment by pisi** [comment]
Thanks for reporting this. It is a very valid point. The way it is supposed to be done is to trigger `"play"` event with new speed as a parameter:

``` js
.trigger("play", 0.6);
```

However it doesn't really work as it should be - a definitive proof, that even 1000+ tests don't ensure everything. It does not reflect in the boolean `"backwards"` data value, which is the one, which controls the direction. I will fix it today.

As a workaround, you can switch the `"backwards"` value manually in the data to reverse the direction:

``` js
.data("backwards", true) // Or `false` for that matter
```

See the working fiddle - http://jsfiddle.net/LWp2f/
