### ISSUE TITLE
Actions on certain frames

### ISSUE THREAD

**Issue by Strooi** [pisi/Reel#112]
Hi there,

Before I ask my question I must say this: The Reel plugin is fantastic.

That said, is it possible to call an action on a certain frame?
Say, you have a sprite-animation of a switch, when you swipe over the screen you flick the switch, when the switch is flicked a video starts to play.
That would be very useful.

Thank you in advance for your answer.

**Comment by pisi** [comment]
You can bind to the `frameChange` event. Reel fires this event every time the value of inner `frame` changes. _For example binding like this will show an alert every time the switch frame changes:_

``` js
.bind("frameChange", function(){
    alert( $(this).reel("frame") )
})
```

Say you have a sprite with two frames representing a simplest two-state switch with switch ON on the second frame. _This example will alert the state:_

``` js
.bind("frameChange", function(){
    var
        switched = $(this).reel("frame") == 2

    alert( switched ? "ON" : "OFF" )
})
```

Be sure to do it with [v1.2rc](/pisi/Reel/tree/development).
