### ISSUE TITLE
Unescaped URIs cause nothing to be displayed

### ISSUE THREAD

**Issue by jheeffer** [pisi/Reel#113]
Hey Petr!

First off: Super plugin, really helpful!

I stumbled upon a bug: when using a sprite and there is a space (' ') in the path to the image, it completes loading but doesn't show the reel. Instead it shows a white screen. I'm on windows using chrome. The bug also exists in Firefox. Didn't test other browsers.

It seems this does not happen when a path to a sequence is given with the 'images' option.

I uploaded a test-case here:
http://jasperheeffer.nl/reel_test/

I guess the bug is in the fact that the background-image-url of the img-element is not in quotes. 
I tried fixing it myself but my js-skills are not up to par with your code yet ; ). Hope it's an easy fix!

Thanks again for you work,
Jasper

**Comment by pisi** [comment]
Good point, @jheeffer! Valuable feedback. Fixed that issue, please confirm with [1.1.4-devel](/pisi/Reel/tree/development). Thank you for improving Reel!

**Comment by pisi** [comment]
Here's a [fiddle](http://jsfiddle.net/zWMkc/) of it.

**Comment by jheeffer** [comment]
Hi Petr, it does work, but not perfectly

I forked your fiddle: http://jsfiddle.net/nfU9x/

I suppose your re-encode is not perfect.

**Comment by pisi** [comment]
The re-encode does all it can to fix an unsafe URI, but there are some ground rules and free-floating `%` is a bit too much, man ;)

**2.4. Escape Sequences** of [RFC 2396](http://tools.ietf.org/html/rfc2396):

> Because the percent "%" character always has the reserved purpose of being the escape indicator, it must be escaped as "%25" in order to be used as data within a URI.

Your URL is not valid:

``` js
decodeURI("http://jasperheeffer.nl/reel_test/test%folder/sprite.jpg")
// throws "URI Error"
```

If the `%` is in the name of the folder, you need to use:

``` js
"http://jasperheeffer.nl/reel_test/test%25folder/sprite.jpg"
```

Updated fiddle - http://jsfiddle.net/nfU9x/1/

This aged but still valid [stackoverflow answer](http://stackoverflow.com/questions/497908/are-urls-allowed-to-have-a-space-in-them) nicely explains what can be used in the URL.
