### ISSUE TITLE
Is this compatible with a spherical Image?

### ISSUE THREAD

**Issue by jessepinuelas** [pisi/Reel#114]
Love your product! I was wondering if It was compatible with a spherical image.

**Comment by pisi** [comment]
Thanks! It is not right now. Sphericals involve CSS3 3D transformations and that is still far from being cross-browser. I would love to support them one day though. Maybe if I'd have one such spherical panorama image at hand, ... ;)

**Comment by jessepinuelas** [comment]
Done, I would love to contribute to that. Where would you like me to put the spherical assets?

**Comment by pisi** [comment]
Cool :) Greatly appreciated! The easiest will be mail it to `petr at vostrel dot cz`. Looking forward!

**Comment by iditude** [comment]
Wait, I did this!! 

The trick is to use a third party software that breaks your spherical image into several flat ones! This soft is brilliant and does correct for spherical parts!

Have a look here : http://webuser.fh-furtwangen.de/~dersch/mp/MotionPanoramas.html

Cheers

**Comment by pisi** [comment]
That's my kind of music! Thanks for the link, @iditude. This way it sounds very feasible. The only thing I'm missing right now, is some spherical image to play with. @jessepinuelas? ;)

**Comment by iditude** [comment]
Hum... Google images, search for "spherical image" :-) Seriously, plenty of those available!

By the way, configuring the script for the software to break images was not that intuitive... Thus I used this link to get a better understanding:

http://wiki.panotools.org/PTStitcher#Example_Script (same author, thus same syntax)

Also, the soft won't name the images with the zero. I think reel wats images such as 001.jpg 002.jpg 003.jpg

The soft names them 1.jpg 2.jpg and so on.

I guess a batch rename solution will easily fix that...

**Comment by pisi** [comment]
You got me there, bud :D I was just trying to embrace cooperation since Jesse offered some.. OK, I'll google ;) Thanks for the example script. That sure may come in handy.

**Comment by iditude** [comment]
Just tried and it worked perfectly... The renaming was a pain though, because the soft starts at zero and reel wants the first frame to be 1. Plus the leading zero thing...

Thus I created a small php script to rename the files ONCE... Please do not use it twice as unexpected results might appear! 

Hope this helps...

Cheers

``` js
<?
$dir='public/examples/pano1/'; //with end slash
$fileext='.jpg';
$numberchar='4'; // format of output, for example 0056
$numberadd = 1; //if need to add numbers, for instance file 1.jpg becomes 002.jpg, useful if need to start at 1 and not 0

  function getDirectoryList ($directory) 
  {

    // create an array to hold directory list
    $results = array();

    // create a handler for the directory
    $handler = opendir($directory);

    // open directory and walk through the filenames
    while ($file = readdir($handler)) {

      // if file isn't this directory or its parent, add it to the results
      if ($file != "." && $file != "..") {
        $results[] = $file;
      }

    }

    // tidy up: close the handler
    closedir($handler);

    // done!
    return $results;

  }





  foreach (getDirectoryList($dir) as $b) 

 { 

$numberfile = intval(str_replace($fileext, "", $b)) + $numberadd; 

$numberfilenew = str_pad($numberfile, $numberchar, '0', STR_PAD_LEFT);
 $newname = $numberfilenew . $fileext;
 print("Renamed " . $b . " to " . $newname . "<br/>");

 //actual rename
 rename($dir . $b, $dir . $newname);
 } 


?>
```
