### ISSUE TITLE
using the images:[] and iPad

### ISSUE THREAD

**Issue by closdesign** [pisi/Reel#116]
We tried using your example of using the images:[] and our example will not work on iPad. 
Your example here http://test.vostrel.cz/jquery.reel/example/object-movie-direct-sequence/index.html 
Does not work either.  It gives us blank or non existent or broken paths.

**Comment by pisi** [comment]
I'm viewing the link on my iPad1 right now and it's working just fine. Do you mean the Safari browser, right?

**Comment by pisi** [comment]
Closed for inactivity (works for me).
