### ISSUE TITLE
Panning with scrollbar event

### ISSUE THREAD

**Issue by jraack** [pisi/Reel#118]
Hi, 

I really like the reel plugin, a lot of options. Looks great.
I was wondering if it is possible to scrub by using a scroll event. Is there an method to do so?

thanks in advance. Ray

**Comment by pisi** [comment]
Thanks!

The possibility exists and it's even been done before. Nice example is the [Interactive Guide to Islamic Art Galleries at Met](http://www.nytimes.com/interactive/2011/10/30/arts/design/20111030-met-islamic-wing.html) feature of NYTimes.com. As you scroll down the page a mini-map pops out in the upper left corner indicating where you "are" in the real-world exhibition. This map is Reel.

You bind to `window`'s [`.scroll()`](http://api.jquery.com/scroll) event and each time it fires translate its [`.scrollTop()`](http://api.jquery.com/scrollTop) distance into frames and direct Reel to change into that `frame`.

_For example Reel:_

``` js
$("#image").reel({ ... })
```

_will be bound to advance by one frame per every 100 pixels scrolled:_

``` js
$(window).scroll(function(){
    $("#image").reel("frame", $(window).scrollTop() / 100)
})
```

Please note that the example code needs [v1.2](/pisi/Reel/tree/v1.2rc).

**Comment by jraack** [comment]
Thank you for your reply,
It is appreciated.
