### ISSUE TITLE
Image bounce up and down in Chrome

### ISSUE THREAD

**Issue by mtwallet** [pisi/Reel#123]
Hi Pisi, I am getting the same issue as another user in Chrome 18.0.1025.168 (lastest version) on a Mac - OS is Lion. The whole image appears to bounce up and down over time as the plugin advances through the frames. Strangely this only happens when run on my localhost (MAMP) or on a live web server not when the example is run from my desktop?! I have uploaded an example here - http://clients.majestic-interactive.co.uk/majestic/object-movie-clockwise-sprite/index.html

I have copied the example from your demo, I haven't altered it in any way. The demo works fine in other browsers I have tested. Any ideas?

**Comment by pisi** [comment]
Hi, by how much does it bounce? I'm unable to reproduce myself. Maybe you have your browser zoomed in (font size enlarged)? That could cause problems potentially for sprites like the one from example manifesting itself as 1 to 3 pixels offset on certain frames.

**Comment by mtwallet** [comment]
You are right Pisi I had the zoom level set to something other than default. Sorry to waste your time on this one. I have another issue with binding the plugin to the window scroll event can you reopen it?

**Comment by pisi** [comment]
No problem. It is fairly unfortunate, that (apparently) the enlarged dimensions of the DOM don't match the same enlarged dimensions in CSS background positioning causing the shifting you experienced. Something I can not find any cure for.. The only way how to avoid it is to abandon sprite and use sequence instead (sequences doesn't deal with CSS, so they are free of this problem).
