### ISSUE TITLE
Disabling stepping with `steppable` option

### ISSUE THREAD

**Issue by feuerballer** [pisi/Reel#126]
In line 812 ("jquery.reel.js"):

wrong:

``` js
opt.steppable || $overlay.unbind('click.steppable');
```

correct:

``` js
opt.steppable || $overlay.unbind('up.steppable');
```

**Comment by pisi** [comment]
Oh, wow, thanks Florian! :) How could I have missed that..

**Comment by pisi** [comment]
The fix is in the [development](/pisi/Reel/tree/development) branch. Please verify. And again, thank you very much for spotting it, hope it didn't cause you any headache ;)
