### ISSUE TITLE
add callback option to sync reel with custom code

### ISSUE THREAD

**Issue by sebhaase** [pisi/Reel#127]
Hi,
I added 

tick_callback: undefined  // call after a tick has been handled

in line 101 ((   last entry in  // Options defaults  <br> def:   ))

and 

if(opt.tick_callback) opt.tick_callback();

in line 366 (( last line in  tick: function(e){   ))

This worked for me well to plug in a custom function that sync a div css to the current postion in a panorama ....

Thanks for reel,

Sebastian Haase

**Comment by pisi** [comment]
Well, you can bind to the driving `tick.reel` event yourself without any changes in Reel. There's just one shared ticker running on `document` level and individual Reel instances on page bind to that event, so you can bind your callback to it too.

``` js
$(document).bind("tick.reel", function(){
    // your callback every tick (36 times per second!)
});
```

But of course in terms of syncing it is much better to bind to instance's [`frameChange`](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Changes) event directly as you receive it only when a frame is changed or to similar `fractionChange`, which occours on every manipulation with Reel (even if it doesn't actually change the frame).

``` js
$your_reel_instance.bind("frameChange", function(){
    // your callback every frame
});
```

**Comment by sebhaase** [comment]
thanks for the reply.  I will try it your way, looks better....

On Wed, Jun 13, 2012 at 11:33 AM, Petr Vostřel
reply@reply.github.com
wrote:
