### ISSUE TITLE
Multi-row Stitched Reels

### ISSUE THREAD

**Issue by stiliyan** [pisi/Reel#129]
Would it be possible to add support for multirow reels where stitched images represent the rows?

**Comment by pisi** [comment]
As right now `rows` and multi-row setups in general are limited only to framed setups, and are completely ignored by stitched setups, this feature will sure even things up a bit. Nice one :)

**Comment by pisi** [comment]
Hi @stiliyan, I finally git to your nice feature request and managed to pull off the majority of it. I know it took very long.. Some tuning is still required, but essentially it is functional now. Please see the dedicated [**stitched-multirow** branch](/pisi/Reel/tree/stitched-multirow) for details. There are two ways to setup essentially the same situations and both are covered by [panorama-multi-row-stitched](/pisi/Reel/tree/stitched-multirow/example/panorama-multi-row-stitched/) example. It works quite well and every aspect of the functionality is covered with unit tests, but I would still like to ask you to grab the code and do some testing if it fits your expectations.

I used your photos for both examples, but I feel it would be less confusing to have unique photo for each example. Can you spare one more? ;)

Cheers!

**Comment by pisi** [comment]
Merged into [development branch](/pisi/Reel/tree/development) awaiting release

**Comment by pisi** [comment]
Merged into [master](/pisi/Reel/tree/master) and **included in today's [version 1.2.1](/pisi/Reel/tree/v1.2.1)** release.
