### ISSUE TITLE
short freezes after reel load (desktop short and ios a little longer)

### ISSUE THREAD

**Issue by RonnyNeu** [pisi/Reel#130]
Hi there,
i have a little problem with the reel loading, when sie reel is loaded it stops and disappears for one frame or so...
on the desktop (firefox, opera, etc) it is barely noticable but on the Ipad (i have tested it on the new ipad) its a little bit longer, the rest works perfectly fine:-D i quess it makes this issue look a little bit bigger for me than it is, but i would be glad if you could help me fix it:-D

you can find my project here:
http://offline.ronny-neumann.de/

Thanks
Ronny

**Comment by pisi** [comment]
I'm unable to reproduce... Your project loads and transitions from still image to Reel instance seamlessly without a blink on my iPad. Does this issue still bother you? Or did the usage of RC resolved it maybe? Please let me know. Cheers.
