### ISSUE TITLE
Image gets dragged when clicking to view panorama (in facebook tab iframe)

### ISSUE THREAD

**Issue by msb006** [pisi/Reel#131]
I have used the reel in a virtual tour on a facebook tab and have ran across an issue when viewing on internet explorer or firefox. When you try to drag the cursor to get a 360 degree view it just drags the image. I believe this has something to do with it being in an iframe, and not a facebook restriction because it works fine in safari. Example of the issue below:

Click on one of the locations to get to an interior page with the 360 panorama reel:
https://www.facebook.com/LaSalleAcademyAlumni/app_326222480795066

Interestingly, the source for the iframe works fine:
https://secure.bboyledesign.com/lsa_vtour/alumniwalk.html

Any insight as to why the reel would not work in firefox and ie when being viewed in an iframe? Thanks.

**Comment by msb006** [comment]
I have since made the links on the main page open in target="_blank", taking you outside the iframe when viewing the pages with the reel, but here is the error that was causing the issue when viewing the reel in an inframe: 

Issue was in jquery.reel-min.js

Unsafe JavaScript attempt to access frame with URL https://www.facebook.com/LaSalleAcademyAlumni/app_326222480795066 from frame with URL https://secure.bboyledesign.com/lsa_vtour/alumniwalk.html. Domains, protocols and ports must match.

**Comment by pisi** [comment]
This is known limitation of version 1.1.4 (1.1.x in fact), where both the hosting page and the iframe content need to conform to same domain policy. This will be resolved in 1.2. It IS resolved in fact, you can try the [v1.2rc2](/pisi/Reel/tree/v1.2rc2) if that will work for you better.
