### ISSUE TITLE
Not compatible with Windows Phone

### ISSUE THREAD

**Issue by Versitek** [pisi/Reel#132]
Doesn't work at all with windows phone.  Just a still image.

**Comment by pisi** [comment]
This is unfortunate, but entirely possible as I don't have such a device at hand to test :/ Are there any emulators for Windows Phone platform?

Apologies for the incovenience. So far Reel ([v1.2rc2](/pisi/Reel/tree/v1.2rc2)) supports devices by Apple and Blackberry and those powered with Android 2.3 or higher.

**Comment by pisi** [comment]
This also duplicates #67. Please add any new findings to that ticket.
