### ISSUE TITLE
Need help forward / backward button

### ISSUE THREAD

**Issue by iditude** [pisi/Reel#133]
Hello guys,

I’ve been trying to implement both forward and backward buttons, but can’t get it to work.

I’ve been reading through the issues to get examples, but still lack a bit of understanding !

Here’s my code for a simple forward button:

I first place a div for the buttons :

``` html
<div id="controls"></div>
```

then the script :

``` js
$(document).ready(function(){
                  $('#image').reel({
                      frames: 32,
                      steppable: true,
                      footage: 4,
                      sensitivity: 70,
                      saves: true,
                      indicator: 0,
                      monitor: 'frame'
});
              });

$('#controls')
    .append($('<button/>', { text: 'next' }).click(function(){ $('#image').reel('frame', $('#image').reel('frame') +1); }))
```

I even tried to do `alert($('#image').reel('frame'));` but it doesn’t return as a number but as an object.

Any ideas ?

Thanks a lot

**Comment by pisi** [comment]
Hello,

be aware, that using `.reel()` for data retrieval (like you do in the alert) is supported only in the upcoming version 1.2. Either use [v1.2rc2](/pisi/Reel/tree/v1.2rc2) or for 1.1.x use `.data('frame')` instead.

Also, in the RC there is a new stepping feature, which might interest you. First, it makes left/right half of the image be clickable and advance by one frame each click. Second, it adds two new control events - `stepLeft` and `stepRight`, which you can trigger from outside and Reel will step one frame in given direction. _For example:_

``` js
$your_button.click(function(){
   $your_reel.trigger('stepRight');
});
```

Just remember, this is a 1.2 feature unsupported by 1.1.x

**Comment by iditude** [comment]
Prefect!

Thanks for the info...

For the one interested, I created the buttons as such:
- first create a blank div:

``` html
<div id="controls">&nbsp;</div>
```
- then code the buttons

``` js
$(document).ready(function(){

//init next et prev
var prev=0;
var next=0;

$('#controls')
    .append($('<button/>', { text: 'prev' }).click(function(){ 

    if (($('#image').data('frame') +1)>($('#image').data('frames'))) {
        prev=1;
        } else {
        prev = $('#image').data('frame') + 1;
        }

    $('#image').trigger('frameChange', prev )

    }))
    .append($('<button/>', { text: 'next' }).click(function(){ 

        if (($('#image').data('frame') -1)<=0) {
        next=$('#image').data('frames');
        } else {
        next = $('#image').data('frame') - 1;
        }


    $('#image').trigger('frameChange', next )

    }));

   });       
```

You'll notice that I tweak the frame number so it goes around completely.

Beware, that probably messes up multi row images!

pisi, thanks a lot for your quick answer. I'll give 1.2 a go when it's ready!

Btw, did you plan a stepUp and stepDown button? That way reel could entirely play spherical images with controls!

Cheers

**Comment by pisi** [comment]
Yeah, `stepUp` and `stepDown` are definitely on the plate now ;) Btw. the [v1.2](/pisi/Reel/tree/v1.2) is just out.

Thanks for sharing your code.

**Comment by iditude** [comment]
OK, 1.2 rocks!!!

I've modified my code to have a left, right, up and down button using 1.2...

I didn't have the courage to hack the actual js, so I created my own function in my page...

So here it is!

Same as before, create a blank div id'ed controls, then add the following script:

Btw, I couldn't figure out how to get the total number of rows... $('#image').data('rows'); gives me weird results...

``` js
var totalrow = 6;
var newframe=0;





$('#controls')

    .append($('<button/>', { text: 'Up' }).click(function(){

        if (($('#image').data('row') -1) >= 1) {

            newframe = $('#image').data('frame') - $('#image').data('frames');
            $('#image').trigger('frameChange', newframe )
        }
    }))
    .append($('<button/>', { text: 'Down' }).click(function(){

        if (($('#image').data('row') +1) <= totalrow) {

            newframe = $('#image').data('frame') + $('#image').data('frames');
            $('#image').trigger('frameChange', newframe )
        }
    }))
    .append($('<button/>', { text: 'Left' }).click(function(){ $('#image').trigger('stepRight') }))
    .append($('<button/>', { text: 'Right' }).click(function(){ $('#image').trigger('stepLeft') }));


});       
```

**Comment by pisi** [comment]
Nice! Looks like this will land in 1.2.1 for sure ;)

Note, that in 1.2 you can now use `.reel()` for the data retrieval, but technically there's no difference from jQuery's `.data()` on reading, just an aesthetic preference ;) Writing of values should however be done with `.reel()` only to get the associated events going.

And yeah, you are right about `.data('rows')`. It is an inappropriately chosen name for another internal variable actually referring to number of "lines" in sprites. You can get the total number of rows with:

``` js
.data('options')['rows']
```

Actually, `.data('options')` returns back the same hash you supplied to `.reel()` previously on initialization.

**Comment by iditude** [comment]
Cool! Thanks for the tip!

**Comment by Neelam2** [comment]
Hey..ist there any examlpe how to use it in reel.js

**Comment by pisi** [comment]
I've put up a little one - http://jsfiddle.net/pg8JY/ - and will add this to regular examples.

**Comment by Neelam2** [comment]
Hi,

Thanks a lot.. And how can i create an Button 
to show only the First picture by clicking these Button ???

**Comment by pisi** [comment]
You basically need to call `.reel('frame', 1)` on the running Reel instance. Please see the documentation on [data API](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Data) especially the [write access](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Write-Access).

**Comment by pisi** [comment]
@Neelam2 You are making elementary mistakes and your issue is starting to grow more complex at the same time. It would be best if we stop clogging this issue (fixed nearly a year ago) and you open new issue for you. But first, please, read as much of the [documentation](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html) as you can digest. Thank you!
