### ISSUE TITLE
Rotate once on load then stop

### ISSUE THREAD

**Issue by SNeilson** [pisi/Reel#134]
Hi,

I've looked through the Wiki but I've not managed to figure out how I can get my sequence of images to rotate once on page load then stop.

Any help would be greatly appreciated, if it helps I'm running v1.2.

Thanks

Stuart

**Comment by pisi** [comment]
Hi, this is called _opening animation_ and its options are described in the [documentation](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#Opening-Animation) [documentation]. See http://test.vostrel.cz/jquery.reel/example/object-movie-non-animated-sprite/ how it's done. Key is to NOT use `speed`.

**Comment by SNeilson** [comment]
Thanks Petr that's solved it!
