### ISSUE TITLE
Ability to have different responsive sizes

### ISSUE THREAD

**Issue by HandHugs** [pisi/Reel#135]
It would be really great if I could use CSS or something to make this option available at different sizes based on screen size - I tried to do it with straight CSS:

``` css
@media only screen and (max-width: 787px) {
  #my_image{width:450px; height:193px!important;}
}
```

which changes the 'window' size but not the size of the images within it. Any help / advice would be greatly appreciated.

**Comment by ssidorenko** [comment]
Hello, I stumbled on this issue too and made a quick fix, see my branch ( https://github.com/ssidorenko/Reel ) for the fix.

**Comment by pisi** [comment]
Nice work, people! Community fix ready some 9 hours after request has been placed 8) What a community! I love you guys :)

I guess there will be at least one more value, which would need to be adjusted for the new dimensions (`revolution` comes to mind first), but overall, this is a perfect start of a new feature!

@ssidorenko, Semion, would you like to join heads and work on this one with me in a pull request? It involves a separate branch and some small discussion about the new code (learn about [pull request procedure](https://help.github.com/articles/using-pull-requests/)) and we will be able to fine tune the code to make it fit for merge into Reel. Sounds good? If so, please go ahead and create new pull request from your fork and we'll "see" each other there ;)

Good job. Thank you!

**Comment by ssidorenko** [comment]
Hello, I've made the pull request. However, I'm far for being sure my code fits the Reel coding style, and I'd happily accept your advices concerning my code !

**Comment by HandHugs** [comment]
Sorry you guys, can you point out what I would need to change to get this working? is my css ok and i just switch out the reel.js for the one in your branch? Thanks so much for the help!!

**Comment by ssidorenko** [comment]
Yeah, just use the reel.js from my branch, but be aware that this is highly experimental, and IMO I think this change only works with separate pictures, not with sprites.

**Comment by pisi** [comment]
Good news, @HandHugs! I've just discovered a way to, if not actually responsively load smaller images, to at least responsively scale the whole Reel so that it fits on screen using the `zoom` CSS property. To scale to 1/2 of original:

``` css
@media only screen and (max-width: 500px) {
    #my_image-reel {
        zoom: 0.5;
        -moz-transform: scale(0.5);
        -moz-transform-origin: 0 0;
    }
}
```

There's a small gotcha however. Where isn't, right? ;) You have to apply the zoom on the `#my_image-reel` DIV, which automatically wraps your `#my_image` image.

There are two actually. The second is the absence of standardized `zoom` in Firefox, where you have to use their proprietary scale transform.
