### ISSUE TITLE
Setting up reel on a hidden div

### ISSUE THREAD

**Issue by parkersweb** [pisi/Reel#139]
Hi there,

Apologies if this has been covered elsewhere - I did search around but couldn't find anything...

I'm using Reel on an e-commerce website - and the 360 view is just one of a selection of product images.  That means that the div containing the reel image is hidden  on page load (i.e. the parent div is display: none) - but this causes reel to fail altogether.

I could trigger Reel when the 360 thumbnail is clicked (and the container is then made visible), but a) that means re-firing Reel repeatedly (and that seems to make Chrome behave unpredictably) and b) the pre-caching of the images doesn't start until the 360 is displayed.

Is this a known thing?  Is there a way I can work around it?

Thanks very much!

Andrew

**Comment by pisi** [comment]
You're right, preloading starts after Reel is initialized. I didn't have problems with initializing while being hidden yet, can you reproduce the bare issue with a [fiddle](http://jsfiddle.net) maybe?

Currently there isn't a way to make Reel initialize and preload, but not start until said. The currently preferred way is to call `.reel()` when showing the Reel image and call `.unreel()` on it when hiding it to show some other.

**Comment by parkersweb** [comment]
Hi 

Here's the issue I'm seeing as a jsfiddle:

http://jsfiddle.net/zk3kS/

I could be setting it up wrong of course :-)

Andrew

**Comment by pisi** [comment]
Actually, in the fiddle the Reel won't initialize even if the container is NOT hidden. What you were missing are dimensions of the image, which are mandatory. Just add `width` and `height` attributes to the image and you're set.

http://jsfiddle.net/zk3kS/1/

**Comment by parkersweb** [comment]
Ah - OK - I'd left those dimensions off because the site is adaptive - so the reel needs to vary in size depending on the size of the container at the time - that works OK when you call reel on the click event:

http://jsfiddle.net/zk3kS/4/

but not OK if you call it at DOM ready:

http://jsfiddle.net/zk3kS/6/

**Comment by pisi** [comment]
In that case, use [`attr`](http://jquery.vostrel.cz/reel#attr) option of `.reel()` to supply initial attributes for the image tag every time you call it.

``` js
.reel({
    attr: {
        width: 400,
        height: 300
    },
    ...
}
```

**Comment by parkersweb** [comment]
Ah - that works great - thanks!
