### ISSUE TITLE
Independent sensitivity

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#14]
Greg would like to split the current shared sensitivity option into two - one for dragging and one for wheeling.

**Comment by ghost** [comment]
its difficult to find a single value where both of the features work optimally, having em split would be awesome!

**Comment by pisi** [comment]
I have this issue targeted for the 1.2 milestone, but actually don't know how to tackle this one, since the aforementioned `sensitivity` property for setting up mouse sensitivity got deprecated in 1.1 and is completely gone in 1.2 and since the frequency of wheel events is hardware dependent and often differs greatly for different mice.

My question is: is this feature request still relevant and valid? It doesn't look like one to me..

**Comment by ghost** [comment]
I'd say this is still an issue. From the v1.1 I'm using, the mouse wheel is nice and smooth (not too sensitive) whereas when I scroll the image by dragging it with the mouse it is WAY too sensitive and difficult to use.

http://panorama.miernicki.com/reel.php
^ example

**Comment by pisi** [comment]
Thanky for the example! It helped me to realize there really is a disproportionality between drag and wheel. I believe this is caused by badly setup ratio used to interpret `revolution` setting for mouse wheel purposes (yes, my Apple Mighty Mouse's "touch wheel" might play a role in that).

I still don't think this private constant should be configurable by an option, but a correction of the ratio seems highly desirable. Right now it is 1:5 (wheel:drag), I tinkered with it a bit and came up with a new ratio of **1:12**, which does seem to better match the dragging setting (verified using a regular analog mouse wheel).

Greg, would you please care to give the new setting a shot and verify it for me? It would involve two steps:
1. remove the `revolution` option from your `.reel()` call,
2. edit [`jquery.reel.js`](/pisi/Reel/blob/master/jquery.reel.js#L504) on line 504 and change `0.2` to `0.0833`.

This should result in a wheel behavior you have currently in your example without affecting the sensitivity of the drag.

**Comment by ghost** [comment]
I wish Github would email me notifications... sorry took so long to see this.

Code changed and I definitely +1 your patch, the scroll and drag effect are much better now!

http://panorama.miernicki.com/reel.php

**Comment by pisi** [comment]
Perfect! Thanks :) Nice and smooth improvement then. That's the way I like it ;)

Merry Christmas, Greg!
