### ISSUE TITLE
"indicator" and "preloader" class names are misidentified in docs

### ISSUE THREAD

**Issue by albell** [pisi/Reel#141]
The class name for the "indicator" box is "reel-indicator", not "jquery-reel-indicator" as listed in the options page.

Similarly, the name for the preloader box is "reel-preloader", not "query-reel-preloader". 

Looks like they just got shortened, and the docs didn't get updated.

Wow, was this tricky to figure out! I had to watch the generated source very carefully and try to read it as it flashed onscreen. I'm sure it's buried in the source somewhere but I couldn't find it. It might help the next guy to change it in the docs. :)

**Comment by pisi** [comment]
Good point! Am very sorry for inconvenience. The docs have been updated, but looks like some stuff is still out of sync.

It is fixed now. Also please note, that you'll find a much better/complete documentation inside the package (`docs/jquery.reel.html`), which also happen to have a [section on class names](http://test.vostrel.cz/jquery.reel/docs/jquery.reel.html#CSS-Class-Names)

Thanks for reporting this!
