### ISSUE TITLE
Drag and move stops working after reload with ajax

### ISSUE THREAD

**Issue by HandHugs** [pisi/Reel#145]
I have reel installed and working on my site that uses ajax to navigate through parts of the site. When ajax loads the new content, I have it re-initiate the reel call, which works for everything EXCEPT the drag to move function - it still works on scroll, but not on click - any advice? I can't provide a working example until later this week, but maybe someone knows a quick answer?

**Comment by pisi** [comment]
Oh, I've completely missed your trouble. @HandHugs, I see you closed the issue. Did you manage to solve it for you?

**Comment by HandHugs** [comment]
I figured out my issue was that the script was repeated on the page so that's what was messing it up- I've been struggling with Ajax and reel loading but it is only my lack of JavaScript knowledge and not an issue with your plugin at all. Thank you very much for getting back to me!

Jessie Matanky
303-396-5452
mail@handhugs.com

**Comment by pisi** [comment]
Oh, OK. So glad you figured it out! Your Javascript knowledge is evidently growing fast :) Keep it up!
