### ISSUE TITLE
Uncaught TypeError: Object [object Object] has no method 'replace' 

### ISSUE THREAD

**Issue by arthuryeti** [pisi/Reel#146]
Hey,

I try to add reel plugin on my website, bug I have some bugs when I want drag the image.

Can you help me ?

Best Regards

**Comment by pisi** [comment]
First, please provide version of Reel (`$.reel.version`), version of jQuery (`$().jquery`) and what browser you're using and its version, so that I can actually help you. Thanks.

Second, I would bet this is duplicate of #140. @Atu Can you confirm?

**Comment by arthuryeti** [comment]
This is with 1.2 jquery.reel, and jquery 1.5.2

**Comment by pisi** [comment]
I see the error now, that definitely is not a duplicate. Sorry about that. Only advice I can give you right now is to notch up your jQuery at least to 1.6 (that I throughly tested now against and it should be just fine).

**Comment by arthuryeti** [comment]
I used jquery.reel 1.1 and it's working :)

**Comment by pisi** [comment]
Disregard the above commit. It should be a different ticket..

**Comment by pisi** [comment]
Ok, this last one really fixes this issue and makes Reel compatible with jQuery 1.5+ again. @Atu, can you please verify this for me? The [**development** branch](/pisi/Reel/tree/development) has this fix in. Thanks!

**Comment by pisi** [comment]
Merged into [master](/pisi/Reel/tree/master) and **included in today's [version 1.2.1](/pisi/Reel/tree/v1.2.1)** release.
