### ISSUE TITLE
clickfree IE7 and IE8

### ISSUE THREAD

**Issue by evertonalmada** [pisi/Reel#147]
Hello!

Please, Reel 1.2 clickfree doesn't work in IE7 and IE8?
I'm trying with jQuery 1.7.2

Can you help me?

Thanks!

**Comment by pisi** [comment]
Hi, sorry to hear that. Just tested it and it§s a bug indeed.

**Comment by pisi** [comment]
Fix for this is in the [**development** branch](/pisi/Reel/tree/development). Please give it a try and let me know. Thanks!

**Comment by evertonalmada** [comment]
It works! Thank you very much!

**Comment by pisi** [comment]
My pleasure :) Thanks for the verification!

**Comment by pisi** [comment]
Merged into [master](/pisi/Reel/tree/master) and **included in today's [version 1.2.1](/pisi/Reel/tree/v1.2.1)** release.
