### ISSUE TITLE
Switching between Reel images without a blink

### ISSUE THREAD

**Issue by matiasjaure** [pisi/Reel#148]
The problem is that we are have several reel image to use the same reel (different car colors) but we don't want the car to dissapear and appear again. Is any implementation of any kind of transition?

**Comment by pisi** [comment]
Reel itself doesn't provide any effects in between it not existing and existing.

But with a little work on your side, this is definitely possible. Please check out http://citan.mercedes-benz.com where further down the page, there is an "Exterior 360°" with wheels and paints changing with smooth transition.
