### ISSUE TITLE
image linking and mapping

### ISSUE THREAD

**Issue by pinolo2** [pisi/Reel#15]
Hi!
First of all, thanks for your job!

I'd like to know if it's possible to create a link or a mappable area into one or all the images I use into the Reel.

Thx in advance

Luca

**Comment by pisi** [comment]
Hey Luca,

such feature is widely requested, it is partly developed, but Reel doesn't have this feature yet.

Stay tuned!

.pisi

**Comment by pinolo2** [comment]
Thanks a lot for your reply ;)

Luca

**Comment by ardelean** [comment]
Hi .pisi,

I was almost ready to add this suggestion too...I find it even more useful than my previous suggestion concerning set/get rotation degree value.

Adorian

**Comment by pisi** [comment]
Adorian, if you care for such feature, please, vote for this issue.
