### ISSUE TITLE
Triggering the reel function programmatically

### ISSUE THREAD

**Issue by harshavarma** [pisi/Reel#150]
Hello,

This is more of a Feature Request / Help. Can you please give me an idea on how to programmatically trigger the reel function. Below is the usecase:

I have 2 windows where controls will be in one window and the animations are shown in the other window. Using window.postmessage(), i want to transmit the events across the windows and handle the relevant animation in the second window.

My plan is to bind custom event relay function to the 'down', 'pan' and 'lift' reel events. Then, in the second window, trigger the down, pan and lift reel events accordingly. Is this possible? 

Any help would be greatly appreciated.

**Comment by harshavarma** [comment]
Ok, answering my own question. RTFM.

I added a window.postmessage function to the 'frameChange' event and synced the frame in the second window. Thank you for this awesome plugin PiSi.

**Comment by pisi** [comment]
No problem at all. I'm glad you figured it out all by yourself. Kudos! :)
