### ISSUE TITLE
Performance problems when running 180 of 1920*1080 frames

### ISSUE THREAD

**Issue by harshavarma** [pisi/Reel#152]
Hi Pisi,

This is directly related to issue #106. That issue is already more than a month old, so starting a new one. I am having this issue almost 50% of the time.  Reel again works once the page is refreshed and fails on next refresh. Almost all alternate refreshes fail.

A few interesting things:
1. Reel will not fail while the Chrome console or Network tab is open.
2. When failing, the code doesn't even bother to execute. Even adding a breakpoint is of no use. It just skips this line.

jQuery Version: 1.8.2
Reel Version: 1.2
Chrome : Stable 22

URL: http://touch.cv.foxqa.com.au/

This url has content which is still in progress. Please click on the "Navigate to interactive page" link to load the application. Around 180 high-res images are being loaded, so please be patient. Just so that you know, this is not a website. A client-specific solution. Also, temporarily disable any pop-up blockers.

All the reel related scripts are in "Sandbox.js" and "touchscreen_functions.js". Please investigate.

**Comment by pisi** [comment]
Hi,

first of all, #106 is perfectly active thread ;) The problem there is the "sometimes" factor of the issue and especially the fact, that I've never actually experienced it to have chance to do the bug hunting.

Yours one is a bit different however, so good you created this new issue. I investigated a bit and I did experience what you describe. But this time I think the enormous amount of data you use there is causing this, quite naturally, frankly. You see you are using 180 images not one of them smaller than half a megabyte (typically around 600 kB). I will skip right over the 2 degree difference between frames and go straight into man, did you notice that overall these frames weigh 108 MB?! Those are fullHD 2 megapixel frames you use there, so somewhere around 360 MB of RAM only for storing decompressed frames. This is a serious weight for my MacBook and I can not imagine any touch device responding well to such load. I'm afraid for fullHD without hardware acceleration (like HD movies usually have) the throughput demand is simply too freakin high.

I would advice you two things:
- crop your images. Tightly box them so there's as little as possible wasted. I know there's the gridded floor, but cutting the empty building surroundings out, you'll save at least 50% of the size.
- lower the rotary resolution. 180 frames (one frame each 2 degrees) is crazy fine. Do every 5 degree or 72 frames, which is fine enough for a stationary object like building. This step alone would bring the weight down by further 60%.

Hope this helps. If not feel free to further comment or even reopen this issue. Thanks.

**Comment by harshavarma** [comment]
Hi PiSi, 

Thanks for the response. I know it seems ridiculous to load such high-res images, but that's the project requirement and i was actually about to post a fix for the issue. I think the issue is because of loading the Html content using AJAX and adding a 500ms setTimeout before initializing Reel fixed it.  So, your plugin is functioning just fine and you can be rest assured, it can handle any images that we throw at it.

The url i gave you is for a one-time install for a single client, and that too i'm storing all the images using Application Cache.

**Comment by pisi** [comment]
Good to know! Thanks for the update.
