### ISSUE TITLE
iPad freeze

### ISSUE THREAD

**Issue by bloc-d** [pisi/Reel#154]
I am in the process of creating a muti-row project using reel and noticed that when rotating on iPad/iPhone the image freezes every so often. I thought it was something I had done wrong so tested your example (http://test.vostrel.cz/jquery.reel/example/object-movie-multi-row-sequence/) and it does the same.
Any ideas?

**Comment by bloc-d** [comment]
I have been testing further and it seems to have something to do with the caching?
I am no expert, so cant overly explain but if I test with 'speed' set; when it freezes and I take my finger off - the anim starts, but if i try to use my finger again it does not read it unitl it has had time to catch up.
Does it have to dump and reset its cached images before it can continue?

Please help!

**Comment by bloc-d** [comment]
On further testing, it seems to be to do with the tempo, the 'laziness' doesnt seem to have an effect, if I lower the overall tempo so they are both set to '6' it seems to mend (or at least lessen) the problem.

Does the laziness work for ipads?

**Comment by bloc-d** [comment]
found it!! the iPad is not checked so is not included as lazy device, buts needs to be. you may want to update, when I updated the code it solved the issue:

line 1862:         lazy_agent:    /(iphone|ipod|ipad|android|fennec|blackberry/i,

hope this helps someone else, it took me ages to realise :(

**Comment by pisi** [comment]
Sorry for your trouble, iPad not being considered a lazy device is by design. It in fact is not as lazy as iPods and Androids. I've just reviewed the example linked on my iPad1 and it works without any glitch. Maybe I will be able to spot it on your example..
