### ISSUE TITLE
Iframe and clickfree:true - not working

### ISSUE THREAD

**Issue by fralla** [pisi/Reel#155]
When using it inside an iframe, and with clickfree: true, the reel-javscript shows an error "TypeError: qc is undefined". This error makes the script unusable.
Just by setting clickfree to false makes it work.
Any one else seen this error?

**Comment by pisi** [comment]
Hey, this is duplicate of already fixed #147. The fix however didn't made it into release just yet. Please grab the patched code from [development](/pisi/Reel/tree/development) branch.

I've made a little fiddle to showcase it working - http://jsfiddle.net/dAXZf/
