### ISSUE TITLE
Example of object movie with multiple annotations at once on single frame

### ISSUE THREAD

**Issue by landrvr1** [pisi/Reel#156]
Is Reel capable of having multiple annotations on screen at the same time?  Can't seem to get this to work so thought I'd better ask.  Tnx

**Comment by pisi** [comment]
Absolutely! In fact you can see one such right on [Reel's homepage](http://jquery.vostrel.cz/reel#demo), where an entire panorama of Moro Rock is annotated. All annotations are being rendered at all times and only switch visibility (and eventually position) based on current frame.

I will enhance one of object movie examples to showcase that for 1.2.1.

**Comment by landrvr1** [comment]
Hmm.  I can't get it to work.  I'm a complete noob, so you'll have to forgive my ignorance.  I can get the first annotation to show up, but nothing after.  Here's my code:

``` js
  annotations: {
    "spot": {
      x: "40%",
      y: 50,
      image: {
        src:    "spot.png",
        width:  50,
        height: 50,
        "spot2": {
          x: "10%",
          y: 40,
          image: {
            src:    "spot2.png",
            width:  50,
            height: 50,
          }
        }
      }  
    }
  }
```

Any help would be appreciated!

**Comment by pisi** [comment]
No problem. We all were noobs once.

I took the liberty to edit your post and properly format the object you posted. Little formatting goes a long way and this way the error will be very clear: **you nested `spot2` inside `spot`'s `image`, which is wrong**. All annotations need to be on the same level. It should look like this:

``` js
  annotations: {
    "spot": {
      x: "40%",
      y: 50,
      image: {
        src:    "spot.png",
        width:  50,
        height: 50
      }
    },
    "spot2": {
      x: "10%",
      y: 40,
      image: {
        src:    "spot2.png",
        width:  50,
        height: 50
      }
    }
  }  
```

**Comment by landrvr1** [comment]
Oh!  lol.  Tnx much for that.

**Comment by pisi** [comment]
Useful demonstration of multiple annotations rendered at once sits in the [Non-looping stitched panorama example](/pisi/Reel/tree/master/example/panorama-non-looping-stitched)
