### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by efdutra** [pisi/Reel#157]
Wont it be nice to play a sound while you scrool the mouse/finger on top of the image?

Like, when get from image 1 to 10 play X sound, when image 11 to 20 play Y sound... and go on...

**Comment by pisi** [comment]
Yes, that would be very nice, but is out of scope for Reel I think at least for now.

But you can do this yourself already! For a reel on `#image`:

``` js
$('#image').reel();
```

You bind to its `frameChange` event and play appropriate sound for the frame your handler will receive as **third** argument:

``` js
$('#image').bind('frameChange', function(e, d, frame){
  if (frame >= 1 && frame <= 10){
    // play sound X
  }else if (frame >= 11 && frame <= 20){
    // play sound Y
  }else if (frame >= 21 && frame <= 30){
    // and go on
  }
});
```

**Comment by efdutra** [comment]
Thanks man!!
