### ISSUE TITLE
too many request add after use custom cursor in ie6   

### ISSUE THREAD

**Issue by czonechan** [pisi/Reel#158]
i am use the custom cursor to create a flip  book ,but when i flip, the cursor file will add about 30 to 40 times http request .Although most of them all 304 ,but my  book images preloaded  are abort.

**Comment by pisi** [comment]
Yeah, unfortunately cursors have tendency to misbehave when caching and browsers doesn't seem to cache them properly like every other request. Most browsers handle this well except the ancient IE6, which seemingly doesn't employ any caching of cursors what so ever and flood server with multiple requests even though you treat them with expiration headers, etags (or whatever) and return 304, IE6 always requests new one on every redraw. For example Reel's CDN serves around million of such requests to IE6es mainly in mainland China.

I haven't found a solution yet and am afraid there isn't one, sorry. Despite Reel being capable to run on IE6, the experience may not be as smooth as in any other browser and cursors are one of the friction spot.
