### ISSUE TITLE
Conflicting with my drupal Jquery

### ISSUE THREAD

**Issue by darshanc** [pisi/Reel#161]
I have embedded the jquery reel plugin on my site.
The plugin is working fine but after that my primary doesnt show dropdown on hover.
When i disable functions.js and jquery.1.7.2.js menu starts working fine.
I quess there is some conflict between the jquery, can you please tell me what can be the issue?

Please refer the following link for your reference: 
http://www.media2win.in/bharatbenz/light-duty-truck/914

**Comment by pisi** [comment]
I am not very familiar with Drupal's inner workings. But give the [Drupal Formatter plug-in](http://bit.ly/i1vDL5) a shot. Lee Rowlands made a great job to make sure such conflicts are no more.

And please sorry it took me so long to respond.
