### ISSUE TITLE
Plugin does not initialise on first time visit of website

### ISSUE THREAD

**Issue by cu2morrow** [pisi/Reel#163]
Hi there, 

I am using version 1.2 (15.07.2012) of the reel plugin on my website which is based on joomla 1.5. 
I've encountered a problem which I'm trying to solve for weeks but unfortunately I am not even able to identify the root for the behaviour. 

If the website is visited for the first time or the user has not visited the website for a while the reel script shows the preloading image and stucks after that. The images for the 3d effect are never initialised. 

Once I've press the refresh button of my browser or surf to another page and afterwards return to my site the script loads flawlessly. This happend in IE and Firefox, no matter which version I use to test (tried from IE 8 upwards and from firefox 3 upwards). 

Has anyone an idea why this happens? 

I would really appreciate your help as I have no idea how to solve this issue and I'm getting quite desperate.

Many thanks in advance, 
Marcel

**Comment by pisi** [comment]
Hello Marcel,

for Joomla, there is a new [3D turntable plugin](http://animium.com/2011/12/3d-turntable-plugin-for-joomla/), which is supposed to seamlessly integrate into Joomla. Please give that a shot and if that doesn't work out for you, please head right back here ;)

And please apologize the huge delay. Work...
