### ISSUE TITLE
Multi-Row Sequence twitchy switching between rows

### ISSUE THREAD

**Issue by mspaw** [pisi/Reel#164]
Thanks so much for putting this out there. I'm getting some really nice results with the Multi-Row Sequence option but I've noticed in both my tests and the example you have posted that when moving the mouse vertically its very easy to have the position within the row change as well, leading to a slight visual twitch.  I'm not sure if there is anything i can do to dampen out this or to make the change less sensitive when moving vertically to the next row. Unfortunately for my application its fairly noticeable.

Ill be happy to email a link if it helps to see the behavior but im seeing it in the sample as well.

Thanks!

-Michael

**Comment by mspaw** [comment]
Im wondering if there could be an option to lock the axis when the other is being manipulated. or even a delay. 

-Michael

**Comment by pisi** [comment]
Hi Michael,

if you're still interested in this, please email me the link to petr at vostrel dot cz and I will take a look. I'm also thinking about some locking option. It is a nice feature suggestion. It would have to be on/off switchable though.

And please apologies for the huge delay in response. So little time for my open-source baby :(
