### ISSUE TITLE
How to not play opening animation

### ISSUE THREAD

**Issue by jeronimonunez** [pisi/Reel#165]
Hi!
I wanted to know how can I initialize reel without playing the opening animation. The animation always plays once and then stops. But I need to init reel without the initial animation.

Thanks!

**Comment by pisi** [comment]
Easy! :) If you don't want opening animation, leave or zero out the [`opening`](http://jquery.vostrel.cz/reel#opening) option when calling `.reel()`. Without it, there won't be any opening animation playing.

And, man, sorry for the time it took me to get to these issues.
