### ISSUE TITLE
Delay before opening animation and momentum

### ISSUE THREAD

**Issue by cu2morrow** [pisi/Reel#166]
Hi,

I am searching for a way to exactely imitate the behaviour of jquery reel as used on this page: http://www.irobot.com/global/de-at/product.aspx?id=282

On this page the opening animation starts slowly after an initial delay, gets faster and slows down and stops after one 360° turn.

On the page mentionend above jquery reel 1.1 is used whereby I use jquery reel 1.2 for my project. I also use 36 frames as on the website. I tried alreay all attributes of the reel script but was not able to find the correct combination of values.  Has anyone an idea how to achieve this behaviour with version 1.2?

Many thanks in advance, 
Marcel

**Comment by pisi** [comment]
Hi Marcel,

I inspected their code and none of the options used by them has the power to do what it does out of the box, which explains why you were unable to replicate it with the same exact options. Version also doesn't matter. What matter's are the modifications they did to the Reel code. They've tweaked Reel to do what they wanted. But they've kept the open-source license, so you can head [there](http://www.irobot.com/global/includes/js/jquery.reel.js) and grab their Reel if you want (don't forget though, you won't be able to easily update to a newer version then).
