### ISSUE TITLE
Hover/ mouseover support

### ISSUE THREAD

**Issue by thejae** [pisi/Reel#167]
is it possible to make Reel support hover instead of dragging? 

Example, the first demo: http://www.mathieusavard.info/threesixty/demo.html

**Comment by pisi** [comment]
In fact it is! By setting [`clickfree`](http://jquery.vostrel.cz/reel#clickfree) option to `true`, Reel will respond on mouse over.

``` js
$('#image').reel({
  clickfree: true
});
```
