### ISSUE TITLE
Multi Row Sequence with vertical orbit?

### ISSUE THREAD

**Issue by danielwoolfson** [pisi/Reel#169]
Hi there,

is it possible to combine a multi-row sequence with Dual-Orbit mode.

this would allow you complete 360 degrees orbit in both vertical and horizontal directions.

I tried combining the "row", "orbital" and "footage" commands, but am getting some strange results....

Cheers for your help

daniel

**Comment by pisi** [comment]
To answer your question: multi-row and dual-orbit modes are not mixable and using `row` with conjunction with `orbital` will yield some funky results.

360° in all directions is not supported.
