### ISSUE TITLE
Add Handler

### ISSUE THREAD

**Issue by adyz** [pisi/Reel#17]
Can we already add an handler somewhere else beside the image itself?
Something like arrows or scroll bar or another thumbnail/div. 
Thank you! 
Sorry for my English!

**Comment by pisi** [comment]
Hi,

internally Reel uses event and you can `.bind` to any of them and let your handler react to the event. Particulary, you will be interested in `"frameChange"` event, which is trigged every time frame is changed. You won't get the frame number as handler parameter. Instead you can access `.data` on the element itself. Reel stores everything in element's data. Look for the key `"frame"`.

```
$('#your_image').bind('frameChange', function(){
    // Inside this handler you can do whatever you want
    // to any element anywhere on page.
    // `this` is the Reel instance element
    $(this).data('frame'); // returns current frame number
});
```

Supposed you have Reel already instantiated by `$('#your_image').reel({ ... })`.

Hope this helps. If not, please, feel free to reopen this issue.
