### ISSUE TITLE
Linking to another pano with annotations

### ISSUE THREAD

**Issue by demund** [pisi/Reel#170]
``` js
annotations: {
  "backin": {
    link: {
      href: "#part1", 
      text: "Go back"
    },
    x: 30,
    y: 20
  }
}
```

I have several div classes for each pano and I would like to have them linking to each other. All of this happens in a single html page and each class is named part1, part2 and so forth. How can I link from one pano to another?

**Comment by thejae** [comment]
According to HTML5, you can directly link to another ID element. For example:

``` javascript
$('#part1').reel(); //The link will be index.html#part1
$('#part2').reel(); //The link will be index.html#part2
$('#part3').reel(); //The link will be index.html#part3
```

You can keep your current properties 
`link: { href: "#part1"} //part2 part3 and so on`

Your browser should automatically scroll down or upward to the relevant scroll.

**Comment by pisi** [comment]
Or you can attach custom click handler to the link (remember, the hash given to `link` is simply handed over to jQuery's `.attr()`, which is nice enough to accept handlers of certain events defined as attributes in the hash):

``` js
    link: { click: myClickHandler }
```

The `click` handler you define is handed over the click event as argument `ev` and `this` reference to the link DOM element itself.

``` js
    function myClickHandler(ev){
      var pano = $(this).attr('href').substr(1); // `substr` removes the leading `#` char
    }
```

Now when you know the name of the `pano` you're linking, you can easily switch it visible, do a on-demand `.reel()`, employ some nice scrolling plugin to scroll to it, or... whatever really ;)
