### ISSUE TITLE
Max throw speed

### ISSUE THREAD

**Issue by thejae** [pisi/Reel#172]
Hi there, thanks for this great plugin. I'd like to know if I can set the maximum speed. I using the plugin to showcase some luxury products and i don't want people to spin them around madly like cheap toys :P thanks!!

PS: am using throwable: true.

**Comment by pisi** [comment]
Thanks! :) Hm, I haven't considered a max speed yet. Don't know about clipping it, but a possibility to provide some numeric sensitivity via the `throwable` option would sure be very nice. Scheduled for the 1.2.1

**Comment by pisi** [comment]
From now, besides the existing Boolean value, the same `throwable` option now can now accept a numeric input, which will limit the throw velocity induced by user.

``` js
    $('#my_image').reel({
      throwable: 0.9
    })
```

The higher the positive value, the faster the spin. Usage is demonstrated in the [clockwise sprite object movie example](/pisi/Reel/tree/development/example/object-movie-clockwise-sprite).

Merged into the [development branch](/pisi/Reel/tree/development) and awaiting release.

**Comment by pisi** [comment]
Merged into [master](/pisi/Reel/tree/master) and **included in today's [version 1.2.1](/pisi/Reel/tree/v1.2.1)** release.
