### ISSUE TITLE
draggable annotations

### ISSUE THREAD

**Issue by aenima3** [pisi/Reel#176]
Hi

I have a reel with image anntotations on it, which are draggable via jquery.ui. As you can guess,  my image reel is "spinning"  while my image annotations are dragged, so i want to stop the reel while dragging the annotations, is that possible?

I guess that what i need to do si to change the "draggable" option  to false in my reel() method but i cant find the way to do it

thanks in advance ! :D

**Comment by pisi** [comment]
By using `draggable` you would loose the dragging interaction all together.

What you want to do is take advantage of the fact, that everything Reel related (including annotations) is wrapped in a parent `<div class="reel-overlay">` created when Reel is initialized. To this overlay Reel's mousedown handler are bound. If you don't want Reel to pick any event up, you need to **act on the annotation node** itself and stop the event from propagating up the DOM towards the overlay:

``` js
    $(".reel-annotation").bind("mousedown", function( e ){
      e.stopPropagation();
    });
```
