### ISSUE TITLE
Hotspots with on hover 

### ISSUE THREAD

**Issue by kugarek** [pisi/Reel#177]
Hello, 
I am currently working on a project where I have to create the hotspots which will rotate with the image. I know that the annotations are great for it, but how I could add on hover effect and display a tooltip with some text while the mouse hoovers on the hotspot? An example of what I am trying to achieve might be seen here: http://www.artd.ch/demos/artd_raupe/index.php/circle-hotspots

Please point me in to the right direction, thank you for any help. 

Regards

**Comment by pisi** [comment]
You can do this easily with a little help of CSS. You simply need to hide a portion of the annotation and show it on the hover. I've put together a little example: http://jsfiddle.net/KKRRk/
