### ISSUE TITLE
Mousewheel not working in stitched panorama

### ISSUE THREAD

**Issue by Beco91** [pisi/Reel#178]
Hi!
I've been working on a stitched panorama for a while (trying to create a google streetview-ish thing), and so far, it worked. Annotations link into each others nicely, and so on

I've got two problems though. Mousewheel doesn't seem to work, and I can't change the rotation behaviour (I'd like to have the effect cw: false does). I've loaded jquery, reel, mousewheel and disable text select js files.

code:
<html><head><title>pano</title></head><body>

<script src="jquery-1.9.1.min.js"></script>

<script src= "jquery.reel.js"></script>

<script src= "jquery.event.wheel-1.0.js"></script>

<script src= "jquery.disabletextselect-min.js"></script>

<img src="0.jpg" id="belepo" width="1042" height="800" />
<script>
       $(document).ready(function(){

```
    $('#belepo').reel({
      indicator:   5, 
      speed:       0.00,
      frames:      120,
      frame:       37, 
      stitched:    3870,
      wheelable:    true,
      loops:       false,
      annotations: {
  "bal1": {
      x: 480,
      y: 655,
      image: {
         src:    "ugras.png",
         width:  71,
         height: 71
      },
      link: {
          href: "b1.html"
      },},
      "jobb1": {
      x: 3180,
      y: 600,
      image: {
         src:    "ugras.png",
         width:  71,
         height: 71
      },
      link: {
          href: "j1.html"
      },},
      "bal2": {
      x: 240,
      y: 620,
      image: {
         src:    "ugras.png",
         width:  71,
         height: 71
      },
      link: {
          href: "b2.html"
      },},
```

  }
        });

```
  });
</script></body></html>
```

please help me. Thanks in advance

**Comment by pisi** [comment]
Sorry I missed your issue. If your trouble persist, please do re-open this issue and provide a link, where I can see it. Thanks!
