### ISSUE TITLE
Stitched Panorama rotation angle

### ISSUE THREAD

**Issue by ardelean** [pisi/Reel#18]
Hi,

Very & very nice tool! 

For the 360° Stitched Panorama it would be nice to be able to get the rotation angle for imaginary line at center of panorama frame (as the stitched image is scrolled/rotated). 
Somebody could use the returned rotation value for building a "radar" on a map or at least define a caption with cardinal directions.

It would be also nice to be able to define where the panorama is opened (let say rotate at 45° where if panorama covers 360°, 0° is the left side and 360° is right side of stitched image): a good reason for having this is that not always the center of panorama is the most interesting part.

All the best,
Adorian

**Comment by pisi** [comment]
Hi again Adorian,

and thanks!

For reporting the current angle, Reel would first have to be aware of the angular range of the panorama, which it isn't. Instead only the pixel length (width) defines the stitched panorama. You can use `frames` or `steps` option to virtually divide the width into smaller chunks. Then you can specify initial `frame` or `step` option to have the panorama start at certain virtual chunk.

F.e.: When having 10 `steps`, starting at `step` 1 will start at far left, 5 in the middle and 10 at far right.
