### ISSUE TITLE
Mouse wheel plugin requirement not clear on the website

### ISSUE THREAD

**Issue by acicali** [pisi/Reel#181]
Unless I'm missing something, the 'wheelable' option seems to not be working at all.

Here is what I used to invoke the plugin:

```
    $('#rotation').reel({
        suffix:     '',
        frames:     36,
        footage:    36,
        cursor:     'hand'
    });
```

The documentation mentions that 'wheelable' is enabled by default, but it didn't work for me even when I explicitly enabled it using "{ wheelable : true }".

I tested in Chrome (25.0.1364.172 m) and Firefox (19.0.2) with the same results.

**Comment by pisi** [comment]
Perhaps you're missing one of **optional** mousewheel plugins ([this](http://plugins.jquery.com/project/mousewheel) or [this](http://blog.threedubmedia.com/2008/08/eventspecialwheel.html))?. One of them actually is **required** for getting mouse wheel to work.

Simplest is to get [Reel already bundled with mousewheel](http://code.vostrel.cz/jquery.reel-bundle.js)

**Comment by acicali** [comment]
Yep, that was the problem.  Sorry I missed that.  Any chance you could mention that requirement under the wheelable option as well?

Thank you!

**Comment by pisi** [comment]
Fair point. Thanks! Although It is mentioned only in [requirements](http://jquery.vostrel.cz/reel#requirements) section, I should probably place a short note to the `wheelable` option itself too. No time for that now, however, so reopened to act as a reminder for me.

**Comment by pisi** [comment]
Mouse wheel plugin requirement is now clearly stated along the `wheelable` option:

> Allows mouse wheel interaction (allowed by default; requires external mouse wheel plugin ).

http://jquery.vostrel.cz/reel#wheelable

Thanks again for the feedback! :)
