### ISSUE TITLE
Annotations don't allow start frame > end frame

### ISSUE THREAD

**Issue by acicali** [pisi/Reel#185]
It doesn't appear that annotations allow for looping the reel animation, which would imply a greater start frame than the end frame.

For my use case, I have a 36 frame reel with an object that comes into view in the reel around frame 34 and disappears around frame 7.  However, settings start: 34 and end: 7 causes the annotation to never be displayed.

**Comment by pisi** [comment]
Hi,

for when your annotation overlaps the seam and is supposed to be visible in few last and few first frames, simple `start` and `end` can not be used and you have to use one of two advanced options:
1. If your annotation doesn't change position, you can use [visibility switching](/pisi/Reel/wiki/Annotations#visibility-switching) with `at`. For your use case, it's `at: "+++++++--------------------------+++"`
2. Or if the position does change, use [placement visibility](/pisi/Reel/wiki/Annotations#visibility-via-placement).

**Comment by pisi** [comment]
There's also an example to check out - the [dual-orbit object movie example](http://test.vostrel.cz/jquery.reel/example/object-movie-dual-orbit-sequence/), which uses the `at` technique to indicate the seam.
