### ISSUE TITLE
Annotation vs. Drag sensitivity on mobile device

### ISSUE THREAD

**Issue by wylkyn** [pisi/Reel#186]
I have noticed that if there is the slightest movement of the finger when touching an annotation hotspot, it doesn't respond. This is true on my test of desktop browsers as well - if the mouse moves even one pixel during the click, no response from the hotspot. I'm assuming that it is because it thinks you are dragging instead, even if no image rotation occurs. It would be nice if there was some way to adjust the sensitivity of the drag to allow for more sloppy touching/clicking of hotspots.

**Comment by pisi** [comment]
I've added some room for error, 20 pixels radius to be precise. Annotation links should now be much more clickable than before, especially on touch devices.

@wylkyn Can you please grab code from the [**devlopment** branch](/pisi/Reel/tree/development) and give it a test ride? Thanks!

**Comment by wylkyn** [comment]
I'll give it a test and let you know. And thanks so much for the response!

**Comment by wylkyn** [comment]
Tests out great in the browser. I have to wait for my boss to get in to get the test iPad, but I'm assuming it will also test out fine. Thanks, Petr! You rock. :)

**Comment by pisi** [comment]
My pleasure :)

**Comment by pisi** [comment]
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)
