### ISSUE TITLE
Image URL being stripped of Query Vars

### ISSUE THREAD

**Issue by daveadotdev** [pisi/Reel#187]
When I specify an image to be reel'd such as:

```
http://example.com/images/test.png?width=2000&height=200
```

...the image that gets loaded from the server (eg, used as the background-image) is:

```
http://example.com/images/test.png
```

I think the above URL example gives a decent use case for when this may be an issue.

The fix is very easy, and I've done it in my code -- include the stuff after the ? in the re.image regex into an extra regex group (line 1885 in trunk) and output it when re-writing the URL to the background image (line 771 in trunk).

**Comment by daveadotdev** [comment]
The other use case, which is actually what led me to discover this was on Shopify, where images are served from a CDN. I was consistently getting an old version of an image, even days later. By appending a query var, they bust the cache and enable image versioning on their CDN, so it looks like image.jpg?4231, which serves up an entirely different image than image.jpg with no query var.

**Comment by pisi** [comment]
Valid point.

**Comment by pisi** [comment]
In an attempt to actually verify your point, I've put together some test, which revealed, that all points where URLs come in (image tag's `src` or [`image`](http://bit.ly/reeljs#image) and [`images`](http://bit.ly/reeljs#images) options) behave as they should and don't strip the query vars.

The only case, where query vars are stripped, is the last test, where URL is taken from the image `src` attribute and by appending [`suffix`](http://bit.ly/reeljs#suffix) a sprite URL is constructed. In this case, keeping the query vars often does not make sense. If for example width and height are defined on the `src`, surely the sprite has totally different dimensions. Not stripping would be unsafe here. If you need to use a sprite with query params, define it using the [`image`](http://bit.ly/reeljs#image) option.

``` html
<img src="image.jpg?size=medium" ...>
```

``` js
$('...').reel({
  image: "sprite.jpg?size=medium"
});
```

Please see the tests (49515408760) and feel free to prove me wrong! :)
