### ISSUE TITLE
Sites update for 1.3

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#194]
As always the release must be concluded by updates on all sites:
- Web update (version, download, options, changelog, news feed)
- Web examples update with the data approach
- CDN update
- Test site update
- G+, Twitter, LinkedIn..
- **jQuery Plugins site** - how glad I am it is back!

**Comment by mjcampagna** [comment]
Where can we get 1.2.2, and where is the changelog? I'm only able to access 1.2.1 for download from both the Github and Reel website.

**Comment by pisi** [comment]
It's not released yet. It needs the site update first. Until then 1.2.2 waits in the [**development** branch](/pisi/Reel/tree/development).

**Comment by pisi** [comment]
Matt, [v1.3rc](/pisi/Reel/tree/v1.3rc) is out now and here is its [changelog](/pisi/Reel/blob/v1.3rc/CHANGELOG.markdown)

**Comment by pisi** [comment]
Sites updates are done and [live](http://reel360.org/reel)! Reel v1.3 is OUT :) Rejoice :dancers:

**Comment by pisi** [comment]
And back on jQuery Plugins site :) - http://plugins.jquery.com/reel/
