### ISSUE TITLE
Pre-loading new images when using direct sequence switching

### ISSUE THREAD

**Issue by WolfyUK** [pisi/Reel#197]
I am attempting to replicate http://test.vostrel.cz/jquery.reel/example/realtime-direct-sequence-switching/ with my own collection of images in a local development environment. For some reason when I call `$('#image').reel('images', newImages);` the pre-loading does not seem to work properly in that all of the `img.reel-cached` elements remain as the original loaded items instead of the new ones. The actual user interface works correctly with the new items, but I am concerned that the images are not being pre-loaded in the browser.

Interestingly, I downloaded the example above to try and find out why it is not working and this caused the same problem to occur when developing locally too. I have not had the chance to upload to a web server yet, but surely this couldn't be the cause?

**Comment by pisi** [comment]
That example and also the switching feature are not released yet. Make sure you use Reel version 1.2.2 (`$.reel.version`) and if not get it from the [development branch](/pisi/Reel/tree/development). Sorry for the confusion.

**Comment by WolfyUK** [comment]
Thanks. I just downloaded 1.2.2 but I get the following error on line 1504 on initialisation:
`Cannot read property 'y' of undefined`

If I remove the `indicator` from the plugin options this error goes away. Is this a bug, or have I missed something that needs to be done after upgrading from the current release version to the development version?

**Comment by pisi** [comment]
Without actually seeing your implementation, I'm just guessing. So far, it looks to me, like you haven't specified both dimensions for the `<img>` tag you are applying Reel on. Its `src`, `width` and `height` are mandatory attributes.

**Comment by WolfyUK** [comment]
Thanks for your quick response. I do have those values set already, but I just updated my comment above after some more investigation. Sorry for the confusion.

**Comment by pisi** [comment]
Then I would really need to see it. There's something odd going on, which prevents Reel to read image dimensions through jQuery's `.width()` and `.height()`

**Comment by WolfyUK** [comment]
Thanks very much for helping out. I have e-mailed you what I am working on.

**Comment by pisi** [comment]
Quick solution is to just remove the `data-frame="6" data-row="3"` from the `<img>` tag of yours and you are good to go.

You see Reel stores all its states in the `<img>` DOM data and there is a big bunch of them. Currently they are not prefixed anyhow, so when you stored your initial values in data on the image node for your later retrieval, you accidentally stepped on two key values and it broke down (it won't in 1.3 btw..).

Alternatives are to either prefix your custom data (e.g. `data-wolfy-frame`) or rename the field to not interfere with Reel's internals (you can find their keys [here](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Shortcuts-And-Minification-Cache) in 2nd paragraph of the chapter).

**Comment by WolfyUK** [comment]
Excellent! Thanks very much for your help. Prefixing my `data` attributes fixes the issue.

**Comment by pisi** [comment]
My pleasure. [Donations](http://jquery.vostrel.net/reel#free) appreciated tho ;)
