### ISSUE TITLE
no concatenation for the img tag ?

### ISSUE THREAD

**Issue by jmharveys** [pisi/Reel#199]
Could be possible to not concatenate the img tag ?

 I would like to use...........

``` js
$('.img1').reel({
  images: [
    '<img class="reel-cached" width="340" height="178" src="img/1.jpg">',
    '<img class="reel-cached" width="340" height="178" src="img/2.jpg">'
  ]
});
```

Is there a way ? thanks for your help !!!

**Comment by pisi** [comment]
This doesn't cut it for you?

``` js
$('.img1').reel({
  images:  [
    'img/1.jpg',
    'img/2.jpg'
  ]
});
```

Or you really DO want to pass whole `<img>` tags?

**Comment by jmharveys** [comment]
I wish to pass whole <img> tags because in the system a put it, i will not work.

thanks !!

**Comment by pisi** [comment]
Then sorry, passing of whole tags is not supported as the one `<img>` tag you start with is being reused for all image URLs.

EDIT: The other `<img>` tags you see inside the wrapper serve for caching and remain hidden all the time...
