### ISSUE TITLE
Example of stepping

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#202]
To showcase [new stepping feature](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Click-Stepping-Events) and using of [`stepLeft`](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#stepLeft-Event) and [`stepRight`](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#stepRight-Event) events either add prev/next buttons into an existing example or create a new example.

**Comment by pisi** [comment]
Followup of #133

**Comment by sagarquad** [comment]
how to change row?
means up and down button to change the view of frame.

**Comment by pisi** [comment]
There are no similar stepping events for vertical direction (for rows) yet.

To manually change the row to 2nd, for example, use `.reel('row', 2)` on the running instance. Read little more on [write access to the data](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Write-Access).

**Comment by sagarquad** [comment]
Thanks for your reply,Now I have query that how to change speed of frame on fly. Currently I'm doing like this $('#my').trigger('play(1)'); but it's not working.So any help would be appreciated.

**Comment by pisi** [comment]
Do `.trigger("play", 1)`. First parameter is an event name (`"play"`) and second parameter is the desired speed in Hz (`1`).

**Comment by sagarquad** [comment]
thanks.

**Comment by pisi** [comment]
OK, [example/object-movie-multi-row-sprite](http://test.vostrel.net/jquery.reel/example/object-movie-multi-row-sprite/)  and [example/object-movie-non-animated-sprite](http://test.vostrel.net/jquery.reel/example/object-movie-non-animated-sprite/) examples have been enhanced with examples how to use stepping events and buttons to test out what these events do.

Besides that, `"stepDown"` and `"stepUp"` have been added.

Already merged into [**development** branch](/pisi/Reel/tree/development) ready for release.

**Comment by pisi** [comment]
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)
