### ISSUE TITLE
Slide to the first image

### ISSUE THREAD

**Issue by Neelam2** [pisi/Reel#204]
I need the following function:

By clicking an Beginning Button, it must be slide back to the first picture, not spring to the first.

$('button:contains(Beginning)').click( function(){
    $('#spritespin img').reel('frame',1);
} );

Any suggestions 

Thanks

**Comment by pisi** [comment]
Reel doesn't have a command, event or option to achieve rotation up to specific frame yet. It sounds like a nice future feature suggestion. Currently you'll have to code it yourself with what's available in Reel at the moment. But judging from what I saw until now, I just hope your skills are up to par. It is not really trivial...

**To click a button and animate Reel until the button is de-pressed.** You want to bind button's [`mousedown` event](http://api.jquery.com/mousedown/) to trigger Reel's [`play` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#play-Event) and also bind to button's [`mouseup` event](http://api.jquery.com/mouseup/) to trigger Reel's [`stop` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#stop-Event).

**To click a button to rewind Reel back to frame one.** This one is a little tricky to solve. You want to bind button's [`click` event](http://api.jquery.com/click/) to trigger Reel's [`play` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#play-Event), but this time the you need to pass it negative speed (`.trigger('play', -0.5)`) to get it rolling backwards. You also need to bind Reel's [`frameChange` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#frameChange-Event) to watch current frame changes and when it reaches frame number 1, trigger Reel's [`stop` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#stop-Event)

My time is seriously limited now to write an actual working code, sorry.

Also be aware of a mistake you have in your code. You always want to run `.reel()` on the same element. If you initiate Reel on `#spritespin` calling it on `#spritespin img` yields no results, as there is no child `img` of the `#spritespin` - it itself still is the `img`.

**Comment by Neelam2** [comment]
Hi, 

thanks for ur answer. 
With "spritspin img" it is not a problem, have a look: 

<div class=" spritespin" id="spritespin"> 
<f:image additionalAttributes="{itemprop: 'image'}" src="{product.imagePath}image_001.jpg" title="{product.name}" alt="{product.name}" width="400" /> 
</div> 

And my skills are up to par!!! 
To click a button and animate Reel until the button is de-pressed: 
I did it and it works super!! 
But i want to change the rotation, which is always the same (cw:true), for only the left-Button, how can i do this? 

$('button:contains(+)').mouseup(function(){ 
$('#spritespin img').trigger('stop'); 
}).mousedown(function(){ 
$('#spritespin img').trigger('play', -0.5) 
}); 

To click a button to rewind Reel back to frame one: 
I am already working on it. 

---

Paints Multimedia GmbH 
Ansa Rana 

Lange Reihe 29 
20099 Hamburg 

Tel: + 49 (0)40 - 27 808 285 
Fax: + 49 (0)40 - 27 808 286 

E-Mail: a.rana @paints.de 
Internet: www.paints.de 

---

Geschäftsführer : F. Till, J. Wähning 
HRB 86114, Hamburg 
Ust.ID.Nr. DE226211017 

----- Ursprüngliche Mail -----

Von: "Petr Vostřel" notifications@github.com 
An: "pisi/Reel" Reel@noreply.github.com 
CC: "Neelam2" a.rana@paints.de 
Gesendet: Mittwoch, 12. Juni 2013 13:08:43 
Betreff: Re: [Reel] Slide to the first image (#204) 

Reel doesn't have a command, event or option to achieve rotation up to specific frame yet. It sounds like a nice future feature suggestion. Currently you'll have to code it yourself with what's available in Reel at the moment. But judging from what I saw until now, I just hope your skills are up to par. It is not really trivial... 

To click a button and animate Reel until the button is de-pressed. You want to bind button's mousedown event to trigger Reel's play event and also bind to button's mouseup event to trigger Reel's stop event . 

To click a button to rewind Reel back to frame one. This one is a little tricky to solve. You want to bind button's click event to trigger Reel's play event , but this time the you need to pass it negative speed ( .trigger('play', -0.5) ) to get it rolling backwards. You also need to bind Reel's frameChange event to watch current frame changes and when it reaches frame number 1, trigger Reel's stop event 

My time is seriously limited now to write an actual working code, sorry. 

Also be aware of a mistake you have in your code. You always want to run .reel() on the same element. If you initiate Reel on #spritespin calling it on #spritespin img yields no results, as there is no child img of the #spritespin - it itself still is the img .

**Comment by Neelam2** [comment]
oh its ok i got it ...it rotates now in the other direction :)

**Comment by pisi** [comment]
Oh, yeah, great you figured it out! Just for the record for others, the direction of animation after `"play"` event is triggered is dicated by using its optional argument, which is the new speed. Positive (`.trigger('play', 0.6)`) will spin one way and negative value (`.trigger('play', -0.8)`) will spin the other.
