### ISSUE TITLE
Opening animation breaks

### ISSUE THREAD

**Issue by bg17aw** [pisi/Reel#205]
I am trying to start the animation on page load to let the user know about it, but the animation seem to start before all frames are loaded which basically make it useless, it is not smooth and stops randomly at a random frame.

This is somewhat solved by using the "delay" parameter, which I guess allows for the frames to be loaded, but using "delay" means I cannot make the page as efficient as possible. 

My animation uses 50 frames, and is called using:
$('#largeImage').reel({     images:      'images/3d2/##.jpg|0..49',
                    delay: 2, entry: 1, opening: 1, });

The link is http://osiris.sunderland.ac.uk/~bg17aw/tests/testReel.php.

Is there a solution? I have seen a smooth start here with another plugin:

http://www.dfs.co.uk/sofas/leather-sofas/bounty/
(need to press on the 360 button). 

Or is it a way to load the frames in the background so they are available at a press of a button like in the example above?

Thank you and great work!

**Comment by pisi** [comment]
I tell you what the difference is. Comparing theirs and yours setups, they run 24 images approx. 16 kB each, whereas you run 50 images approx. 45 kB each. That's theirs 384 kB vs. yours 2.25 MB - some 6 times more (read: longer).

It is all about finding the right balance between fidelity (read: file size) and performance (read: loading). So the advice is simple:
- more compression to those JPGs
- and cut them by half - 25 would be enough. In my experience, high count of images usually pays out only in panoramic shots, where camera rotates, not the object. You can do this fairly simple if you use `"images/3d2/##.jpg|0..49|2".

You can of course start the Reel hidden (or covered) and make it visible with a button, which can play the Reel as well.

**Comment by bg17aw** [comment]
Thank you, good advice. Any chance to have a slider like the one on the example above?
We had reports some users need a slider to invite them to interact (on desktops, not on touch devices, of course, but having it on a touch device would still not harm in any way I think).

**Comment by pisi** [comment]
Reel can work with any slider plugin you like the most via monitoring and changing Reel's [data](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Data). Either bind to `frameChange` event and use `frame` data value (grows from 1 to total number of frames) or bind to `fractionChange` event and use `fraction` (represents the same but in a range of 0.0 to 1.0).

**Comment by bg17aw** [comment]
Thank you, this might be simple for you, but sounds complicated to me, might make your plugin more flexible if you would include something like that in the future? I want to get a slider like this one if possible: http://dev.lesdecos.com/spinscslink/spinlinkstandchair/sofa360.php

Any help would be highly appreaciated. Thanks!

**Comment by pisi** [comment]
You see, the main thing is I don't want to re-invent a slider and consequently force my users to use it, when there is a myriad of very nice slider plugins around each being well capable to attach an event handler to it. Second, everyone has his favorite slider, most probably is already using it and wants this slider to control Reel.

Integration is pretty easy as you can see here - http://jsfiddle.net/YfYgV/ - where I demo this on [jQuery UI Slider](http://jqueryui.com/slider/). For other sliders, the approach would be very similar:
1. Configure slider with `1` as minimum and total number of frames as maximum.
2. Configure slider with a slide handler (name can differ between slider plugins), which would take the actual value (say `6`) and feed it to Reel with `.reel('frame', 6)`.

That's all that is to it.

**Comment by pisi** [comment]
As much I want to have issue resolutions verified, I want such long resolved ones out of the way. Verification still welcome tho!
