### ISSUE TITLE
Two Reel objects at the same time. Not stable

### ISSUE THREAD

**Issue by gnatok** [pisi/Reel#206]
Now i very closely working with Reel in my site.
I have two reel objects on the same page(#image0, #image1), objects are synchronized by frameChange. 
I have couple of methods that change images path. And i found that it works very slow, lot lacks and frame skip on PC..On my ipad(ipda 2) totally not usable, in some moment frameChange stops working on iPad and I see unpredictable frame changes.

Probably jsFiddle not good solution to show problems with speed and frameChange problems, but at least you can see my code:
http://jsfiddle.net/xTZ7H/1/

And bug N2. 
When you have on the page two(or more) Reel's objects and thay use ONE same image(sprite):
$('#image0').reel("row", someRow) will change rows for all Reel objects.

Thanks. Probably i know that i am asking too much. But anyway. Thanks

**Comment by gnatok** [comment]
@pisi Sample for bug 2

http://jsfiddle.net/rrwaX/1/

As you can see, Reel with sprites works better and faster, no lags and etc. But with sprites I have this nasty Row bug and quality reduces for iPad and some browsers

**Comment by pisi** [comment]
I am not experiencing any slowness or skipping in your jsfiddle with two viewports created. With four viewports, there is a barely noticeable jaggedness, which is understandable with your code. You see, in your `frameChange` handler you bind for each viewport, you relay the `frame` number to the other 3 viewports, which means, their `frameChange` event gets triggered too, which results in each viewport relaying it back the 3 others, where the causality chain finally stops (as there's no actual change then).

So, the more viewports are interconnected in this way, the more relay exchange is happening between them. To cut down the number of calls, I would suggest to make one viewport a _master_ and make others to relay the frame only to it. Master would then distribute the change to others.

**Comment by pisi** [comment]
As for the second issue reported inside this one, this looks like a genuine unrelated bug, so moved to #207 on itself. @gnatok, please watch that issue.

**Comment by gnatok** [comment]
@pisi for the "Row" bug - ok. 

About frameChange.
The big problem that they all must be masters. If I rotate second one it must automatically rotate first one. And conversely

**Comment by pisi** [comment]
Don't think of the idea as only dragging master would influence the slaves.

Instead of having all masters affecting each other, think many slaves, which report their position to one master, which is responsible for the sync and uses the reported position to drive itself and all remaining slaves.
