### ISSUE TITLE
bind function

### ISSUE THREAD

**Issue by Neelam2** [pisi/Reel#208]
Hi,

I have a button which has the function to rotate to start image(#ButtonAnfang') .
I have implemented it with the bind function.

I also have a button where the Anmiation begins to rotate automatically(#ButtonPlay), the problem here is that if I have previously used the #ButtonAnfang, the #ButtonPlay always stops at the first picture,
But I want him to continue to rotate continuously until I press the #ButtonStop.

Is there something like an unbind function that I can use?
Or any other solution?
Thanks

``` js
$('#ButtonPlay').click( function(){  
$('#spritespin img').trigger('play', -0.5)
   $('#ButtonPlay').hide(); 
    if ($('#ButtonPlay:hidden').length){
        $('#ButtonStop').show();    } }); 


$('#ButtonStop').click( function(){  
$('#spritespin img').trigger('stop');
    $('#ButtonStop').hide();
         if ($('#ButtonStop:hidden').length){
     $('#spritespin img').trigger('stop');
        $('#ButtonPlay').show();   } });


$('#ButtonAnfang').click(function(){    
$('#spritespin img').trigger('play', 1.0 )
.bind('frameChange', function(){
  if ($(this).reel('frame') == 1){
         $('#spritespin img').trigger('stop'); }});
```

If I implement the #ButtonPlay with the bind function , it rotate only in one direction if I rotate with the mouse over the picture and no longer stops.
Here with binding:

``` js
$('#ButtonPlay').click( function(){  
$('#spritespin img').trigger('play', -0.5)
    .bind('frameChange', function(){
        $('#spritespin img').trigger('play', -0.5)  });
 $('#ButtonPlay').hide();  
    if ($('#ButtonPlay:hidden').length){
        $('#ButtonStop').show();    } }); 
```

Thanks

**Comment by pisi** [comment]
You want to `.unbind()` your `frameChange` handler inside #ButtonAnfang after it reaches the frame 1. Otherwise it will continue monitoring the `frameChange` event and as a result will stop on frame 1 every time. To be safe and not accidentally unbind Reel's internal `frameChange` binding, you can for example namespace your event bindings with whatever namespace you like (f.e. `frameChange.mine`).

``` js
.bind('frameChange.mine', function(){
  if ($(this).reel('frame') == 1){
         $(this).trigger('stop')
         .unbind('frameChange.mine'); }});
```

**Comment by Neelam2** [comment]
Thanks ...it works very well!!
