### ISSUE TITLE
Annotation rendering in centre of the image first, later goes to the position

### ISSUE THREAD

**Issue by pvelumani** [pisi/Reel#209]
Annotation rendering in centre of the image first, later goes to the position.
look at this example http://jsfiddle.net/velumani/M6kjg/ when loading the page,the pin for the wheel displays in the middle, later goes to proper position, 

when page loads slowly, it takes little time to position properly!

Thanks the awesome reel.js, Any help/work around would be appreciated.

**Comment by pisi** [comment]
It doesn't exhibit to me no matter what I try, but from a quick glance at the stylesheet you have there, I would say that when you remove `position: absolute; left: 50%; top: 50%;` declarations from your `#wheel` CSS and this should remove this initial appearance in the center of the image.

http://jsfiddle.net/M6kjg/2/
(your fiddle with the above applied)

**Comment by pvelumani** [comment]
Thank you for your immediate response. It worked !!!! 

Highly commendable effort and very very useful and functional. Thanks for this wonderful js.

Cheers !!!

**Comment by pisi** [comment]
You're very welcome! :)
