### ISSUE TITLE
The transparent gif is being displayed after all images are loaded

### ISSUE THREAD

**Issue by luksak** [pisi/Reel#21]
hi

i use the following code:

```
$('#reel').reel({
    clickfree: true,
    delay: 1,
    frame: 1,
    speed: 0.2,
    path:    '/images/',
    images:  ['test1.png',
            'test2.png',
            'test3.png']
});
```

after all images are loaded, the reel disappears. instead of the first frame the transparent gif palceholder is being inserted.

am i doing something wrong?

thanks

lukas

**Comment by luksak** [comment]
oh, i just saw the existing issue for that.

**Comment by pisi** [comment]
Good :) For others I will just add the link to the [issue 11](https://github.com/pisi/Reel/issues/closed/#issue/11), which contains the solution for this.

**Comment by pisi** [comment]
For the record, I [just released](https://github.com/pisi/Reel/issues/closed#issue/11/comment/896575) the patch [version 1.1.1](https://github.com/pisi/Reel/tree/v1.1.1) with a cure for this pain.
