### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by Neelam2** [pisi/Reel#210]
![circle](https://f.cloud.github.com/assets/3706846/760052/965d28a6-e7a3-11e2-9af6-02bff5be127e.png)

Hi, 

i will place an picture (an circle) into the image and have its visibility synchronized with the position of Reel.
The circle will be seems like it rotate too.

Can i put an piture in the annotation and how??

Attached only to pictures of more, who shows the circle with an space, which change his postion always with the position of Reel.
The number of circle pictures is the number of the reel images
I hope I could explain it well

**Comment by pisi** [comment]
Image annotations are possible, see chapter **Content > Image** in [Annotations wiki page](https://github.com/pisi/Reel/wiki/Annotations).

However annotations have no built-in support for changing the image(s) in sync with Reel, so you'd need to bind to `frameChange` to monitor Reel and adjust the annotation accordingly.

Or you might be better off simply setting up another Reel just for the circle, placing it on top of your Reel image and again sync it with `frameChange` binding.

**Comment by Neelam2** [comment]
I do it like these:

``` js
 annotations: {

            "the_product": {
             image: {
             src:    "<f:uri.image src="{product.imagePath}image_001.jpg " width="400" />",
             width:  150,
             height: 90
            },
              start: 1,
              end: 2,
             x: "35%",
             y: 250
            },

               "the_product2": {
             image: {
             src:   "<f:uri.image src="{product.imagePath}image_002.jpg " width="400" />",
             width:  150,
             height: 90
            },
              start: 2,
              end: 3,
             x: "35%",
             y: 250
            },

               "the_product3": {
             image: {
             src:    "<f:uri.image src="{product.imagePath}image_003.jpg " width="400" />",
             width:  150,
             height: 90
            },
              start: 3,
              end: 4,
             x: "35%",
             y: 250
            },
}
```

**Comment by pisi** [comment]
Ah, ok. That should work too.
