### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by Neelam2** [pisi/Reel#211]
Hi,

how can i change the cursor image
thanks

**Comment by pisi** [comment]
There is a [`cursor` option](http://jquery.vostrel.net/reel#cursor) with several settings available:
1. undefined value (default) makes spin-suggesting Reel logo cursor to be used,
2. `cursor: "hand"` makes it to use a palm of hand cursor, which visually grabs during drag,
3. any other **valid** CSS cursor declaration stack can be used for completely custom cursors:

``` js
  .reel({
    cursor: url(my_folder/my_cursor.cur) move;
  })
```
