### ISSUE TITLE
Interaction Between Two Spin Objects

### ISSUE THREAD

**Issue by josephhsieh** [pisi/Reel#212]
Just wondering, is it possible to have interaction between two spin objects?
For example, if users spin on Object A, and then Object B will automatically spin too.

Thanks,

**Comment by pisi** [comment]
Oh, of course! Something like this is especially fun in [`clickfree` mode](http://jquery.vostrel.net/reel#clickfree).

``` js
$("#A, #B").reel();

$("#A").on("fractionChange", function(){
  var position = $("#A").reel("fraction");
  $("#B").reel("fraction", position );
});
```

This will make Object A the master replicating its exact position to Object B the slave. If you need just frame sync, not the exact position, replace all three `fraction`s with `frame`.

**Comment by josephhsieh** [comment]
Works like magic!!  Thank you so much!!
