### ISSUE TITLE
Initialization partial fail when data in conflict

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#213]
I have a live example of the issue at the link below:

http://dig-houston.com/dev/portfolio/trucks

If you view the source, you can clearly see in the original <img tags, I'm embedding pertinent reel information into "data-" attributes. I.e. `data-speed="" data-cw="0" data-frame="23" data-frames="45" data-id="10" data-active="0"`. As shown, frame 23 is the intended initial frame. But when you look at the later created (by the reel) enclosing DIV, it reports `"frame-45"` as the opening frame.

The code initiating the reels looks like so:

``` js
$reel.each(function(index){
    var $thisReel = $(this)
    var $reelFile = $thisReel.attr('src')
    var $reelFrames = parseInt($thisReel.attr('data-frames'))
    var $reelStartFrame = parseInt($thisReel.attr('data-frame'))
    var $reelCW = $thisReel.attr('data-cw') > 0 ? true : false
    var $reelSpeed = $thisReel.attr('data-speed')
    if ( $(this).closest('.colorReel').size() > 0 ) {
        $thisReel.reel({ loops:true, frames:$reelFrames, frame:$reelStartFrame, footage:4, revolution:600, suffix: '-reel', preloader: 3 })
    } else {
        $thisReel.reel({ frames:$reelFrames, footage:4, speed:parseFloat($reelSpeed), cw:$reelCW })
    }
})
```

Since the data is being tossed around from multiple sources and dynamic vars are being injected into the mix, I've toyed around with `parseInt()` to make sure the numbers are not string, and noticed a slight variation in results. But the problem still remains that it never initiates on the exact frame I want. I've even tried manually typing in my desired frame instead of passing vars, and it's a no go. I get varying results. If I type 23, I get 45. If I turn off `parseInt()` I get 5 instead of 45. However, if I type 24, 25, or 10, it actually obeys and gives me the proper frame. In fact, as I'm testing right now, I'm noticing that 23 seems to be the only frame it will not obey.

So, let's pick this apart. With 45 frames, 23 happens to be the frame exactly in the middle (with 22 frames on either side of it). Coincidence? Also, possibly worth mentioning, is that 45 is not perfectly divisible by 2, in being 22.5 is the answer. Math problems?

At any rate, I think I'm onto something, but I'm not sure where the next level of testing should go.

**Comment by pisi** [comment]
Indeed you've tapped something. It looks like a `frameChange` handler is fired internally while having no `frame` yet. I may have fixed it now, just need to run a few more tests

**Comment by IsraelThompson** [comment]
So when I'm typing the frame manually, like so: `frame:23` (as opposed to passing a var the way I was originally. i.e. `frame:$reelStartFrame`), this is still somehow interpreted as not having a frame yet? How does one ensure there is already a frame?

Hmmmm.. And I was so positive that the fact that 23 was in the middle of a 45 frame reel and that 45 isn't divisible by 2 evenly had something to do with it...

**Comment by pisi** [comment]
I know now where the problem is and as it turns out it is not even a bug :) You see, Reel uses the DOM data store on the `<img>` element quite extensively and in fact it is directly driven by changes of these data values. When you use a data attributes on the tag, make sure they don't conflict with: `annotations`, `area`, `backup`, `backwards`, `bit`, `brake`, `cached`, `center`, `clicked`, `clicked_location`, `clicked_on`, `clicked_tier`, `cwish`, `dimensions`, `fraction`, `frame`, `frames`, `hi`, `image`, `images`, `lo`, `opening`, `opening_ticks`, `options`, `playing`, `preloaded`, `reeled`, `reeling`, `revolution`, `revolution_y`, `row`, `rows`, `spacing`, `speed`, `stage`, `stitched_shift`, `stitched_travel`, `stopped`, `style`, `tempo`, `tier`, `velocity`, `vertical`. Consequences of such a conflict include improper initialization such as the one you are experiencing.

That is why direct manual input made no difference - because there still is the (same) data attribute on the element, which prevents the initial change event to fire (because there is no actual change).

**Removing `data-frame` and `data-frames` from your `<img>` tags resolves your situation.**

**Comment by pisi** [comment]
Btw. the frame you want to start on is `24` ;)

**Comment by IsraelThompson** [comment]
I believe, sir, you've figured this one out!

By renaming the `data-attributes` to something less conflicting, the problem was definitely solved. This does bring me to a question, however... No matter how extensively the `data-attributes` are being used, shouldn't a manual entry always supersede or override?

For anyone else following, I'd like to point out I tried removing the `parseInt()` wrapped around the two frame oriented vars and the frame number kept defaulting to `5`, so I had to leave the `parseInt()` in place.

And also... You were right about the frame needing to be 24! Keen eye, mister! And thank you for such an excellent turnaround! The reel has worked quite well for us and we've put it to lot's of good use. Very shortly we'll have this live at the following URL in case you wanted to reference it in any way (same url as above, only without the "dev"):

http://dig-houston.com/portfolio/trucks

**Comment by pisi** [comment]
Excellent! :) Thanks for the verification and the URL.

To your question. Yes it (maybe) should and since 1.2.2 there will be a newer way to define your options with data attributes (see #193). But that technique would initialize all such image tags on page, which is not what you would want I presume, so you're "stuck" with the regular javascript call, where using data attributes can be dangerous. But you are probably right, that manual data attribute entry should override the default, not break it ;) I will think about this some more.
