### ISSUE TITLE
Safari refresh does not work

### ISSUE THREAD

**Issue by Neelam2** [pisi/Reel#215]
Hi,

My Reel will not load on Safari, when using the F5 key or refresh it loads not reel.
But it doesnt work only on PC, on ipad and Iphone it works!

The same mistake by  and Galaxy Note 10 - Android Browser 4.1.2 .

Any idea

**Comment by pisi** [comment]
Check that the actual DOM element is ready when you call `.reel()` upon it. Neat way to make sure is to execute the call inside a [DOM ready](http://api.jquery.com/ready/) callback, like so:

``` js
$(function(){
   // all code inside this function
  // will be executed only after the DOM is 100% ready 
})
```
