### ISSUE TITLE
I want to access preloader from the plugin

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#218]
Actually i am using buttons,that i want to make them disabled untill the preloader has completed preloading.How can that be possible? help please

**Comment by pisi** [comment]
Hi there! :)

You need start with your buttons disabled like this:

``` html
<button disabled="disabled">...</button>
```

start the Reel:

``` js
$("#image").reel({
  // your options
});
```

bind to its `"loaded"` event, which is fired right after all images finish preloading, and in the handler enable your buttons:

``` js
$("#image").bind("loaded", function(){
  $("button").removeAttr("disabled");
});
```

**Comment by mirzatalat** [comment]
Hey Thanks, :)

**Comment by mirzatalat** [comment]
one more thing :o ... what if i want to disable  once again the "up" and "down" button when completing the stepup and step down functionality..

**Comment by pisi** [comment]
Supposed you have `#up` and `#down` buttons:

``` html
<button id="up">UP</button>
<button id="down">DOWN</button>
```

You simply add the `disabled="disabled"` attribute back to it like so:

``` js
$("#up, #down").click(function(){
   // trigger the `stepUp` or `stepDown` event here
   $("#up, #down").attr("disabled", "disabled");
});
```

**Comment by mirzatalat** [comment]
actually i am completing 180 degree rotation , after completing 180 degrees rotation the buttons should get back to disabled state ..any clue?

**Comment by pisi** [comment]
Every time a frame is changed, Reel reports this by triggering the `"frameChange"` event. You can bind to this event, wait for a desired frame to be reached and do your business then.

``` js
$("#image").bind("frameChange", function( e ){
  if ( $("#image").reel("frame") >= 33 ){ // 33 or what ever frame you want
    // disable the buttons with `.attr("disabled", "disabled")`
  }
});
```

**Comment by mirzatalat** [comment]
This is my reel :--

``` js
$('#image').reel({
        frames:      20,
        frame:       14,
        rows:        13,
        row:         8,
        cw:         true,
        speed:       0,
        images:      'Drilbit/Drilbit_normal_###.png',
        cursor:     'move',
        preloader:  3,
        draggable: true,
        wheelable: true,
        throwable: true,
        steppable:true, 
    }); 
```

I am using following code :--

``` js
$("#image").bind("frameChange", function( e ){
  if ( $("#image").reel("frame") <= 14 ){ 
     $("#button-up").attr("disabled","disabled");
  }
  else
  {
  $("#button-up").removeAttr("disabled");
  }
  if ( $("#image").reel("frame") >=14 ){    
     $("#button-down").attr("disabled","disabled");
  }
  else
  {
  $("#button-down").removeAttr("disabled");
  }
});
```

Problem is that up button is working properly but i am not getting how to disable down button with the help of frames.

**Comment by pisi** [comment]
Ah! You then probably want to disable these up/down buttons based on `row` change, not `frame`. Mechanism is similar, you just bind to `"rowChange"` event instead of `"frameChange"` and watch `.reel("row")` instead of `.reel("frame")`. This will give you numbers from 1 up to your total number of `rows` option.

**Comment by mirzatalat** [comment]
Yes, Its working with rowchange. Thanks! .
One more question related to preloader. The current position of preloader is @bottom of image , What if i want to add the same preloader in the middle of image ?? showing the percent of preloading

**Comment by pisi** [comment]
Great! :)

Preloader is absolutely positioned within the image currently using `top` CSS property, so you can define your own position in your stylesheet. You can either use pixel-precise position or use percents. This will put the preloader right in the middle of the image:

``` css
#image-reel .reel-preloader {
  top: 50%;
}
```

**Comment by mirzatalat** [comment]
how about showing percentage of preloading? and what all can we change about preloader, i mean can we add image ? or text saying how much percent loading is done?

**Comment by pisi** [comment]
Well, I made the preloader to go without typography as much as possible. No "loading... wait", no numbers. The preloader bar growth communicates the preloading progress very intuitively and obviously IMO.

However as it is styled with CSS, image could be added although you might find yourself fighting with the default stylesheet at times. The number alone is not reported anywhere and currently can not be accessed with an event handler for example.

**Comment by mirzatalat** [comment]
If i want to add external preloading bar for loading these images? Would I be able to add? how?

**Comment by pisi** [comment]
You would, but probably not to the full extend you expect. You won't get any percentage information during the loading, so external loading progress bar showing precise preloading status is fairly out of question.

But you can create your own external static preloading indication, like an image or text or whatever, bind it to the `"loaded"` event just like in my first comment here and hide the indicator afterwards.

**Comment by mirzatalat** [comment]
done already ..but thanks :)

**Comment by mirzatalat** [comment]
placing buttons on that image .. how?

**Comment by pisi** [comment]
You can either use normal HTML button outside of Reel and use CSS positioning to move it over the Reel image.

Or you can use the [Annotations](/pisi/Reel/wiki/Annotations) feature, which is capable of inserting any HTML you want over the image. Please read the linked wiki page for full explanation, but this is roughly how it would look like.

``` js
annotations: {
  "my_button": {
    html: "<button>Click Me!</button>",
    x: 100,
    y: 50
  }
}
```

**Comment by mirzatalat** [comment]
please answer me on my other post. i took another div for placing these buttons. I want to disable hese buttons while preloading is going on. Left and Right buttoons are workiing fine.But UP and DoWn are getting enabled on preloading i mean when i click on that images frame, up and down buttons are also enabled.Ideally which should not happen.
Please any suggestions ?One solution is to disable the click event of that image reel div.

**Comment by pisi** [comment]
@mirzatalat, you do realize you posted the other post mere two hours ago? This is not my daily job, this is not a side job either... I'm happy to help if I can, but still I need to process free support requests in order to be fair to everyone. Our conversation about your issues is already far too extensive by the number of your posts or issues. Please be patient and in the meantime, read all of the documentation in the [annotated source code](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html) inside each Reel ZIP's `docs/` folder - all about everything is right there. If you're finished, there is a nice little [wiki](/pisi/Reel/wiki), where I especially recommend page on [Annotations](/pisi/Reel/wiki/Annotations).

**Comment by mufaddalmw** [comment]
Hi pisi, 

How we can show percentage value for progress bar pre-loader?
