### ISSUE TITLE
option for animations between images

### ISSUE THREAD

**Issue by luksak** [pisi/Reel#22]
hi

i have a set of 16 photos which is really not enough to get a smooth reel experience. a fade between the two images would really improve this. maybe we also could include a option for the duration of this animation. if you can point in some direction where to implement this i could also try my luck.

thanks

lukas

**Comment by pisi** [comment]
Hi Lukas,

current Reel architecture features just one single IMG tag stage and for fade there would have to be at least two of them. So right now this ain't possible. But principialy it should be feasible to implement. Please go ahead, fork me and if you succeed I will be more than happy to be inspired.

Good luck!

.pisi

**Comment by luksak** [comment]
hi pisi

i will try to accomplish that. what do you suggest, should i create a second img element and position both absolutely and then animate both of them? this would require the reel container to be positioned absolutely. or should there be another container for the active images?

thanks

lukas

**Comment by pisi** [comment]
Hi again,

awesome you want to give it a shot yourself! Please go ahead and fork Reel. My suggestions:

The only option would be to create another image which will overlay the current one and fade it back and forth. It would probably doesn't involve any positioning changes to the Reel container as it is already positioned relatively, so position the second image absolutely and top 0 left 0 would be the upper left corner of the first image.

You can also find out current frame and other data in the Reel instance `.data()`.

Good luck, Lukas! And, please, keep me posted. Thanks!

.pisi

**Comment by seb-thomas** [comment]
@luksak Hey did you get anywhere with this?

@pisi Hullo, thanks for the plugin! In your experienced opinion, do you think such a fade would make the rotations much smoother? I might give it a try.. :)

**Comment by luksak** [comment]
@sebastianthomas I don't think so... I think I just used it as it is.

**Comment by pisi** [comment]
@sebastianthomas It wouldn't make them much smoother. It would surely change the experience for the eye and help "entertain" the mind in between the frames. But it would also introduce a perceptible loss of sharpness, _blurriness_ if you will, which may benefit certain themes, but certainly not all of them. Personally, I've tried this years ago (in Flash to be fair and square) and the result wasn't much pleasing to the eye. It came out to be quite fuzzy and worse than without it. But that may as well been the crappy photos we were forced to use ;)
