### ISSUE TITLE
I want to disable those Up and down buttons while preloading is going on. 

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#220]
I want to disable those Up and down buttons while preloading is going on.:-
When Preloading ,Left and right buttons are being disables,but Up and down are still getting enabled,while clicking on image-reel or image .

This is what i have done with up and down buttons:

``` js
 $("#image").bind("rowChange", function( e ){
   if ( $("#image").reel("row") <= 1 ){ 
     $("#button-up").attr("disabled","disabled");
     $("#button-down").removeAttr("disabled");
   }
   else if($("#image").reel("row") > 1)
   {
   $("#button-up").removeAttr("disabled");
   }


   if ( $("#image").reel("row") > 12 ){ 
     $("#button-down").attr("disabled","disabled");
     $("#button-up").removeAttr("disabled");
   }
   else if($("#image").reel("row") <= 12)
   {
   $("#button-down").removeAttr("disabled");
   }
```

initially these are disabled .

**Comment by pisi** [comment]
Reel allows interaction right from the start without the need to wait for the rather large number of images to be loaded. Hence its [progressive loading](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#Preloading-Modes). 

So, you need to enhance your change event handlers to take into account whether Reel has been preloaded or not. And again, just like in #218 (duplicate), you want to bind to `loaded` event to register this fact and allow for the button disabling. Or.. you can keep your change events as they are, but bind them inside the `loaded` handler to make sure they get to be effective after the preload is finished.

**Comment by mirzatalat** [comment]
sorry for out of the context query , I have one CSS related issue and i know u'll answer me to the point ;) :- I am trying to place four buttons inside a circular div , its working fine on firefox , but not on chrome(buttons are misplaced/scattered)

here is the code i for CSS:

 .Circle_Base {
    -webkit-border-radius: 999px;     /_circular base for div_/
    -moz-border-radius: 999px;
    border-radius: 999px;
    behavior: url(PIE.htc);
    }

```
.type1{
width: 100px;
height: 100px;                   /* div */
background: #ecf0f1;
border: 1px solid black;
margin-left:25%;
margin-top:10%;
}

#button-up{
float:left;                     /* button-Up */
margin-left: 33px;
margin-top: 6px;
}

#button-right{                
float:left;                   /* button-right */
margin-left: 15px;
margin-top: 10px;  
}

#button-left{  
float:left;                  /* button-left */
margin-left: 10px;
margin-top: 9px;
}

#button-down{
float:left;             /* down button*/
margin-left: 33px;
margin-top: 7px;
}
```

can u please help me out with this?

**Comment by pisi** [comment]
Is it related to Reel preloader? These issues serve others too, you know. If you keep on posting off topic posts into your issues, it won't help nobody else, but you alone. And that is not the spirit..

**Comment by pisi** [comment]
Also note, that this issue is a duplicate of another issue (#218) and you're not supposed to submit further posts to the duplicates and rather post to the real one issue.

**Comment by mirzatalat** [comment]
This is off topic issue that i want to ask you, so where shall i post?

**Comment by pisi** [comment]
Easy. New topic = new issue.

**Comment by mirzatalat** [comment]
i did not wanted to disturb the issues List of this site,by posting some off topic issue.Okay if you say then I must post this as a new issue
