### ISSUE TITLE
Toggle reel

### ISSUE THREAD

**Issue by firewaller** [pisi/Reel#225]
I'm combining reel and a zoom & pan plugin and would like to disable reel functionality on zoom to allow panning without rotation.

I've managed to change the frame back to the desired one after the fact with <code>.bind('frameChange', function(e)</code>, but that produces an unpleasant frame stutter and can sometimes crash the page, even with <code>throwable: false</code>.

Is there any way to prevent a frame change or temporarily disable reel with a variable?

**Comment by pisi** [comment]
You'll welcome the two new [locking options](http://test.vostrel.net/jquery.reel-development/docs/jquery.reel.html#Multi-Row-Locks) (#191) then - `framelock` for horizontal and `rowlock` for vertical axis - in the next release. Both are _Boolean_ and `false` by default. Can be used as setup option or realtime data value change. When `true` it disables motion on respective axis, in effect holding the current `frame` or `row` until set `false` again.

_For example to temporarily disable change of the frame of Reel setup on `#my_image`:_

``` js
$("#my_image").reel("framelock", true );
```

You can try them now in the [**development** branch](/pisi/Reel/tree/development)

**Comment by firewaller** [comment]
Wow! Exactly what I was looking for. I really appreciate the quick response and hard effort everybody has put into this project.

The other development features look great too. Thanks!

**Comment by pisi** [comment]
My pleasure :)
