### ISSUE TITLE
Opening Animation

### ISSUE THREAD

**Issue by karanis** [pisi/Reel#226]
What I could not solve is, the "Opening Animation". After loading, everything is ok. But what I need is a one lap easeInOut Opening Animation (as stated in the document to attract and inform visitor) and I could not find a satisfactory guide in documents or elsewhere, and I`ve played with misc  "entry and opening" values (including <1).

"reel" should be capable of this but I just could not understand "Opening Animation" and "entry and opening" usage from the document. Maybe some examples in the documentation would be helpful for users also.

**Comment by pisi** [comment]
There is an example of [`opening`](http://reel360.org/reel#opening) & [`entry`](http://reel360.org/reel#entry) usage - http://test.vostrel.net/jquery.reel/example/object-movie-non-animated-sprite/ - it has 2-second opening animation with entry speed of 1 Hz.

Opening animation won't do the easeInOut effect for you though. You can get easeOut intro animation by setting an initial [`velocity`](http://reel360.org/reel#velocity). Example of it here - http://test.vostrel.net/jquery.reel/example/object-movie-clockwise-sequence/

**Comment by karanis** [comment]
Perfect demonstration. Thank you for fast reply and help.

**Comment by pisi** [comment]
You're very welcome :)
