### ISSUE TITLE
Trigger play from current frame

### ISSUE THREAD

**Issue by chrishoadley** [pisi/Reel#227]
Right now the trigger('play') reverses my reel to frame one then plays. Is there anyway to have it play from the current frame you are on?

**Comment by pisi** [comment]
The [`play` event](http://test.vostrel.net/jquery.reel/docs/jquery.reel.html#play-Event) does play from the current frame and it doesn't jump to first every time. It does work just like you want it. Try it out here - http://jsfiddle.net/2CxDm/

**Comment by chrishoadley** [comment]
Thank you for the quick reply.
Would you mind taking a look at my code? Not sure what i'm doing wrong. I can send msg you the dev link if that would help.

```
$('#image').reel({
                images:     'images/castle/castle_###.png|1..120',
                cursor:     'hand',
                loops:      false,
                brake:      0.15,
                cw:         true,
                revolution: 2000,
                annotations:{
                    "hit1":{
                        image: {
                            src: "images/hit1.png",
                            width: "100%"
                        },
                        link: {
                            click: Hit1Link
                        },
                        x: "42%",
                        y: "40%",
                        start: 52,
                        end:   55
                    }
                }
            });
            var target_frame = 120;
            function Hit1Link(){
                $('#image')
                .trigger('play','1')
                .bind('frameChange', function(e, depr_frame, frame){
                    if (frame == target_frame){
                        $(this).trigger('stop');
                        $(this).niceScroll().animate('scrollLeft', '100px');
                    }
                });
            };
```

**Comment by pisi** [comment]
Yeah, mail the link to `petr at vostrel dot cz` please.

Also updated the fiddle to better follow your scenario with no speed at startup and one given only at the event trigger. http://jsfiddle.net/2CxDm/1/

**Comment by pisi** [comment]
But looking at the code, I would guess the niceScroll initialization on the Reel instance itself might be a problem. Did you try it without the `$(this).niceScroll().animate('scrollLeft', '100px');` line?

**Comment by chrishoadley** [comment]
I did try that.
Email coming.

**Comment by chrishoadley** [comment]
Click anywhere in the footer to initiate the animation.

**Comment by pisi** [comment]
For the record, the internal prototype Chris sent me had enormously large (3840px) images, which he intended to play in an unsupported way.
