### ISSUE TITLE
Start value 0..35 evaluates 0 as false

### ISSUE THREAD

**Issue by mixtapeco** [pisi/Reel#228]
When start value is zero, it gets evaluated as false and default start of 1 is used instead. 

example: `images: "##.jpg|00..35"` skips `00.jpg` and starts at `01.jpg`

**Comment by pisi** [comment]
Indeed. Tests confirm it. Thanks a lot for catching this one, Chris! :)

**Comment by pisi** [comment]
Fix already merged into current [**development** branch](/pisi/Reel/tree/development)

**Comment by pisi** [comment]
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)
