### ISSUE TITLE
Images Array - Image Goes Blank After Preload

### ISSUE THREAD

**Issue by Archivist-zz** [pisi/Reel#23]
I tested both images array and image sheet. Image sheet seems to work fine.

However, images array is preferable because it seems to run much smoother, and it is less work for me to create.

First image loads, then preloading occurs (don't interrupt) - after preload is done, the image goes blank.

After it goes blank, you can grab and start dragging to rotate, but it would be great if it didn't go blank.

As I said, image sheet works fine, so I think I did everything right - I don't think I messed anything up, but it's always possible.

Any help on this issue would be greatly appreciated! This Javascript is really awesome!

**Comment by Archivist-zz** [comment]
Oops, I'm sorry, I didn't see that it was an already known issue under "Unread." I'm glad to know it's addressed and will hopefully soon be released with 1.1.1.

Thanks!

**Comment by pisi** [comment]
Exactly ;) For the record, it is a duplicate of [GH-11](https://github.com/pisi/Reel/issues/closed#issue/11) and I [just released](https://github.com/pisi/Reel/issues/closed#issue/11/comment/896575) the patch [version 1.1.1](https://github.com/pisi/Reel/tree/v1.1.1) with a cure for this pain.
