### ISSUE TITLE
How to hide and show annotations?

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#230]
I want to use annotations as hotspots on my 360 degree images.How to hide and show or more specifically how should i make the annotations visible and invisible according to my need?

I am using image as an annotation. Please guide me to make these image annotations visible and invisible depending on rotations.

**Comment by mirzatalat** [comment]
``` js
  $('#image').reel({
        frames:      20,
        frame:       14,
        rows:        13,
        row:         8,
        cw:         true,
        speed:       0,
        images:      'Drilbit/Drilbit_normal_###.jpg',
        cursor:     'move',
        preloader:  13,
        draggable: true,
        wheelable: true,
        throwable: true,
        annotations: {
             "annotations_1": { 

              image: {src:"hotspot_plus.png"},            
              x: 280,
              y: 160,             
            }
        }
    }); 
```

Above is my reel code

**Comment by pisi** [comment]
@mirzatalat You should also specify what your "needs" actually are...

**Comment by pisi** [comment]
But generally all techniques available with annotations are described in the [wiki](https://github.com/pisi/Reel/wiki/Annotations#synchronization-with-frames)

**Comment by mirzatalat** [comment]
OHk.. I am using annotations on my 360 degree rotation thing. Working Fine but the problem is i have to change the x and y options in annotations manually , meaning , I have to specify x and y co-ordinates with the rotation,
Is there any solution to this needed, every hotspot must be placed only once and it will rotate with the images.

**Comment by pisi** [comment]
From the [wiki](/pisi/Reel/wiki/Annotations#synchronization-with-frames):

> Unless both X and Y annotation coordinates are defined for a frame, the annotation is hidden. You can do this intentionaly by using undefined positions. First array item represents frame 1.

So, If you want the annotation to rotate with the image, you need to specify a set of coordinates and Reel will reposition the one annotation accordingly.

``` js
    x: [ 5, 10, 15, , , 15, 10, 5 ],
    y: 20
```

The above will place your annotation on 20px vertically and will hold this coordinate. Horizontally, the annotation will be at:
1. 5px
2. 10px
3. 15px
4. won't be visible on this frame
5. won't be visible on this frame
6. 15px
7. 10px
8. 5px
9. won't be visible on this frame
10. won't be visible on this frame
    ...

You still have to write the coordinates manually, but you need just one annotation for that.

**Comment by mirzatalat** [comment]
hey thanks.. I have been following the same thing which you mentioned above, But the problem is i am using more than two annotations as a hotspot, maybe 5-6 annotations, so its kind of time consuming to provide co-ordinates for each of them. So, I was eager to know the alternate and easy solution for this. Anyways, thanks Dude!

**Comment by pisi** [comment]
Yes, everything about 360° is fairly time consuming hard work indeed... But is worth it! :)

**Comment by mirzatalat** [comment]
one more thing , How to hide annotations( images) untill and unless the images have been  fully loaded??

**Comment by pisi** [comment]
There's no built-in way to do this. I will consider this to be added in the future.

**Comment by mirzatalat** [comment]
can you please suggest me some option in this case, how shalli i make the annotation images invisible for some time before images have been loaded. is there any damn way :(

**Comment by mirzatalat** [comment]
Mr. Petr Please i need your help in this urgently!

**Comment by pisi** [comment]
@mirzatalat please take into account, that Reel is a one man show and a hobby, not a day job. Forgive me, but urging an answer 8 minutes after asking the question is rather silly. So I ask you _once again_ to be patient and study all the documentation carefully instead.

Now, if there was an _easy_ working option, I would sure suggest it to you. But sadly, there isn't easy one. You need to get creative. For example add a `loading` class name to let's say `<body>` element to indicate to your stylesheet, that the Reel has not yet finished loading and remove this class on `loaded` event. Now you only force hide annotations with CSS with `.loading .reel-annotation { display: none !important; }`. Not tested. Just an idea..

If you do want urgent help, you can always buy a commercial support package from me. Mail me if interested.

**Comment by mirzatalat** [comment]
Oh am sorry for being mean, But thanks for the reply @least :P
