### ISSUE TITLE
Open a new pop up window or a new div by clicking annotation.

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#232]
Need help in this. How is it possible?

**Comment by pisi** [comment]
Easily by handling a standard `click` event triggered on the annotation when it is clicked. The event bubbles up the DOM so you can catch it on every ancestor of Reel element, for example all the way up on `document`.

``` js
$(document).on('click', '.reel-annotation', function(){
  // Handle the click event
});
```

Working example: http://jsfiddle.net/rRMPm/1/

Please note, that click propagation is a new feature yet to be released (#219), so grab your code from the [**development** branch](/pisi/Reel/tree/development) if you don't want to wait until the release.
