### ISSUE TITLE
Touch input not recognized on chrome in windows 8 hybrid devices

### ISSUE THREAD

**Issue by harshavarma** [pisi/Reel#233]
Hello,

I'm a long time user of reel and I encountered a couple of issues a few days back. One is the image flickering in firefox (#196), which is already reported.

The other one is the touch input (swipe) is ignored in chrome in devices that support both mouse and touch inputs (windows hybrids). It's actually the blink engine I think as both Opera and Chrome are not responding to touch where as Safari, Firefox and IE are working fine.

Reel just doesn't seem to respond to any touch gestures on chrome. Any help would be greatly appreciated.

**Comment by pisi** [comment]
Currently touch events are bound only on devices with touch support, which is performed using simple user agent matching. So it is possible, that this doesn't work for your device and I have a suspicion the method employed won't work for these hybrids.

Please run http://test.vostrel.cz/jquery.reel-development/test on the device in question, allow it to finish and let me know when you did. Thanks.

**Comment by harshavarma** [comment]
Hi,

I ran the test suite on the device, there are a lot of errors in the chrome console about missing resources but somehow all the tests (1864) in the suite passed. I ran it in both Firefox and Chrome. The touch events are working fine in every browser except chrome ( & Opera) though. 

Are there any touch specific tests that I can perform to give you more information? It is just that Chrome has the best performance out of all the browsers and It's sad that I can't use it right now.

**Comment by pisi** [comment]
Great. The missing resources don't matter. Sometimes it is even testing what happens when resource IS missing.

But, sadly, your test run didn't get recorded for some odd reason, so I will need you to:
1. Copy paste the user agent string you see in white on blue in the tests.
2. Execute `$.reel.touchy` in the console on the actual device - I'm guessing it will read `false`.

Thank you! Btw what is the actual device of yours?

**Comment by harshavarma** [comment]
The userAgent is `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.76 Safari/537.36`

And yes, `$.reel.touchy` returns `false`. The device I'm using is a Lenovo Thinkpad Helix. We deployed the app using reel on a PC which connects to a touchscreen monitor. It's basically a normal monitor with a panel overlay that adds the touch function. Chrome didn't recognize that touch input either while all other browsers did.

**Comment by pisi** [comment]
Um, ok, that's what I was afraid of - user agent detection won't cut it this time. Will rewrite the touch capability detection then ;) Stand by.

**Comment by harshavarma** [comment]
Appreciate the quick response. Let me know if you want me to do any more tests. Will be glad to help you in anyway I can.

**Comment by pisi** [comment]
Pls, verify for me that `'ontouchstart' in window` returns `true` on the device. Thanks!

**Comment by harshavarma** [comment]
`window.ontouchstart` returned `null`.

**Comment by pisi** [comment]
That's actually excellent! :) , because `null` indicates unused yet available bind point. It would equal `false` otherwise.

**Comment by pisi** [comment]
@harshavarma Test the revised touch capability detection code in the [**gh-233-touchy** branch](/pisi/Reel/tree/gh-233-touchy) please. It should be able to pick the device up as touch-enabled and hopefully there won't be any actual touch issues ;) Let me know.

**Comment by harshavarma** [comment]
I just tested the new branch and the touch support is great. However, on devices that support both mouse and touch, the mouse no longer works for reel. This is not a big issue but will be nice to have both working (all other browsers support both).

The other thing is, can you port this touch detection to a previous branch of reel (1.2). The images flicker in firefox (21+) as reported in #196. And the css workaround mentioned in that thread no longer works with this branch.

**Comment by pisi** [comment]
Oh, OK T_T Then I would have to bind them both somehow. I may end up porting it back, but it still is rather half-finished. I made advancements on the flicker issue, so @harshavarma please check that once again.

**Comment by pisi** [comment]
So am binding to touch and mouse events both at once now. On mouse only devices, the unknown touch events will be ignored. Touch only devices will pick up touch events only (and cancel eventual mouse events) and on hybrid devices, both should work, again with touch events taking precedence.

@harshavarma Looks promising, can't wait for you to test this! :)

[**gh-233-touchy** branch](/pisi/Reel/tree/gh-233-touchy)

**Comment by pisi** [comment]
Unless there are objections, this is ready for release. Still would appreciate independent verification ;)

**Comment by pisi** [comment]
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)

**Comment by pisi** [comment]
@harshavarma an issue (#260, which I just fixed) arose as a consequence of the fix here. And since that fix was made in the general thereabouts of this fix, I would like you to re-test the code from [[**gh-260-touch-fix** branch](/pisi/Reel/tree/gh-260-touch-fix) just in case. Thanks very much!

**Comment by harshavarma** [comment]
Hi @pisi, Sure, will let you know how it goes.

**Comment by harshavarma** [comment]
@pisi Just tested the code and can confirm it works well.

**Comment by pisi** [comment]
Awesome. Thanks!
