### ISSUE TITLE
IE lag issue when rotating image

### ISSUE THREAD

**Issue by scubastevo2005** [pisi/Reel#234]
Im using the REEL plugin and it seems to work GREAT in every browser except for Internet Explorer.  For some reason when I click on the image to spin it, it waits like 2 seconds before turning, and anytime I go outside of the box/frame it stops and starts about 2 seconds after leaving the box/frame.  I checked the delays and everything set to zero, and in all of the other browsers it works just fine, any insight that would be great!

Thanks

UPDATE:  I did some more digging and found this error pops up - 

```
                SCRIPT28: Out of stack space
                File: jquery-1.9.0.min.js, Line: 1, Column: 24660
```

Any insight on this would be great.

Seems to be stuck in an infinite loop.

**Comment by pisi** [comment]
Do you mean [Reel examples](http://test.vostrel.net/jquery.reel/example) or your implementation? In case of the later, this sometimes happens due to mis-configuration. What Reel options do you use?

**Comment by scubastevo2005** [comment]
In my implementation, I actually am using all the default settings. Everything works great in all of the other browsers except for IE.  Below is the exact error I get when I click to drag to spin it, or go outside of the image box to continue rotating it.

![error](https://f.cloud.github.com/assets/5603717/1282000/0110a154-2f6c-11e3-9c8f-1279a2aaaef6.jpg)

**Comment by pisi** [comment]
Can you show me?

**Comment by pisi** [comment]
I guess not ;) Then it's really hard to tell. It most likely is a misconfiguration of yours. But you can not go bad testing out the edge version in [**development** branch](/pisi/Reel/tree/development) - it always has something more than the latest released stable.
