### ISSUE TITLE
Best approach to play one time clockwise and then one time counter-clockwise 

### ISSUE THREAD

**Issue by ced64k** [pisi/Reel#239]
I'm using jQuery Reel to play an animation with 15 png on page load. I'd like to play it one time clockwise (frame 1->15), then one time counter-clockwise (frame 15->1), then stop (frame 1).

No problem to make the first loop, but I'm little bit stuck for playing it in the reverse direction.

``` javascript
     $(function(){ 
       $('#image').reel({
            images:      'img/##.png|01..15',
            opening:     2,
            entry:       0.5
       });
     });
```

What's the best approach to make that ?

Thanks.

**Edit**

I managed with this code but I'm not sure it's the best solution.

``` javascript
     $(function(){ 

       $('#image').reel({
            images:      'img/##.png|01..15',
            opening:     2,
            entry:       0.5,
            loops:       false,
            speed:       0.5

       });

       $('#image').on('frameChange', function(){
            if ($(this).reel('frame') == 1){
                $(this).trigger('stop'); 
            }
       });

     });
```

**Comment by pisi** [comment]
Non-looping animations do this back and forth motion, so yes, this might currently be the best solution. But I have two other (maybe better) alternatives for you ;)

In [v1.3rc](/pisi/Reel/tree/v1.3rc) there is also a new [`duration` option](http://test.vostrel.cz/jquery.reel-development/docs/jquery.reel.html#duration-Option), which sets the playback duration in seconds. So if what you need is a linear 0.5 Hz motion and you use this version, you could simply set 4 second duration like this and it should stop after 4 seconds:

``` js
$('#image').reel({
    images: 'img/##.png|01..15',
    loops: false,
    speed: 0.5,
    duration: 4
})
```

Have to warn you, this might not reliably stop on frame 1 on some slow mobile devices.

OR

In [v1.3rc](/pisi/Reel/tree/v1.3rc) there is also a new [`reach` event](http://test.vostrel.cz/jquery.reel-development/docs/jquery.reel.html#reach-Event), which lets you animate to certain frame. It finds the shortest path, so you can not start on frame 1 and make it reach frame 1 - it won't move. But you can tell it to reach frame 15 and on frame 15 tell it to reach frame 1. Something like so:

``` js
$('#image').reel({
    images: 'img/##.png|01..15',
    loops: false
})
$('#image').on('loaded', function(){
    $(this).trigger('reach', [ 15, 0.5 ]);
    $('#image').on('frameChange', function(){
      if ($(this).reel('frame') == 15){
          $(this).trigger('reach', [ 1, 0.5 ]);
      }
    });
});
```

As you can see, you trigger `reach` with two arguments, which need to be in an array. First one is target frame and the other one is desired speed.

**Comment by ced64k** [comment]
Thanks for your detailed reply Petr ! :+1:

**Comment by pisi** [comment]
Pleasure all mine :)

**Comment by drurustin** [comment]
I have 400 frames in my sequence. When I swipe left/right I would like the sequence to play to a specific frame number and stop. For example, if my start frame is 0 and then I swipe right it plays from frame 0 to frame 100 and stops on this frame. If I then swipe right again it plays from frame 100 to 200 and stops on frame 200 and so on and so on. I am aiming to achieve a 'snap to' effect. The sequence does not autoplay.

Would I use the above reach event to achieve this? 

Great work on this extremely powerful plugin.
