### ISSUE TITLE
show text and images in a Div under the reel 360 window after hotspot (annotation) click

### ISSUE THREAD

**Issue by structuraweb** [pisi/Reel#240]
Hi! you made a wonderful plugin! i am trying to achieve this objective: show text and images in a Div under the reel 360 window after hotspot (annotation) click
i read about the node function, but i'm a newbie and i don't know how to set the whole thing up! can you send me an example or an existing page of what's described above? thank you!

**Comment by pisi** [comment]
Thanks! :)

This should help you a bit - http://test.vostrel.net/jquery.reel-development/example/panorama-non-looping-sequence/ - there you can see how hotspots are setup to open in a lightbox plugin. There is no other example of annotations opening something, but it is trivial really, of the top of my head:

``` html
  <img ... class="reel">
  <a class="reel-annotation" id="clickme" ...>Click me!</a>
  <div id="divbelow"> The thing below Reel to show on click </div>
```

(HTML is simplified, building on top of the linked example add relevant attributes in place of `...`)

Your JS to make the hotspot show the div will be:

``` js
  $("#clickme").on("click", function(){
    $("#divbelow").show();
  });
```

**Comment by structuraweb** [comment]
thank you! so it's possible to do this with different hotspots and switch the content on the div below?

**Comment by pisi** [comment]
Entirely possible :)

**Comment by structuraweb** [comment]
how the code would look like? don't know how to switch the text on the same
div!

**Comment by pisi** [comment]
You can for example have several divs all of them hidden and show just the one you want. Or you can have one div and change its content is done with [`.text()`](http://api.jquery.com/text) or [`.html()`](http://api.jquery.com/html). Anyway that's a basic jQuery and quite out of scope of Reel itself.

**Comment by structuraweb** [comment]
ok thanks! i got to study the whole thing
