### ISSUE TITLE
Initial rotation direction doesn't work in 1.3

### ISSUE THREAD

**Issue by Dvornik** [pisi/Reel#241]
Hi! In version 1.2 I could control initial rotation direction using a positive and negative values ​​of the `speed` parameter.
For example: `{ speed: -0.3 }` for CW initial rotation and `{ speed: 0.3 }` for CCW rotation.
It worked fine for me, but it doesn't work now in 1.3 version, **when I use `{ shy: false/true }`.**

Thanks for your great job.

**Comment by pisi** [comment]
Will look into this on the weekend. Stay tuned

**Comment by shoany** [comment]
FYI, I had a similar problem and discovered that by using the "play" event I was able to reverse direction with speed. So, originally I was using: `$("#element").reel({frame: 15, frames:30,footage:30,speed:-0.3});` which didn't work as anticipated. Using the data method to set the frame to 15 and then using the play event works like a charm, though:

``` js
$("#element").reel('frame',15);
$("#element").trigger('play', [ -0.5 ]);
```

**Comment by pisi** [comment]
Nice workaround @shoany :)

I happened to spare some time for this issue and have the fix already :) Tests pass, so please try out the patched code from [**gh-241-negative-initial-speed** branch](/pisi/Reel/tree/gh-241-negative-initial-speed) and let me know if that works for all of you. Thanks.

**Comment by pisi** [comment]
@Dvornik can you please evaluate and verify the functionality of the fix above?

**Comment by Dvornik** [comment]
Thank you very much. Bug has been fixed!
It's:

```
$(activeImageId).reel({
                    ...
                    speed: -1,
                    shy: true,
                    ...
```

works fine now.
