### ISSUE TITLE
Loading troubles with IE7

### ISSUE THREAD

**Issue by cookieseventeen** [pisi/Reel#243]
when I user the IE Tester,it not load picture!

![ie7](https://f.cloud.github.com/assets/6064966/1643697/ec0b34da-58cf-11e3-80fe-f2b85ae6b3cc.jpg)

Just like pic!!!

**Comment by pisi** [comment]
Thanks for spotting this! Looking into it..

**Comment by cookieseventeen** [comment]
I find the Website,That use jquery.reel , It can support IE7!!!

http://www.dji.com/feature/phantom-2-vision-features/

**Comment by pisi** [comment]
Good news! Bug fixed (one-liner) and IE6+ compatibility regained. To test this you can simply revisit http://reel360.org - the site already runs the fixed version. Or grab the fixed code from [**gh-243-old-ie-loading** branch](/pisi/Reel/tree/gh-243-old-ie-loading) to test it with your stuff. Please confirm.

Tests suite still not pass in IE6/7 tho, but that's a separate [issue](/pisi/Reel/issues/245)..

**Comment by cookieseventeen** [comment]
This is great,Thank you very much!!!

**Comment by pisi** [comment]
You are very welcome :)

**Comment by pisi** [comment]
Merged and awaiting release. Until then, please use CDN's http://code.vostrel.cz/jquery.reel-edge.js or code from the [**development** branch](/pisi/Reel/tree/development).
