### ISSUE TITLE
initial autoplay direction + mousedrag and cw

### ISSUE THREAD

**Issue by ghost** [pisi/Reel#257]
How can I achieve the same behaviour in mousedrag and initial auto play ?

I'm trying to figure out a way to do that, and saw that in the [clockwise example](http://test.vostrel.net/jquery.reel/example/object-movie-clockwise-sequence/) happens what I'm saying. When we set `cw : true` the dragging makes the animation follow de mouse correctly, but the self-rotation goes "backwards" initially.

[Here's a case in my project](https://sunflower2.digitalpages.com.br/html/reader/191/31740/6/1), I need the initial autoplay to go on the same direction as mousedragging to the left.

**Comment by pisi** [comment]
Yes, this is a known issue (#241), which is already resolved, but hasn't been released yet. The patched code is now however available for your use in the [**development** branch](/pisi/Reel/tree/development).

Sorry for inconvenience.

**Comment by ghost** [comment]
Oh, sorry, didn't saw that issue. thanks
