### ISSUE TITLE
a conflict with css fonts?

### ISSUE THREAD

**Issue by ov** [pisi/Reel#261]
Meet a strange bug on the latest Chrome. Not sure if it is a Chrome issue, or a reel's one, but let's start here :)

So, here is the code:

``` html
<html>
<head>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.vostrel.cz/jquery.reel.js"></script>
    <style>
        * {font-family:'Open Sans';}
    </style>
</head>

<body>
    <h1>Some text above</h1>
    <img src="http://test.vostrel.net/jquery.reel/example/object-movie-camera-sequence/fish/DSCN0691.JPG" width="210" height="186" class="reel" id="image" data-images="http://test.vostrel.net/jquery.reel/example/object-movie-camera-sequence/fish/DSCN####.JPG|691..702">
    <p>Some text below</p>
</body>
</html>
```

Save it as HTML and open the file in the latest Chrome (ver  33.0.1750.117).

Here's what I see:

![image](https://f.cloud.github.com/assets/151412/2253630/2b3e6d48-9dc2-11e3-8e57-715198515d89.png)

I can click around the page - nothing helps, until I click the reel image. Then the texts appear:

![image](https://f.cloud.github.com/assets/151412/2253637/526cfb64-9dc2-11e3-9f82-c92120e11d16.png)

I tried the same in Chrome on OSX - the same result. It worked well in Chrome ver.32 on OSX until I updated it. Also tried in IE and Safari - it works just fine there. So it can be a Chrome issue, but before reporting there (as it happens only when the reel is active), I would like to ask you first.

Any ideas?

**Comment by ov** [comment]
looks like a [Chrome bug](https://code.google.com/p/chromium/issues/detail?id=336476), instead

**Comment by pisi** [comment]
Hopefully :) Thanks for making me aware of this though.
