### ISSUE TITLE
"Reach" not working

### ISSUE THREAD

**Issue by pxlwrkz** [pisi/Reel#262]
Hi,
maybe I did something wrong but I can't get the "reach" function to work. Neither with an image sequence nor with a sprite sheet. I also tried it in different ways with and without passing a speed parameter. Here are my tests:
http://pixelblitz.net/testing/reel/
http://pixelblitz.net/testing/reel/index_2.html
While I can go to a specific frame (see example), the reach function never works.
Is it a bug or did I do something wrong?

**Comment by pisi** [comment]
Yeah, you passed the extra parameters to the event incorrectly. jQuery [`.trigger()`](http://api.jquery.com/trigger/) has only two arguments and the second one `extraParameters` is an **array of parameter values**.

_For example: When you need to pass both frame (`20`) AND speed (`2`) to the event trigger, you need to use `.trigger("reach", [ 20, 2 ])`._

Only when you pass only one single extra parameter to the event trigger, you can omit the array syntax and use naked value.

_For example: When you simply want to reach frame (`20`) with the current speed, you'd use `.trigger("reach", 20)`._

See http://api.jquery.com/trigger/ for more documentation on how to work with events.

**Comment by pisi** [comment]
Beautiful V10 btw.!

**Comment by pxlwrkz** [comment]
Hey, thanks for your fast answer. It works when I use an array as parameter! Great!
Thanks again ..and thanks for your great tool :)
