### ISSUE TITLE
Running reel within Visual Studio Project causes error.

### ISSUE THREAD

**Issue by Boldonglen** [pisi/Reel#263]
Im currently trying to create a HTML5 CSS3 JS app for a Windows Surface. When i try to use this library it is causing the following error:

> 0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  For more information, see http://go.microsoft.com/fwlink/?

Any quick fix?

**Comment by pisi** [comment]
Well, I see this is kind of an issue with Win8 App Store apps. Besides wrapping the image, Reel injects two things into the DOM - a `div.reel-cache` at the end of the `body` and anonymous `style` at the beginning of the head.

Can you see in the developer tools if loading of the images has begun before the error?

Also a snapshot of the HTML after the error happened would be great!.

**Comment by Boldonglen** [comment]
The loading of the image has not loaded before the error. Nothing within my application has loaded. I am unable to provide a snapshot of the HTML after the error as the error seems to be happening before anything in initialized. This is the line within jquery-2.1.0.min.js where it seems to be comlaining: b.insertBefore(a,b.firstChild) Not sure if that helps

**Comment by pisi** [comment]
@Boldonglen can you please grab this [jquery.reel.js](/pisi/Reel/blob/gh-263-win8-app-fix/jquery.reel.js) and try out with this one if that changes anything?

**Comment by Boldonglen** [comment]
Perfect fix thanks you so much! Great plugin, great support. Keep up the good work!

**Comment by pisi** [comment]
That's a great news! :)

**Comment by pisi** [comment]
The previously posted code wasn't quite done. The final fixed code is available for pickup in the [**development** branch](/pisi/Reel/tree/development).
