### ISSUE TITLE
touch not working in IE 10

### ISSUE THREAD

**Issue by aaaaaaaaaarg** [pisi/Reel#264]
Accidentally opened this with a title only. 
I am trying to get Reel to work with a touchscreen on IE10. It works fine with the most recent firefox browser, so I am guessing it is an IE problem. Do you have any idea what I could do? I am testing with the examples here: http://test.vostrel.net/jquery.reel/example/index.html

**Comment by pisi** [comment]
Could you be more specific about your setup? I'd like to replicate your trouble, but sadly have no touchscreen Windows device. But I need a clearer idea about what hardware I'd need to get my hands on to test this out. Thanks.

**Comment by aaaaaaaaaarg** [comment]
Sorry. I am running a 64 bit windows 8.1 Lenovo Think centre. I think it is just something to do with my IE settings. If I click down with my finger on the screen, then move the mouse, it scrolls. However I cannot seem to get it to scroll with just touch alone. I also meant IE 11 not 10. The touchscreen I am using is an ELO 4201L.  I believe it is an optical touch.Reel works flawlessly in firefox though. And I just tried it on my android phone and it works as well. Do you know if ie handles touch input differently than other browsers maybe?

**Comment by aaaaaaaaaarg** [comment]
If I have stepping on, it steps once when I hold my finger down. Even if I just put my finger down and don't lift it. It seems to register hold as a press and release?

**Comment by aaaaaaaaaarg** [comment]
So... I have no Idea what happened, but today when I started up my computer it worked. I restarted my computer many times yesterday with no luck. The only thing I did differently was I turned off the power supply over night. Thanks for taking an interest in my problem, it seems that a full power down/unplug was the solution.
