### ISSUE TITLE
Teardown: improve cleanup

### ISSUE THREAD

**Issue by miguel-silva** [pisi/Reel#265]
Version: 1.3

Issue: After a teardown happens the .reel-cache divs are not removed, just emptied.

Solution: on line 1191 use get(_cache_).remove(); instead of get(_cache_).empty();

**Comment by pisi** [comment]
Oh, that is so true!

**Comment by pisi** [comment]
This fixes it. Thank you, Miguel!

**Comment by pisi** [comment]
Fixed code has been merged into the [**development** branch](/pisi/Reel/tree/development).
