### ISSUE TITLE
Scaled reel in responsive mode starts auto-play after reach function

### ISSUE THREAD

**Issue by pxlwrkz** [pisi/Reel#269]
Hi,
when I set "responsive" to true to make the reel element scalable there seems to be a problem if I want to use the "reach" function.
I put an example here: http://pixelblitz.net/testing/reel
Click "reachFrame(20)". After the frame is reached scale down the browser window in its width so that the reel element gets scaled down. Now it auto animates the element.
Is this a bug or did I miss something?

Edit: I just saw that user Ghisello posted a similar issue under #250

**Comment by pisi** [comment]
I'm gonna mark this as duplicate and let's continue in #250, which I just fixed btw.! :)
