### ISSUE TITLE
Fix image distortion (linear panoramas) [Suggestion]

### ISSUE THREAD

**Issue by moikirsch** [pisi/Reel#273]
As anyone can notice, when doing a 360 panorama there is certain distortion (straight lines look curved).

In the past some Java viewers and even some Flash based corrected this with some image manipulation.

I found the following which might help give an idea on how to fix it on a HTML/Javascript viewer:
http://adityasankr.tumblr.com/post/3458572813/html5-panorama-viewer

**Comment by pisi** [comment]
Nice technique indeed and can come in helpful for next versions. Thanks!

At the present though Reel displays only rectilinear panoramic images and it does not assume cylindrical projection. The software, which user uses to "stitch" his individual images into a rectilinear image already does this for you.
