### ISSUE TITLE
Base 64 encoded Image Support

### ISSUE THREAD

**Issue by kemarc** [pisi/Reel#29]
I don't currently see a way that if I provided a base64 encoded image in the source for the plugin to work. This would be great as it ensures a certain level of performance because base64 images loaded immediately.

**Comment by pisi** [comment]
Using a base encoded images is a very nice thing, especially when it comes to performance. Reel itself bundles-in mouse cursors this way.

You are right, that if you use base encoded image as IMG `src`, it won't work as Reel takes it and appends the suffix to look for the sprite.

Instead, you want to use your base encoded sprite as a value of  [`image`](http://jquery.vostrel.cz/reel#image) option, which goes right around this. Similarly you can use array of base encoded frames as a value of [`images`](http://jquery.vostrel.cz/reel#images) option.

Please, let me know if that works.

Best of luck,

.pisi
