### ISSUE TITLE
Link to the drupal formatter on the project page

### ISSUE THREAD

**Issue by larowlan** [pisi/Reel#31]
Hi
Firstly, thanks for your great work here - also congrats on the excellent documentation - a pleasure to work with.
I've made a Drupal module that packages this plugin as a formatter for image fields in Drupal 7.
The content author has to upload two images, one for the static, one for the reel sprite - they can choose their config options (a limited set) using the ui and then get some jquery reel goodness on their page.
Would you consider linking to the Drupal project from your site?
http://drupal.org/project/reel
Demo here: http://www.thebronxbrewery.com/node/41 - although this might be taken down at some stage, we'll get a demo link up from the project page in which case.
Lee

**Comment by pisi** [comment]
Hello Lee,

thank you for your kind words and especially for your energy you must have put into the Drupal formatter.

I'm already well aware of your work and I've linked it in the wiki here: http://github.com/pisi/Reel/wiki/Reel-on-production-websites in the _3rd Party Tools_ section nearly a month ago.

It is very exciting, that such integration efforts emerge and I'm very happy about it in fact :) And I do want to go event further to promote hopefully all of them. Right now I'm in the middle of updating the Reel homepage for the version 1.1.2 released very soon (maybe even this weekend) and I count your link in. In the upper part where the ticks for the features reside and the last line will be: 

**"Emerging tools for [Drupal](http://bit.ly/i1vDL5) , [Dreamweaver](http://adobe.ly/fAuflI) or [Poser](http://bit.ly/apjdDT) by the community!"**

I will let you know when it's on-line.

.pisi

**Comment by larowlan** [comment]
Thanks, looking forward to the new release - I'll update the module
accordingly.
My associate Nicholas in Peru has got the reel formatter working with
Drupal 6 too, there is a workaround involved as Drupal 6 doesn't
natively support jQuery 1.4, we're hoping that will be resolved in time.

Thanks again
Lee

**Comment by pisi** [comment]
Lee, several days ago I managed to actually release Reel 1.1.2 and the link has been included in the subsequent [website](http://jquery.vostrel.cz/reel) update.

Thanks again for brigging Reel into the Drupal world and its users!

Btw. aren't you into Wordpress too? Judging by this [discussion](http://bit.ly/mGekI2) similar tool might be needed there too ;)

.pisi

**Comment by larowlan** [comment]
Thanks
I'll try and find sometime to re-roll the Drupal module with the new
version.
Unfortunately I don't know Wordpress (I've never even installed it
(gasp)). Perhaps I should look into it further...

Lee

**Comment by larowlan** [comment]
Hi
I've rolled 7.x-1.0-beta4 of the formatter using the new 1.1.2 version
as well as making some enhancements to the way the js files are attached
to the content to leverage new features available in Drupal 7.
Lee

**Comment by pisi** [comment]
Cool!
