### ISSUE TITLE
Review need to update Drupal Formatter with Reel 1.1.3

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#35]
Lee,

I took the liberty to add you as a collaborator to the Reel project here on Github and will be my pleasure if you accept. As a collaborator you will be able to receive tickets informing you about an upcoming release, so that you won't receive release announcement post-release like this one ;) I promise I won't bother you and will assign you tickets just from time to time, mostly before Reel releases to ideally sync up with Formatter releases.

Very recently Reel 1.1.2 was identified to be using an `.attr` class name definition syntax unfortunatelly problematic and incompatible with jQuery 1.6 released just a few days ago. This weekend I've addressed this sudden issue (GH-33) and I've changed the syntax to restore the declared 1.4.2+ compatibility. The compatible version is rolled out as fresh Reel 1.1.3, which is also the latest version served by the [CDN](/pisi/Reel/wiki/CDN).

I don't really know whether Drupal sites are deployed with a fixed version of jQuery or if they use latest. Because if they do use the latest jQuery 1.6, your Formatter would have to be updated.

If your Formatter uses jQuery 1.5.2 or lower, just ignore this and simply close this issue. The update is neccessary only for jQuery 1.6.

Thanks for your time!

.pisi

**Comment by larowlan** [comment]
Thanks,
At present Drupal 7 runs against 1.5 or lower but with time will get to
1.6.
FYI Drupal core ships with a fixed version of jQuery (whatever the
current version was at time of release). As new versions of jQuery are
released, you can update your Drupal by installing the jquery_update
module (drupal.org/project/jquery_update) this replaces the javascript
(at run time, not physically on disk) with the newer files and any other
js in Drupal that requires updating for the new version. So as the
compatibility is written/tested, jquery_update moves along with newer
versions. You may or may not be familiar with Drupal but a key mantra is
'don't hack core' ie keep the core files shipped with Drupal as they
are. This makes updating a breeze as you don't have to go back and
reapply patches etc. Drupal is flexible enough that (almost) anything
can be modified without touching the core distribution - hence the role
jquery_update plays. In this case javascript files are added to a stack
by modules/core using drupal_add_js or drupal_add_library and then
before the head of the page is rendered, the stack of files is passed
off to any 'interested' module to examine and modify as required, the
resultant returned stack is then output in the head of the page. This is
called an 'alter hook' in Drupal speak and is key to Drupal's
flexibility. See http://api.lullabot.com/jquery_update_library_alter/7
for more information, this is what Drupalers call 'an implementation of
hook_library_alter' - ie a php function that follows a particular naming
pattern and hence is seen by Drupal to be 'interested' in modifying (in
this case) Drupal's library files. If you're already familiar with how
Drupal works, then please ignore my ramblings...
Finally, something light-hearted: http://heyrocker.com/hack_core.jpg

Lee

**Comment by larowlan** [comment]
BTW I accept the collaboration, although I think the Reel plugin itself
is beyond my Javascript skills

**Comment by pisi** [comment]
Excellent! Thanks for the throughout explanation as all I know about Drupal is that it's PHP. And that isn't much... ;)
