### ISSUE TITLE
Bug with mousewheel

### ISSUE THREAD

**Issue by danieltome** [pisi/Reel#37]
Using jquery 1.6.1, mousewheel from: https://github.com/brandonaaron/jquery-mousewheel
and latest jquery reel.
When performing a wheel event on the image, it tries to load 'undefined' images and it just loops trying to load an infinite number of undefined urls..

**Comment by pisi** [comment]
Hey Daniel,

not sure where's the problem. Reel 1.1.3 (latest) works just fine with jQuery 1.6.1 (just confirmed) and allthough I'm using (and bundling) version 3.0.2 of Brandon's plugin it should still work (also his latest 3.0.4 works without a glitch).

Try to run the `test/index.html` in the downloaded zip file - failures in these indicate problem in Reel. Also `test/sampler.html` has many test samples for you to try out. Both of these run latest Reel against latest jQuery with 3.0.2 version of mousewheel plugin.

But, based on all those `undefined`s, I suspect something is wrong in your setup maybe. Being more specific about your setup and environment would help.

.pisi

**Comment by danieltome** [comment]
Hi pisi,

I uploaded my test here: http://danieltome.com/tests/reel/
I think it might be because I am not using a sprite, but an images array.
I will debug it to see what's causing this.

cheers,

**Comment by danieltome** [comment]
Sorry.. my bad.. I had the wrong jquery.weheel version.
This is works as expected!

**Comment by pisi** [comment]
No problem, Daniel. Glad to see, that you got it right finally.
Btw, what version number of the mousewheel plugin was it?

**Comment by danieltome** [comment]
It wasn't that plugin. I managed to download a different mousewheel plugin. That was my mistake sorry.

**Comment by pisi** [comment]
Ah, I see. Good then.
