### ISSUE TITLE
.reel + j360 = true?

### ISSUE THREAD

**Issue by kronandr** [pisi/Reel#38]
Hi all.
I'm trying to connect this .reel-plugin to my j360-plugin to make my 360 degree images scrollable with the mouse. Also I'm trying to create the nice effect The Panorama-image on the demonstration-page has, but I fear I might have too little experience in jQuery to really know what i'm doing.

anyone want to help?

**Comment by pisi** [comment]
The j360 plugin appears to do things in a completely different way. Reel makes a regular image tag an interactive one withou any additional HTML code (thus it degrades gracefuly on non-JS browsers). j360 instead uses an arbitrary DIV with all frames as imagey inside it and converts this into the interactive container.

I don't see a clear way (nor a reason for it) how these two would work together ... Sorry
