### ISSUE TITLE
How to refresh the reel to the starting frame?

### ISSUE THREAD

**Issue by danjirawat** [pisi/Reel#40]
Hi pisi,

Would you please help me? I created the reel then spin it to a random frame and hide it. When I show it again I want to refresh the reel to go to the first frame. I know how to get the data from the reel but I'm not sure how to set the data back to it.

Thanks in advance,
Jirawat

**Comment by danjirawat** [comment]
Hi,

I already find an answer myself. Here it is.

$('.jquery-reel').trigger('frameChange', '1');

JQuery reel is the best!
Jirawat

**Comment by pisi** [comment]
Oh, well good then :) Forgive me such a slow response.

Your answer is indeed right, Jirawat. Just to do it top notch correct, pass in the frame number as a number, not as a string.

```
.trigger('frameChange', 1);
```

**Comment by danjirawat** [comment]
Thank you pisi :-)

**Comment by Spone** [comment]
It seems that now the right way to do it is:

``` js
$('.jquery-reel').reel('frame', 1);
```

`.jquery-reel` being your selector

**Comment by btburton42** [comment]
@Spone glad I found this! the documentation is so horribly out of date and once I used this it worked. great find!
