### ISSUE TITLE
Can 'footage' option default to 'frames'?

### ISSUE THREAD

**Issue by SimonEast** [pisi/Reel#43]
Currently, the `rows` option defaults to 0 (single row).

The problem is that by default, the reels I am testing only display 6 images from my sprite.  Even when I set `frames` to the correct value, still only 6 are displayed.  I finally figured out I had to change `footage` to the same as `frames`.  Shouldn't `footage` be automatically set to `frames` if `rows = 0`?

Simon.

**Comment by pisi** [comment]
Simon,

what you say is very reasonable. When you have all your frames in one long stripe, in your case `frames == footage`, but that is rather an edge case as sprites can be organized freely. For example if you take later half of your frames and place them below the first half, you would halve your `footage` and use the very same `frames` setting.

I think there is a misunderstanding of what "row" is in Reel terms. When implemeting this feature request for multi-row setups I had some doubts about the naming, but in the discussion we couldn't come up with a better term for it. "Row" simply isn't a set of frames aligned horizontally in the sprite. "Row" refers to a set of frames having the same tilt angle. There is a [PDF](http://plugins.jquery.com/files/issues/reelsheet.pdf) exmplaining the role of `footage`. It doesn't take multi-rows into account, but I hope it would help shed some light on it.

So the answer is no it should not do that automatically. The default use case is a sprite with 36 frames arranged in the sprite in a 6 x 6 grid (`footage` 6) and yet it is a single row setup. And when having this sort of sprite arrangement, `36 != 6`
