### ISSUE TITLE
Reel + Fancybox == Error

### ISSUE THREAD

**Issue by mackil** [pisi/Reel#44]
Launching a rotating image in Fancybox works the first time, but once the Fancybox is closed and opened again, a static image is all that is shown.

**Comment by pisi** [comment]
Thanks for reporting this. Could that be IFRAME-related? Test case (or seeing your implementation) would be great.

**Comment by mackil** [comment]
In putting the test case together in jsfiddle, I managed to fix it. Sorry for the false error there. The problem was not with the plugin after all, but in my implementation of Fancybox. Sorry about that. Thank you for your time.

**Comment by pisi** [comment]
Oh, excellent then :)
