### ISSUE TITLE
Feature Request: Image Preloader rather than Percentage Bar

### ISSUE THREAD

**Issue by marissajmc** [pisi/Reel#52]
As of v1.1.3, the Reel preloader is set as a div that increases its width across the screen as the sprite/images are loaded.
The only option you can set for the preloader is the height of this percentage bar.

What would be great is an option to set what type of preloader we want - a percentage bar OR a static image eg. loading circle gif.

If I set the preloader as a loading gif, the image moves across the screen in IE7 which looks odd.

I just want a static image to hide the frames while they're loading, rather than a percentage bar.

Update: commenting out this line stops .jquery-reel-preloader css bg image from moving.

Line 324
<code>$preloader.css({ width: 1 / img_tag.frames \* img_tag.preloaded \* space.x })</code>

**Comment by IsraelThompson** [comment]
Heh, I wondered this same thing... I just threw a div over the top of my reel using z-index and initiated the reel as my preloader div fades out (using some jquery trickery)... I'll have a look at the line you pointed out!

Izz

**Comment by pisi** [comment]
Guys,

while it looks like a great feature, it may bring an additional complexity, which I would like best to avoid especially when I believe there's a CSS-only way to do this.

Using the `"jquery-reel-preloader"` class name you can already apply any style you like on the node. As Reel sets few properties on its own (the color, size, the growing), you would need to use the `!important` CSS directive in your style to override them.

For example:

```
.jquery-reel-preloader {
    background: green !important;
    width: 50px !important;
}
```

would result into fixed width greenish preloader.

**Comment by pisi** [comment]
I just added this to the [FAQ](/pisi/Reel/wiki/FAQ)

**Comment by IsraelThompson** [comment]
Nice! Now how about taking a look at my inquiry? I've been dying to hear your thoughts! ;)
