### ISSUE TITLE
Bug 1.1.3 - background-image: initial; array image disappears

### ISSUE THREAD

**Issue by marissajmc** [pisi/Reel#53]
I am loading jquery Reel spinners using ajax and image arrays. If I click around the page and then roll back over the Reel instance, the Reel image disappears and is replaced with an x. It says it's undefined.

The .jquery-reel-interface div css becomes:

<code>style="position: absolute; left: 0px; top: 0px; width: 800px; height: 320px; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(0, 0, 0); opacity: 0; background-position: initial initial; background-repeat: initial initial;"</code>

Any idea what this is?

Seen in IE7 and Chrome.

**Comment by pisi** [comment]
Hi Jerallyn,

do you teardown the original instance when loading a new one?

**Comment by pisi** [comment]
Also note, that the `.jquery-reel-interface` DIV should look like this. It actually is a black fully transparent block sized to match the image and absolutely positioned overlaying it. The image underneath is then being manipulated based on user interaction events originating from the interface overlay.

So this piece of code won't help. A link yould be best in this case I think.

**Comment by pisi** [comment]
I assume the above answer did the job for you and am closing this issue. Feel free to reopen otherwise.
