### ISSUE TITLE
Liquid Height Resizing

### ISSUE THREAD

**Issue by brianself** [pisi/Reel#56]
First of all you've done an amazing job in writing this plugin. The side-by-side comparison with Flash as far as battery life is fantastic. This plugin uses a fraction of the computing power and battery of Flash to accomplish a comparable presentation. 

I'm wondering if there is a way to make the panorama height fluid in a div so that it resizes along with the size of the browser - much like Flash does. I've tried using your custom "klass" keyword, and I can adjust the width (since the panorama is wider than any screen) but the image height remains static despite specifying a height in the #klass css. The klass class does change the actual div (jquery-reel) background size (I made the background black so it's obvious) but the image inside does not resize with the klass class.

Are there any built-in controls in the Javascript that I'm overlooking or any css overrides that I could do to resize the image inside the query-reel class or the klass class? I'd prefer to use a single image that resizes with the browser than to use css to load different sized panoramas that depend on the size of the browser window.

Any thoughts or suggestions in creating this automatically resizing Reel window like Flash does?

Thanks in advance!

**Comment by brianself** [comment]
To clarify - I'm trying to set the height to be a percentage of the browser window rather than a fixed pixel height so that it will scale.

**Comment by pisi** [comment]
Brian,

what kind of setup you have? One long stitched panorama image? If so, the image is applied to the node as CSS background image and that is why it doesn't resize along with the div itself. I'm not entirely sure if scaling of CSS background images is even possible.

And thank you for the heart-warming first paragraph :) I'd like to quote it on the new upcoming Reel website, if you don't mind. Thanks!

.pisi

**Comment by brianself** [comment]
I'm aware of a couple of JQuery plugins that have scaling backgrounds. JQuery SuperSize 3.0 does this. But I wouldn't know where to begin to combine those features with the Reel plugin.

**Comment by pisi** [comment]
Brian,

please, don't get me wrong. Scaling of backgrounds is entirely possible if you have the background as `src` of an `<img>` tag - you simply adjust its `width` and `height` to whatever the JS measures after a `resize` event has happened. This is the way SuperSize does it and the same approach would work well also for image sequences in Reel. But not for sprites. 

Sprites are asigned to the cleared `<img>` tag as **CSS background** images, which doesn't have any "given" dimensions and are not easily scaled. Such image can then be shifted in all directions, but not efectivelly scaled. There are CSS directives like `-webkit-background-size`, but they are still browser-specific as far as I'm aware.

So to conclude, if you use Reel's `images` option to feed it an array of individual images, you should then be able to use `width` and `height` attributes of your image to scale it.
