### ISSUE TITLE
Refresh reel with diffrent reel image

### ISSUE THREAD

**Issue by doa4real** [pisi/Reel#57]
great plugin ! :)
i'm not sure how to change the reel image ... whats the best way to do this

**Comment by AlphaKilo615** [comment]
make sure your image name has -reel.jpg

For example: <img src="image.jpg" id="360image" />

that "image.jpg" will automatically look for the file name that has "-reel.jpg" so it will be "image-reel.jpg"

**Comment by pisi** [comment]
Right now the best way to change the Reel image is to tear it down, change the `src` of the `<img>` and setup it again. Like so:
1. Once you start the Reel:
   
   ```
   $('#my_image').reel();
   ```
2. To switch the image:
   
   ```
   $('#my_image').trigger('teardown');
   $('#my_image').attr('src', 'the_new_image.jpg').reel();
   ```

Be advised, that a bug in current vertsion (resolved in the upcoming) causes the `.trigger()` call to return different DOM node and thus can not be used in chain with the `.attr()` or `.reel()`.

**Comment by messutied** [comment]
Hi great work pisi, but im trying this with multiples images and after changing the reel i cant rotate by dragging with the cursor, only with the wheel, am i doing something wrong?

Thanks!
