### ISSUE TITLE
Panorama will not loop

### ISSUE THREAD

**Issue by elissaios** [pisi/Reel#6]
Hello there, I revisited the script after a few weeks I found my self troubled by the fact that the panorama (stitched) doesn't loop anymore, including the example on your website.

Here's a test:
http://www.greekhome.gr/demo/gr/panorama.php

Uppon reaching the far right end of the image, the script will jump again to the 1st frame instead of contuining (looping / stitching) the image. The same occurs if you scroll to the left end, which brings you again the last frame.

Let me know :)
Best regards,
Elissaios Koumridis.

**Comment by elissaios** [comment]
As an addition, 1.0.3 works with looping but 1.0.4 doesn't.

**Comment by pisi** [comment]
Wow, a serious bug. Will fix it right away.

**Comment by pisi** [comment]
The issue has been fixed.

It loops just fine on the site, however also an automated test for this issue has been added to Reel Test Suite:
http://jquery.vostrel.cz/reel/source/test/index.html (Issues › GH-6)

Grab the newest master and you'll be just fine. Please test it out and let me know.

Also thank you for your donation!

**Comment by pisi** [comment]
OK, closing.
