### ISSUE TITLE
`scrollable` option for touchy devices

### ISSUE THREAD

**Issue by togglemedia** [pisi/Reel#60]
Reel works fine on an iPhone when the page that the reel is on is fully zoomed out, but when a user pinches and zooms in, and begins to finger drag over the reel, the reel sometimes activates and the page scrolling sometimes activates. More often than not, the page scrolling activates. Is there a way to disable screen scrolling, so only the reel receives the finger input?

**Comment by pisi** [comment]
Hey,

litlle bit of background first:

Right now, to satisfy GH-7, the scrolling detection is left up to the browser itself by not stealing the touch events and merely listening to them instead. This makes page scrolling and gestures (like pinch for zoom) possible to be performed above the Reel image.

The primary concern is to not let user to get lost. Without actions taken in GH-7, if user zooms in the Reel image too much in, she wouldn't be able to "get out" from there - page wouldn't scroll as dragging would "reel" instead, pinch out or any other gesture not possible. For example scrolling over a larger full-page-width Reel is also extremely difficult then.

This doesn't apply to multi-row and orbital setups though.

So, your request sounds reasonably and I can easily imagine new option `scrollable` with `true` being the default value. Setting `false` would result in what you ask for - an exclusivity on the touch events, which would prevent scrolling of page initiated from above the image (much like multi-rows do now).

Is there anyone else out there, who would appreciate such option/feature? Please let us know here.

**Comment by pisi** [comment]
I started toying with this idea in a separate branch [gh-60-scrollable](/pisi/Reel/tree/gh-60-scrollable), so please don't mind the commits linked to this issue - some of them might be rubbish (like the first one ;). I currently have no other sensible way of testing on iPad than doing it on-line by commiting to Github...

**Comment by togglemedia** [comment]
Thanks Petr. Just in the initial phases of developing an interactive piece that will require this, I'll let you know how it goes.
