### ISSUE TITLE
trigger('play') has no effect when using opening animation

### ISSUE THREAD

**Issue by LuukBarten** [pisi/Reel#61]
I'm loading a reel with 20 frames that are loaded with the mini_frames() function which returns an array of files from my path.

```
$('#my_image').reel({
    entry:      1,
    opening:     2,
    path:       'images/motor/',
    cw:         true,   
    images:     mini_frames(20) });
```

Apart from loading the reel i've included a "controls" div with appended buttons that I would like to use for controlling the reel.

```
$('#controls')
    .append($('<button/>', { text: 'play' }).click(function(){ $('#my_image').trigger('play') }))
    .append($('<button/>', { text: 'pause' }).click(function(){ $('#my_image').trigger('pause') }))
    .append($('<button/>', { text: 'stop' }).click(function(){ $('#my_image').trigger('stop') }));
```

The reel loads and loops twice due to the opening en entry options. Then it stops. So far no problem. However, I can't seem to trigger the "play" function with the button after the opening has halted. I've tried adding the "speed = 1" option, but this will only result in the reel directly playing after the opening animation. Using "delay = -1" won't work either. I end up setting "delay = very large number" in order to mimic a stop.

```
$('#my_image').reel({
    speed:      0.5,
    entry:      1,
    opening:    2,
    delay:      999999,
    path:       'images/motor/',
    cw:         true,   
    images:     mini_frames(frames) });
```

**Comment by pisi** [comment]
Hey Luuk,

the animation control events (`play`, `pause` and `stop`) are available only for animated Reels (those with a non-zero `speed` option).

**Comment by LuukBarten** [comment]
Hi pisi,

Thank you for replying. If I use the speed option, the reel still continues right after the opening animation. I'd like to have a stop after the opening animation without having to use the "delay hack".

**Comment by pisi** [comment]
That's what it's supposed to do.

If you want to pause after the opening, you use `delay` to specify the length of the pause and `speed` to specify the speed of followup animation.

If you want to stop after the opening animation, you simply don't set any `speed`. In that case there's no animation (except the opening) and no events to control the animation.

To sneak peak behind the curtain of the upcomming release, the end of the opening animation will now be announced by new `"openingDone"` event, so you will then be able to use `speed` option to enable animation control events, trigger `"stop"` manually while still having the `"play"` event available.

**Comment by pisi** [comment]
Hey @LuukBarten, could you please give the latest [development](/pisi/Reel/tree/development) version a shot. Some work has been done on the way animations are starting, so it could have some effect on your case. Thanks and happy holidays!
