### ISSUE TITLE
Return Current Frame

### ISSUE THREAD

**Issue by reformatco** [pisi/Reel#63]
I am going using your plugin in a web app that needs to open a zoomed image when you click on a 360.

How do I return the current frame number? I can't seem to find anything in the documentation.

**Comment by reformatco** [comment]
Doesn't matter, I did a bind on the frameChange to get the current frame

**Comment by pisi** [comment]
Hey Ben,
all internals are stored as a DOM node data on the instance, so from within any event handler you can access anything like so:

```
$('#reel').bind('frameChange', function(){
    $(this).data('frame') // gets current frame
});
```

Please inspect `test/unit/data.js` for a test listing all available values in instance's `.data()`
