### ISSUE TITLE
3D with separate images

### ISSUE THREAD

**Issue by paulinedupraz** [pisi/Reel#66]
It can be really great if we can use rows and footage with separate images to have the 3D effect.

**Comment by pisi** [comment]
I'm sorry, but I don't seem to get you. Can you please explain more?

**Comment by paulinedupraz** [comment]
Sorry it wasn't really clear… If we use an array of images it's impossible to use the X and Y axis. Is it possible to do something for that?

**Comment by pisi** [comment]
Well, basic Reel setups span 360° horizontal (X axis) - that's one horizontal _row_ in Reel terminology.

In case you have the same set of 360° view from a let's say slightly different perspective (you've elevated the camera a notch), you have another _row_. You can have as many rows as you'd like. By telling Reel the number of such rows you have using [`rows`](http://jquery.vostrel.cz/reel#rows) option, you switch Reel to a so called **multi-row** mode. In this mode Reel is sensitive also to vertical mouse movement (Y axis), which effectively switches between rows and horizontal movement switches between frames on respective row. Plase check out the [test sampler](http://test.vostrel.cz/jquery.reel/test/sampler.html) and click on Multi-Row Object Movie Sequences sample to get an idea.

There also is a **dual-orbit** mode also showcased there. This mode offers two independent orbits around the object - usual horizontal plus one vertical - crossing each other at one spot. It is brought up by the [`orbital`](http://jquery.vostrel.cz/reel#orbital) option. As I suspect you are after the multi-row mode, I won't go into details of this now.

Is this what you're up to?
