### ISSUE TITLE
Odd behavior in iPad landscape orientation

### ISSUE THREAD

**Issue by kidlucky** [pisi/Reel#78]
i'm trying to use reel on an ipad in landscape orientation. since each of my frames are 1024 x 768, i'm using images rather than a sprite. i've set vertical to true so i can swipe horizontally. i've also set loops to false.

here's what happens: my 12 frames will load and then image number 7 will be displayed(frame 1 is specified). i can swipe left and experience the next 4 frames but a missing image will be displayed as the last image(it's not missing). also, i can't swipe right at all to view the images i saw loaded initially. 

if i set vertical to false reel works perfectly, you're just swiping perpendicular to the images(not intuitive).

hope this makes sense, and thanks in advance for your help!

**Comment by pisi** [comment]
So far the [`vertical`](http://bit.ly/reeljs#vertical) option is indeed used to flip horizontal interaction axis for vertical, but ONLY in the dual-orbit mode, which is triggered by [`orbital`](http://bit.ly/reeljs#orbital) option and offers a combined horizontal+vertical axis object movie. The `vertical` option then specifies, what will be the initial axis.

**Comment by pisi** [comment]
To add: the possibility of going pure vertical is a suggested improvement filed under #73
