### ISSUE TITLE
Help to use the "area" option

### ISSUE THREAD

**Issue by bricofera** [pisi/Reel#8]
Hi!
I need to use the area option because on iphone and android if you zoom to almost fullscreen the part of the page with the reel-image then you can not move the page up or down, because the pinch to move is disabled over the image. I would like to reduce the area sensitive inside the image to solve this problem.

Can you help me to use the area option? I didn't found any example or guide to use this option :(

Thanks very much, your work is wonderful, best regards from Italy!

**Comment by pisi** [comment]
This is closely related to yet unresolved issue https://github.com/pisi/Reel/issues#issue/7 where it should be solved.

However, if you wish you can overcome this by using the `area` option. When not defined, the entire image real estate is used as an active area for interactions. When a jQuery object `area` is defined, it is used instead.

F.e.:

```
<img src="my_image.jpg" id="my_image">
<div id="#my_reduced_area"></div>
```

And you start Reel with `area` option:

```
$('#my_image').reel({ area: '#my_reduced_area' });
```

Reel will be controllable (interactive) only through the `#my_reduced_area` and dragging, wheeling or anything on the original image won't do anything. You have to drag on the reduced area to really control the Reel.

.pisi
