### ISSUE TITLE
image :	myotherpictype

### ISSUE THREAD

**Issue by ag-coder** [pisi/Reel#80]
hello

first i have to say big thanks for this great plugin!

i have two differend pic-types i wanna use.
first a preload gif-animation and the turn-pic as a big PNG.

reel use by default the same pic type for the preload-pic and the viewpic.

now i use the option " image : 'mybig.png' " to change from gif to png.
it works on firefox but in safari and chrome not!

seem i do the wrong thing?
how can i change from the gif to a png?

thanks for help

**Comment by pisi** [comment]
Hi,

I've put up a little jsfiddle demonstrating [how `image` option is used to load different image file type](http://jsfiddle.net/5x972/1/) and it works well in Chrome loading first PNG and then JPG sprite. Please compare it to your application.

You may also have a problem in the first GIF image non existing. The mechanism assumes both files are loadable and the replacement happens on first image load.

**Comment by ag-coder** [comment]
thanks for your help

yes it works on chrome 
but still wont work with FF8 & Safari (IE not tesed)!

is it the new jquery 1.7.1?

**Comment by pisi** [comment]
I'm pretty sure, that it works in FF & Safari too, just not in the jsFiddle environment, where complete Reel initialization fails on "Permission denied" when accessing the document containing the `iframe` Reel image resides in on jsFiddle. Please see issue #83 for details.

**Comment by ag-coder** [comment]
ok thanks for your effort!
