### ISSUE TITLE
weird chrome behaviour after reload

### ISSUE THREAD

**Issue by cindreta** [pisi/Reel#81]
So i tested this in firefox l8 and 9 and everything works just fine and expected. But in Chrome(i tested on version 17 and a few below) some weird stuff happens. If you load the reel for the first time everyhing works fine, the instance is rotating at normal speeds, play stop works and so on. BUT WHEN YOU JUST RELOAD the page the reel either rotates at a very very low speed, play stop doesn't work and it just becomes sluggish and not responsive. I use the 1.1.3-devel version. I dont know how to fix this, i don't know if anthing stays loaded somewhere and is causing this problem. But i would like to at least know why :) thanks.

**Comment by iscold** [comment]
If you pay attention, even the examples (http://test.vostrel.cz/jquery.reel/test/sampler.html) doesn't work properly on Chroma. I am experience the same problem. If you look in the network traffic is it possible to see that it is reloading all the images again.

**Comment by iscold** [comment]
I my case, it is not working at Chrome at all. It is always weird and it is possible to see that it is reading all the images through the internet. Locally it works perfectly, but on the web it is not. I also would appreciate a help.

**Comment by iscold** [comment]
Seems that it is a problem with sequences, all sprite examples are working properly, mainly because they don't need to reload the images....

**Comment by pisi** [comment]
Well that is the correct behavior, I think. When you hit reload, it reloads.

You see, Reel doesn't do anything, than filling a `src` attribute of an image. So, actually the caching (or not) is purely a result of browser's negotiation with the server and Reel doesn't influence this. When you hit reload, browser does what it's supposed to do - it reloads all resources and behaves according to a HTTP code it receives back for each of them. Either it receives 200 "OK" accompanied by the actual resource or it gets a 304 code "Not Modified" alone and reuses the image from cache. 

I'm pretty sure, that my testing server isn't configured for this yet and throws 200 every time, causing the what seems to be an additional load of all images. So it may be the same thing maybe?
