### ISSUE TITLE
Issues with IE8 and jQuery 1.7

### ISSUE THREAD

**Issue by lopsided** [pisi/Reel#84]
Hey,

Im getting the "Object doesn't support this action" error in IE8 with jQuery versions >= 1.7. It works fine with any versions < 1.7 and seems to work in all the other browsers with either. I have been testing with the latest release (1.1.3) and I've also tried with the latest dev release. 

I would just use the older jquery version except I need the '.on' events introduced in this version. 

Any ideas?

Cheers,
Tom

**Comment by lopsided** [comment]
Ive put an example of this behaviour up here:

http://instantiate.co.uk/reel_with_jquery1.7/test.html

**Comment by pisi** [comment]
Thanks for the example. One problem though - you link Reel from `http://fl3/js/jquery/`, so it doesn't work. Please make it point to `http://code.vostrel.cz/jquery.reel.js` instead. Thanks again! ;)

**Comment by lopsided** [comment]
Whoops sorry. Ive updated it now thanks

**Comment by pisi** [comment]
I believe this line in your source may be the cause:

```
<img id="360-image" src="images/pic0.jpg" width="545px" height="392px" alt="testpic" />
```

It should look like this:

```
<img id="360-image" src="images/pic0.jpg" width="545" height="392" alt="testpic" />
```

You don't put units into the `width` and `height` attributes. No other units than pixels can be used to define dimensions of HTML `<img>`, so the `px` unit is implied and you define only numeric integer value.

Feel free to reopen if that's not it.

**Comment by lopsided** [comment]
Hi pisi, this was another remnant of my testing. I have updated this and still have the same issue. I would reopen the issue but I dont have permission! Thanks, Tom

**Comment by pelister** [comment]
I too have the same issue with IE 8  "Object doesn't support this action"

included http://code.jquery.com/jquery.min.js in my html

works fine with other browsers, IE 8 cracks my head..

**Comment by lopsided** [comment]
Hi pisi, have you made any progress on this? If you have any ideas let me know, Ive been trying to crack this for a while but not got very far. If you have any suggestions Id love to hear them, see if I can help with anything.

**Comment by pelister** [comment]
yeah mee too looking for a solution on this

**Comment by pisi** [comment]
@pelister has made a very useful observation, that the version of mousewheel plugin, which is shipped alongside Reel is incompatible with jQuery 1.7.x and IE combination.

Please update your copy of [mousewheel](/brandonaaron/mousewheel) with the latest version, it should free you of the  "Object doesn't support this action" error. It still won't drag correctly though, for that the changes done in the augmented-frames branch are needed and that one isn't online yet. Will keep you posted.

**UPDATE:** Scratch that, the error is caused by the above PLUS a conflict of `start` event. The above won't be enough to kill the error...

**Comment by pisi** [comment]
Can you please report back to me, if the fresh development version [1.1.3-devel](/pisi/Reel/blob/development/jquery.reel.js) makes any difference in your attempts to get along with IE. It should... Mind the aforementioned necessity of upgrading your [mousewheel plug-in](/pisi/Reel/blob/example/inc/jquery.mousewheel.js). Version 6.0.2 didn't get along with jQuery 1.7 very well.

**Comment by lopsided** [comment]
Hey @pisi, still having the same problem with this latest dev release (have updated the test page above), though I havent done anything with the mousewheel plug in because I was not using it before. I am only linking jquery 1.7.1 and this latest dev reel release on the test page. Do I still need to do anything with the mousewheel plugin?

**Comment by lopsided** [comment]
Ive made a copy of the latest dev release and commented out all references I can see to mouse wheel behaviour. Still getting same problem (http://instantiate.co.uk/reel_with_jquery1.7/test2.html).

**Comment by pelister** [comment]
hi lopsided take a look on this 

using jquery.reel latest dev branch( https://github.com/pisi/Reel/tree/development)
jquery 1.7.1
mousewheel 3.0.6

works fine on all browsers,  if you want to take a look http://orscella.com (Joomla plugin development stage).

I have noticed two problems though..
1. stop button do not work after page loads. but works when we perform some other actions - mouse drag , mouse wheel etc.
2. conflict with mootools on opera only.

**Comment by lopsided** [comment]
Hey pelister, 

Ive updated my test page with the same links to reel and mousewheel as on the orscella link. I also copied the set up code (this bit: $('#testtn').reel({ ....})). There is definite progress! The reel is rotating now, but there are 2 problems I can see which are occurring in FF now as well as IE. All of the frames are appearing on the page and there is no indicator! Am I doing something wrong here? 

I can see the orscella page is working great but there is a lot going on on it; maybe Ive missed something that needed extracting too...?

See it here http://instantiate.co.uk/reel_with_jquery1.7/test.html

**Comment by lopsided** [comment]
ps. The indicator I could live without ;)

**Comment by pelister** [comment]
hi lopsided, the setup code on orscella is generated by a php file.

I read images from specified directory, sort them in asc order and pass the array to reel.

if your running it as a script better try this way, instead of passing path: images/ which is in your code.

pass the absolute path like home/..../html/sitename/folder

or you no need to use path option pass the image array with full link for each image as you see in my code.

if you need php test code or html version that  I use I can give you ... but I dont know how to attach files here

**Comment by lopsided** [comment]
Hi pelister,

I must be missing something still. 

This is all Im linking to in < head >:

< script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js ">< /script >
< script src="http://orscella.com/plugins/content/turntable/files/jquery.reel.js" type="text/javascript" >< /script >
< script src="http://orscella.com/plugins/content/turntable/files/jquery.mousewheel.js" type="text/javascript" >< /script >

In < body >:

< img id="testtn" src='http://orscella.com/images/testtn/00001.png' width='300' height='200' / >

< script type="text/javascript" >
//<![CDATA[
$(document).ready(function() {
    $('#testtn').reel({ 
        speed:.3, 
        indicator:5, 
        images: ["http://orscella.com/images/testtn/00001.png", ... ,"http://orscella.com/images/testtn/00176.png"] 
    });
});
//]]>
< /script >

If you check this out in FF or IE (via the link above) its rotating fine, but with no indicator and all the images in the reel rendering on the page... Is there any css that I should be including?

Cheers

**Comment by lopsided** [comment]
Ive got it working! Many thanks to pelister and pisi for their help on this. There were two problems with my test page. The first (which fixes the code in the previous comment) was to add

< style type="text/css" > < /style > 

to the head. On my actual site I did not need this for some reason. Maybe because I have stylesheet links then IE has already fired up the CSS handlers...?

In my test page my image had id="360-image". This was also no good in IE, had to change this to id="image360". I also removed the mousewheel.js and it still worked, since I did not need any mousewheel behaviour on my site.

In the end the only things that needed changing on my site was to switch to the latest devel reel release and change the image id.

Again, thanks to pelister and pisi.

**Comment by pisi** [comment]
First to answer your question: no, the mousewheel plugin is not needed to get Reel running. It's just fine without it.

I know now! You've tapped it @lopsided, thanks! Reel keeps some its styling rules in a dynamically injected stylesheet in the head. The `<style>` is injected [here](/pisi/Reel/blob/development/jquery.reel.js#L332) before all other styles to allow easy CSS overide by user without the `!important` enforcement. And I foolishly presumed, that all pages have some stylesheet in one way or another already. I think, I'd rather change the already-awkward:

``` js
... .insertBefore($('head link, head style').first());
```

and simply prepend the stylesheet to the `<head>` not caring about what's inside:

``` js
... .prependTo('head');
```

It would be much cleaner then, but at the same time far too prominent when viewing the source code. But I guess that's the price it has to pay to sit below all other styles no matter what ;)
