### ISSUE TITLE
Vertical scrolling on iPhone disabled even when scrollable is set to true

### ISSUE THREAD

**Issue by bobbymarko** [pisi/Reel#85]
I'm using Reel on a mobile site and the 360 viewer takes up the full width of the site. So you end up not being able to scroll down the page because when your thumb hits the Reel object the touchmove event returns false. I hacked in on my local copy a check to see if the touch move is vertical or horizontal and to only return false on a horizontal move and it solves the problem. My particular solution isn't written well so I won't burden you with a pull request ;)

**Comment by pisi** [comment]
Cool! Good for you, Bobby!

Let me point out however, that this duplicates #60.

**Comment by bobbymarko** [comment]
Sorry about that, I looked through the open issues quickly and didn't see it. I'll look closer next time!
