### ISSUE TITLE
still one more conflict

### ISSUE THREAD

**Issue by pelister** [pisi/Reel#88]
jquery 1.6.4
jquery.reel  - from latest development branch
mousewheel 3.0.2

works fine on all browsers. (IE 8 -  mouse drag do not work , but mousewheel works.)
works fine along with mootools.

---

Jquery 1.6.4
jquery.reel  (http://code.vostrel.cz/jquery.reel.js)  Version: 1.1.3  Updated: 2011-05-08
mousewheel 3.0.2 

works fine on all browsers with all features (mouse drag and mouse wheel)
but this version of jquery.reel has conflict with mootools (sliding behaviour of reel).

---

used Jquery  1.7.1 - does not work with IE8 - reel is not playing the sequence.  works fine with other browsers.

**Comment by pisi** [comment]
Thanks for the detailed report!

I've just pushed the [development](/pisi/Reel/tree/development) branch, which should be fairly cool with IE. I've verified on Windows 7 in IE 8.0 and 9.0 against 1.6.4 and 1.7.1 with mousewheel 3.0.6. Please, verify on your setup please.

**Comment by pelister** [comment]
Amazing Job Pisi.

Jquery -1.7.1
Jquery.reel  - latest dev branch (Version: 1.1.3-devel  Updated: 2011-12-17)
Mousewheel 3.0.6

Win XP
tested browsers : Firefox 8, Opera 11,  Chrome recent edition, IE 8, safari 5.1

Everything works fine.

Reel sequence plays fine, mouse functions drag and mousewheel works fine on all above mentioned browsers. It must also work on all other browsers.

Thanks to Pisi and everyone who have developed this wonderful Jquery Plugin.

**Comment by pelister** [comment]
one more problem with the latest development branch.

Jquery.reel - latest dev branch (Version: 1.1.3-devel Updated: 2011-12-17)

stop button does not works as soon as the page loads, but works after we perform other actions like (mouse drag, mousewheel or clicking on the pause button ). only pause button works as soon as the page loads. stop works only after performing other actions. (same for every browser.)

**Comment by pelister** [comment]
conflict with mootols on opera.

Jquery.reel - latest dev branch (Version: 1.1.3-devel Updated: 2011-12-17)
Jquery 1.7.1
mousewheel 3.0.6

still has the sliding behaviour only on opera. other browsers work fine.

here is the link if you like to take a look

http://orscella.com

**Comment by pelister** [comment]
sorry for the above report

Jquery.reel - latest dev branch (Version: 1.1.3-devel Updated: 2011-12-17)
Jquery 1.7.1
mousewheel 3.0.6

Conflict with mootools was because of browser cache.. I dint refresh with the new jquery.reel... my bad...

Opera and other browsers tested works fine with mootools.

but still the problem with the stop button persists in all browsers.

**Comment by pisi** [comment]
Reel itself triggers the `"stop"` event when it starts preloading frames, so there's no need to trigger it manually.

If you want to prevent Reel from animating, you should be able to bind to `"loaded"` event, which is eventually fired by the Reel instance and trigger `.trigger('stop')` in the handler. You may also need to stop propagation of the event by returning `false` from the handler.

``` js
$('#my_image').reel({
    speed: 1.23
}).bind('loaded', function(e){
    $(this).trigger('stop');
    return false;
});
```

**Comment by pisi** [comment]
I recon this issue was about jQuery/Mootools conflict, which got resolved by clearing the browser's cache, so am closing it. Thanks a bunch for testing!
