### ISSUE TITLE
`speed` data access

### ISSUE THREAD

**Issue by pisi** [pisi/Reel#9]
For changing a 'speed' option value, one needs to teardown the current Reel instance and run a new one. Let's add something like a "speedChange" event and be able to change the speed on-the-fly without the teardown

**Comment by doa4real** [comment]
actually this could be a nice function that later could be connected to some jquery slider.

**Comment by pisi** [comment]
I believe the current code in development branch already supports DOM data-based `speed` persistence, so if you do:

```
$("#my_image").data("speed", 2); // Any new speed
```

any new speed is applied immediately on the running Reel instance.

Similarily one can get current speed with:

```
$("#my_image").data("speed");
```

So, speed control using a slider should be at all possible.
