### ISSUE TITLE
Gyroscope support

### ISSUE THREAD

**Issue by arathael** [pisi/Reel#92]
How about detecting gyroscope for natural rotation sliding?

**Comment by pisi** [comment]
Very nice suggestion indeed! I'm however afraid, that such hardware values are not yet available to Javascript in browsers (but I may as well be mistaken, please correct me if so). I will therefore label this ticket as **unlikely** and we will see what the future will bring in terms of browsers' accelerator APIs.

However in a PhoneGap (or similar) situation, it should already be possible to bind the accelerometer to Reel control events like `"frameChange"`.

**Comment by arathael** [comment]
In fact, this info is already available to javascript in browsers. I used your reel plugin in here (http://www.adidas360.com/player-65.html) and take a look at the code and the page in iOS with gyroscope (iPad2 or iPhone 4/4s)

**Comment by pisi** [comment]
Interesting 8) Thanks for making me aware of this! Well, feature it is then ;)

**Comment by pisi** [comment]
Ok, so I've added `orientable` option, which is disabled (`false`) by default. When enabled (`true`) and on a compatible device, it will tie the alpha angle (compass) to Reel's `fraction` value.

Code is available in [**gyroscope** branch](/pisi/Reel/tree/gyroscope) for testing.

However, this support is very preliminary and basic shall I say. More configuration is required to work well with non-looping panos and to enable the same for the vertical axis too.

**Comment by pisi** [comment]
Merged into [development branch](/pisi/Reel/tree/development) awaiting release in version 1.3

**Comment by pisi** [comment]
Released today as part of [v1.3.0](/pisi/Reel/tree/v1.3.0)
