### ISSUE TITLE
Image reel won't load on IE 9

### ISSUE THREAD

**Issue by vinamelody** [pisi/Reel#93]
Helo, I read about some IE issues before, and still couldn't figure out the solution for my case.

I'm embedding panorama reel on wordpress page but in IE 9.0.8112 to be specific, somehow the panorama isn't scrolling right.
The webpage is at www.projectdignity.sg/facilities
When I test on Android's browser works fine except for Dolphin however few ppl use it. I think Safari should be good.

Thank you in advance.

**Comment by sebhaase** [comment]
Hi, I just fixed an IE problem on my version of reel (based on reel 1.1.3).

I found (http://help.dottoro.com/lhhnbecg.php) that IE is special in that it defines the 'start' attribute for each IMG element.
(its value is "fileopen" -- and consequently reel fails with saying, "elem[type] not callable" )

My fix was to rename the "start" function (used in trigger("start")) to "startreel"

I'm not sure if this fixes your problem and/or if it is dealt with in the current dev version of reel....

Cheers, HTH,
Sebastian Haase

**Comment by pisi** [comment]
Yeah, @sebhaase is indeed right. IE has it's start thing going, which forced me to remove the start event from the next version alltogether.

**Comment by vinamelody** [comment]
hi @sebhaase , thanks a lot for the tips ..now things work perfectly :)
thanks everyone appreciate it.

Cheers

**Comment by pisi** [comment]
Reel internally uses `"start"` event, which is not available for free use anymore in IE since jQuery 1.7. Until [Reel 1.2](/pisi/Reel/issues?milestone=4) is released (soon) you have two options. Either use jQuery 1.6.x or patch the source yourself by replacing the word `start` [here](/pisi/Reel/blob/master/jquery.reel.js#L209) and [here](/pisi/Reel/blob/master/jquery.reel.js#L242) with some other word (for example `startreel` proved effective to @sebhaase).

**Comment by pisi** [comment]
Please be aware that Reel 1.1.x has been patched to work just right with jQuery 1.7 in IE - fixes init-time error (like this one) and wheel issues. Released as [Reel 1.1.4](/pisi/Reel/tree/v1.1.4).

Note, that you must also upgrade your copy of the mousewheel plug-in with the included version [3.0.6](/brandonaaron/jquery-mousewheel/tree/3.0.6). The one shipped with Reel 1.1.3 (mousewheel 3.0.4) was also jQuery 1.7 incompatible.

**Comment by sumitpaul** [comment]
I have Reel 1.2 and jquery 1.7.1, but it still doesn't seem to work in IE 9. Can you please take a look? http://conduitprojects.com/work/airframe-helmet/
