### ISSUE TITLE
Annotation examples for Reel

### ISSUE THREAD

**Issue by cyndyl** [pisi/Reel#94]
I would like to test out the new annotation features of Reel.  Could you please post some examples?  Thank you very much for this excellent work!

**Comment by pisi** [comment]
Working on it. There sure will be examples once the code is released.

**Comment by pisi** [comment]
I've put several annotations into some [examples](/pisi/Reel/tree/v1.2beta/example) illustrating some annotation features - namely into:
- [object-movie-clockwise-sprite](/pisi/Reel/tree/v1.2beta/example/object-movie-clockwise-sprite)
- [object-movie-dual-orbit-sequence](/pisi/Reel/tree/v1.2beta/example/object-movie-dual-orbit-sequence)
- [object-movie-multi-row-sequence](/pisi/Reel/tree/v1.2beta/example/object-movie-multi-row-sequence)
- [panorama-non-looping-stitched](/pisi/Reel/tree/v1.2beta/example/panorama-non-looping-stitched)

I plan to put more for the 1.2 release, but this would do it for the 1.2 Beta, I hope. Also see the [Annotations](/pisi/Reel/wiki/Annotations) for documentation.

You also can see them live at http://test.vostrel.cz/jquery.reel/example (those with annotations are marked with asteriks).

**Comment by pisi** [comment]
Looks like enough for the 1.2 release after all. I'm still pretty much open to any suggestions for examples or even to working examples to include in the set.
