### ISSUE TITLE
jQuery 1.7 with IE7/8

### ISSUE THREAD

**Issue by gnesher** [pisi/Reel#95]
Reel breaks when running using jQuery 1.7 (and up).
Giving the following error : Object doesn't support this action
Line 3175 (jQuery 1.7 non minified)

Seems to work fine on other browsers (tested on Chrome/FF/Safari).

Any ideas how to solve this ?

**Comment by pisi** [comment]
Hi @gnesher, please head to issue #93 for explanation and hints for a temporary solution. Sorry for inconvenience.

**Comment by gnesher** [comment]
Thanks, works like a charm.

**Comment by pisi** [comment]
Please be aware that Reel 1.1.x has been patched to work just right with jQuery 1.7 in IE - fixes init-time error and wheel issues. Released as [Reel 1.1.4](/pisi/Reel/tree/v1.1.4).

Note, that you must also upgrade your copy of the mousewheel plug-in with the included version [3.0.6](/brandonaaron/jquery-mousewheel/tree/3.0.6). The one shipped with Reel 1.1.3 (mousewheel 3.0.4) was also jQuery 1.7 incompatible.
