### ISSUE TITLE
Plugin causes a javascript error in IE7 with jQuery 1.7

### ISSUE THREAD

**Issue by LaurentGoderre** [pisi/Reel#98]
When using the plugin with jQuery 1.7 I get an error in IE7 but not in Firefox. I isolated the problem down to this:

Line 209 is the following : 

t.trigger('start');

It seems that in IE7 for some reason my image already hasd a property called 'Start' which in my case was set to 'fileopen'. This caused a jQuery level error (trying to trigger an property as an event). I fix the problem by doing the following (which was only for debugging, I know its probably not the ideal fix)

Change Line 209 to 

t.trigger('start2');

Change Line 242 to

start2: function(e){

**Comment by pisi** [comment]
Hi @LaurentGoderre, please head to issue #93 for explanation and hints for a temporary solution. Sorry for inconvenience.
Btw. You are absolutely right ;)

**Comment by pisi** [comment]
Please be aware that Reel 1.1.x has been patched to work just right with jQuery 1.7 in IE - fixes init-time error (like yours) and wheel issues. Released as [Reel 1.1.4](/pisi/Reel/tree/v1.1.4).

Note, that you must also upgrade your copy of the mousewheel plug-in with the included version [3.0.6](/brandonaaron/jquery-mousewheel/tree/3.0.6). The one shipped with Reel 1.1.3 (mousewheel 3.0.4) was also jQuery 1.7 incompatible.
