### ISSUE TITLE
Play to frame X and then stop.

### ISSUE THREAD

**Issue by NilsHolmstrom** [pisi/Reel#99]
I would like to for example press a link with a data-value of "50" and then play the reel to that frame, not only jump to it.

I suppose this feature is already supported via the "play" and "frameChange"-events, but I can't seem to find any good examples...

**Comment by pisi** [comment]
By the closed status I judge you did find a solution for this by yourself. In case you didn't or for anyone else to see how this is made, I answered this exact [same question at stackoverflow.com](http://stackoverflow.com/questions/9277332/how-to-play-jquery-reel-to-a-specific-frame-and-stop-there/9444676#9444676).

I plan to add built-in support for such a function. Something like playTo or analogous to opening animation, a [closing animation (#90)](/pisi/Reel/issues/90) is in question. I'm just not sure yet how to put this in neatly.

Please watch the #90 issue as this one basically duplicates it. Thx.
